### ISSUE TITLE
Multi node - worker/control-plane setup fails

### ISSUE THREAD

**Issue by patvdleer** [kubernetes-sigs/kind#1020]
**What happened**:
```
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
I1029 15:49:02.096728     575 round_trippers.go:438] POST https://172.17.0.3:6443/api/v1/namespaces/kube-system/configmaps  in 0 milliseconds
error execution phase control-plane-join/update-status: error uploading configuration: unable to create ConfigMap: Post https://172.17.0.3:6443/api/v1/namespaces/kube-system/configmaps: EOF 
 ✗ Joining more control-plane nodes 🎮
Error: failed to create cluster: failed to join node with kubeadm: exit status 1
```

**What you expected to happen**:
Basic create

**How to reproduce it (as minimally and precisely as possible)**:
`kind create cluster --wait 300s --config config.yaml --name kind-test --retain --loglevel debug`

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
```

**Anything else we need to know?**:
[kind.log](https://github.com/kubernetes-sigs/kind/files/3784508/kind.log)

**Environment:**

- kind version: (use `kind version`): `v0.5.1`
- Kubernetes version: (use `kubectl version`): `v1.16.2`
- Docker version: (use `docker info`): `19.03.4`
- OS (e.g. from `/etc/os-release`): `Ubuntu 18.04.3 LTS`

**Comment by patvdleer** [comment]
It seems like an issue on the VPS side, cleaning up and testing it again now raises disk space issues while have 60G to spare... sorry to have wasted your time..

**Comment by ereslibre** [comment]
I have been getting this issue recently with a [kind patch that lowered timeouts for HAProxy](https://github.com/kubernetes-sigs/kind/compare/master...ereslibre:low-timeout) -- to test some things.

The fix is merged now: https://github.com/kubernetes/kubernetes/pull/85763.

I could reproduce almost everytime with the linked kind patch, always with several control plane instances (as the problem always showed up when trying to create and then update the `kubeadm-config` ConfigMap when joining new control plane nodes).

With https://github.com/kubernetes/kubernetes/pull/85763 I have been unable to reproduce again.

**Comment by BenTheElder** [comment]
thanks @ereslibre !
