### ISSUE TITLE
Improve project community profile

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1112]
**What would you like to be added**:

- [x] Code of conduct

- [ ] Pull request template

**Why is this needed**:

In order to fulfill the recommended community standards

https://github.com/kubernetes-sigs/kind/community

**Comment by BenTheElder** [comment]
so, we have a code of conduct, github just does not recognize it.

**Comment by BenTheElder** [comment]
a pull request template is not particularly helpful for this project, the community "standards" are unfortunately not very helpful.

ALL kubernetes projects "fail to meet the standards" because the code of conduct check matches exact text from ~2 choices github will give you when creating a project

this is a github bug, and well known. we've spoken to them about it.
