### ISSUE TITLE
delete cluster failed as unknown command

### ISSUE THREAD

**Issue by mshahat** [kubernetes-sigs/kind#1145]
Hello, 

I'm trying to delete a cluster but i am receiving the following error. 

```shell
~ ❯❯❯ kind get clusters
cka1-16
~ ❯❯❯ kind delete cluster cka1-16
ERROR: unknown command "cka1-16" for "kind delete cluster"
~ ❯❯❯ kind version                                                                                                                                                                            ✘ 1 
kind v0.6.1 go1.13.4 darwin/amd64
~ ❯❯❯ 
```

And i am on macOS `10.15.1 (19B88)`

Many thanks,

**Comment by BenTheElder** [comment]
Hi, you want `kind delete cluster --name=cka1-16`

**Comment by mshahat** [comment]
That's right. thanks! 
not very natural though, but my mistake not going through the help in details. 

Thanks v. much

**Comment by BenTheElder** [comment]
Yeah I get that, it's mostly been about consistency across all the commands
and being able to have a default, similar to minikube's --profile.

I think we might want to add a `kind delete clusters [name1 name2 ...]` or
something like that and maybe let this command take --name optionally as an
argument instead.

We're also going to add an environment variable that can be used instead of
--name.
