### ISSUE TITLE
Ship a working storageclass

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kind#1151]
**What would you like to be added**:

We would like KIND to create a working storageclass by default.

**Why is this needed**:

We build a few Kubernetes operators. We would like to update our documentation so that users use KIND instead of Minikube as a test/dev Kubernetes setup in case they don't have one. Here is an example: https://github.com/stashed/docs/pull/54

One of the blockers for us is that KIND does not come with a working storageclass. We had success with Rancher's local provisioner. This is what we do internally. https://github.com/appscodelabs/e2e-test-setup/blob/kind-v0.6.1/run.sh

Obviously we could point our users to our custom docs for how to setup KIND, but it will be nice it KIND could ship a working storageclass solution.

**Comment by BenTheElder** [comment]
This is the dynamic volume provisioning issue.
We're revisiting it this week.

**Comment by tamalsaha** [comment]
Cool! Here is the script we are using now (also updated in the original post): https://github.com/appscodelabs/e2e-test-setup/blob/kind-v0.6.1/run.sh

**Comment by mkarimawan** [comment]
Hi @tamalsaha, just wondering why couldn't you use default sc that ships with k8s ? It works find with Kind on local host.

**Comment by tamalsaha** [comment]
I don't remember it now. But we were creating a 3 node cluster and using dynamic provisioning. Something there did not work. If the default/built-in storageclass works, then that is even better.

**Comment by BenTheElder** [comment]
the built in one (installed by kind) from k8s.io/hostpath built in driver has a few issues, namely that it requires containers to have UID=0, because it's based on the `hostPath: ...` driver for which it would be a violation of the security model to support non-root so upstream k8s does not respect fsgroup

this one alone is a big problem.

this, host restarts, user defined networks, and registries are on my near term list, in that order, other than ongoing maintenance stuff etc...
