### ISSUE TITLE
Why not use `PullIfNotPresent` instead of `Pull` method while building node image?

### ISSUE THREAD

**Issue by jiatongw** [kubernetes-sigs/kind#1266]
Hi, I recently try to build node image myself and found an interesting thing: I pre-loaded images like `etcd`, `coredns` that out of `bazel build` range. But kind does not use pre-loaded images, instead, it pulls from upstream ignoring loaded images - according to this line 
https://github.com/kubernetes-sigs/kind/blob/master/pkg/build/node/node.go#L455
it calls `docker.Pull()` method.  

But I also see a `PullIfNotPresent()` method (https://github.com/kubernetes-sigs/kind/blob/master/pkg/build/node/internal/container/docker/pull.go#L29)

I want to know that why don't use `PullIfNotPresent()` while building node image?

**Comment by aojea** [comment]
`docker.Pull()` executes `docker pull`in the host and AFAIK it doesn't download the images if there is one in the local host.
Better if @BenTheElder can confirm, but if you have the images in your local `docker`storage, kind will use those images to create the `nodes`

**Comment by BenTheElder** [comment]
> I pre-loaded images like etcd, coredns that out of bazel build range.

Can you elaborate on "pre-loaded"?

> But kind does not use pre-loaded images, instead, it pulls from upstream ignoring loaded images - according to this line

Aside for anyone else finding this issue: `kind build node-image` preloads images _into the node image_, at runtime `kind create cluster` will not be pulling from GCR etc. and we also refer to this as "preloading".


> I want to know that why don't use PullIfNotPresent() while building node image?

`PullIfNotPresent` is most suitable when you're fully specifying the image (as users ideally do when using node images, including the hash). 

The concern during node image build is that if the upstream image tags have been mutated (due to E.G. a botched release, which just happened for some of kubernetes...).

In that case we want to make sure we pull the new ones since the caller is not aware of the list of images (whereas with `kind create cluster` we're either using an exact image with a hash or the user specified it and can pull themselves). Similar to `docker build --pull`.

Note that while we do always pull during image build we don't fail if pulling failed, we just attempt to update it.

https://github.com/kubernetes-sigs/kind/blob/ee60ced0d14cde918a87cbc2bfe4ececd86e37fd/pkg/build/node/node.go#L454-L458

**Comment by BenTheElder** [comment]
Do you have a case where ignoring pull failure is not sufficient?

**Comment by BenTheElder** [comment]
closing for now due to lack of follow up
