### ISSUE TITLE
service ips

### ISSUE THREAD

**Issue by jjangga0214** [kubernetes-sigs/kind#1272]
Hi. 

Is there a way to get service ip or url, that can be accessed externally(e.g. from local machine running Kind to service in the cluster)?

`minikube service foo --url` returns something like "http://192.168.99.108:30568", for example.

Thanks in advance!

**Comment by BenTheElder** [comment]
on mac / windows docker containers are not routable from the host.
given that limitation, we don't have a feature like this.

however, you can use something like `kubectl proxy` or `kubectl port-foward`

additionally, if you are on linux you can add a route for the service IP range to go through the node IP and then you can access the service IPs directly, but this is not possible on mac / windows at the moment due to the docker limitation

**Comment by BenTheElder** [comment]
@aojea had a neat one-liner for this on linux

**Comment by aojea** [comment]
hehe, is a bit hacky but it does the work
https://github.com/kubernetes-sigs/kind/issues/702#issuecomment-573427905
