### ISSUE TITLE
How to pass extra arguments to docker run?

### ISSUE THREAD

**Issue by mtatheonly** [kubernetes-sigs/kind#1284]
How can I pass extra arguments to docker run, like a network to join? Or to provide a network name other than "bridge" for the nodes? I'm having some issues regarding external docker-compose containers and kind nodes.

**Comment by BenTheElder** [comment]
You can't, but even if you could, using a different network would break kind currently because docker has breaking behavior on non default networks.

We're working on configurable networks, TLDR it requires some DNS workarounds and we're trying to solve the host reboot problem while we're at it  I have a partial implementation punted until the current in flight PRs are complete.

**Comment by BenTheElder** [comment]
#273
