### ISSUE TITLE
Kind does not save images it just built and tagged

### ISSUE THREAD

**Issue by applike-ss** [kubernetes-sigs/kind#1373]
**What happened**:
i used devspace in combination with kind to run a temporary local kubernetes cluster within docker.
`devspace dev -b` does build docker images and tags them right away, so i assumed that devspace would be able to use those tagged images afterwards. Using minikube that worked Out of the box.

**What you expected to happen**:
Tagged images should be available to kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:
```
kind create cluster
devspace -n dev dev
#image building/tagging happens
kind delete cluster
```

**Anything else we need to know?**:

**Environment:**
local development
- kind version: 0.7.0
- Kubernetes version: v1.17.0
- Docker version: 19.03.5
- OS: Ubuntu 18.04

**Comment by BenTheElder** [comment]
This is not a bug.
kind supports multi node and multi cluster, in order to have images in the cluster they must be populated into the container runtime in the relevant nodes.

minikube does NOT have your docker images out of the box unless you use `minikube docker-env` (only works for one single node cluster) OR if you use --vm-driver=none which is roughly `kubeadm init` directly on the host.

Please see the docs for how to use kind with images

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

https://kind.sigs.k8s.io/docs/user/local-registry/

**Comment by BenTheElder** [comment]
I've never used devspace but it purports to support kind for what it's worth. https://github.com/devspace-cloud/devspace/blob/master/README.md#4-choose-a-kubernetes-cluster

**Comment by applike-ss** [comment]
It does only make limited sense to me:
Kubernetes is able to build an image, so it should have it locally when it was build.
Can i configure kind to use my local docker daemon?

**Comment by BenTheElder** [comment]
> Kubernetes is able to build an image, so it should have it locally when it was build.

Kubernetes does not support image building actually, the normal expectation is that images are pulled from a registry. I'm not sure what you're referring to here.

> Can i configure kind to use my local docker daemon?

Unfortunately not, though if you are on linux and want to do this the answer is probably `kubeadm init`.

the initial design may help in understanding, there is an entire kubernetes node in each node container. this includes a container runtime.

https://kind.sigs.k8s.io/docs/design/initial/
https://kind.sigs.k8s.io/docs/user/resources/

see also:
https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
https://kind.sigs.k8s.io/docs/user/local-registry/
https://kind.sigs.k8s.io/docs/user/private-registries/

**Comment by BenTheElder** [comment]
when we started it looked like 
![image](https://user-images.githubusercontent.com/917931/75698691-00e95c80-5c64-11ea-880a-3c7732cb5941.png)

where there might be arbitrarily many node containers. it's changed a little since then but that still gives some idea of the layers involved in pulling this off. while your images are in the host docker when you `docker build`, they are not in the nested ones. the on-disk docker structures are not made for sharing between multiple instances.
