### ISSUE TITLE
customize the master and worker nodes name

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes-sigs/kind#1401]
With simple command, I can create kubernetes cluster easily,

```
$ more kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

But the master and worker node names are not as I set, it has prefix `kind-*` automatically, and have to be `kind-control-plane*` or `kind-worker*` how to rename them?
```
$ kubectl get node
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   11m   v1.17.0
kind-worker          Ready    <none>   10m   v1.17.0
kind-worker2         Ready    <none>   11m   v1.17.0
```

I'd like to set the name to 

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: master
- role: node01
- role: node02
```
But it doesn't work
```
$ kind create cluster --config kind-config-1.yaml
Creating cluster "kind" ...
invalid configuration for node 0: "master" is not a valid node role
invalid configuration for node 1: "node01" is not a valid node role
invalid configuration for node 2: "node02" is not a valid node role
must have at least one control-plane node
ERROR: aborting due to invalid configuration
```

So I want to customize the cluster name as below: 
```
$ cat kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  name: master
- role: worker
  name: node01
- role: worker
  name: node02
```
Obviously, this feature with `name` isn't supported currently

Any hints for me?

**Comment by aojea** [comment]
the problem I see with that approach is that you may have collisions with the naming.

**Comment by BenTheElder** [comment]
It's not currently supported but it's something we're _considering_ for v1alpha5, I think we're more likely to focus node label support though.

Relying on node names is an anti pattern... What exactly are you depending on them for?

**Comment by 0xVox** [comment]
> It's not currently supported but it's something we're _considering_ for v1alpha5, I think we're more likely to focus node label support though.
> 
> Relying on node names is an anti pattern... What exactly are you depending on them for?

I found this after trying to do the same. 

Although I will encourage the team to avoid relying on them and move to labels - we have some nodeSelector's that rely on the hostname.

As a broader solution, would it be possible to expose the docker args that are run with the node containers, then we could use the -h flag? Or would that cause other issues?

**Comment by BenTheElder** [comment]
>Although I will encourage the team to avoid relying on them and move to labels - we have some nodeSelector's that rely on the hostname.

understandable, we'll look at node names again in the next API.

>As a broader solution, would it be possible to expose the docker args that are run with the node containers, then we could use the -h flag? Or would that cause other issues?

we're not exposing setting docker flags intentionally because we have multiple backends (e.g. podman) and the docker CLI is not 100% stable, we reserve the right to switch to the docker API instead of CLI in the future.

**Comment by nadenf** [comment]
@BenTheElder 
> Relying on node names is an anti pattern... What exactly are you depending on them for?

For me it's as simple as I have different nodes doing different things and want to distinguish them via a UI like Lens.

**Comment by BenTheElder** [comment]
Note that for local development with kind it's all running on the same shared kernel, memory, cpu.

Unless you're tainting / labeling nodes for some special reason or testing rolling behavior across nodes (why we implemented this, to test kubernetes itself) having different nodes doing different things is also superfluous at the moment. Worse, the overhead of each node is non-zero.

They should be possible to tell apart via the labels / taints and existing distinct names ..
You're also unlikely to have many nodes to tell apart locally.

---

Regarding node selectors, you should likely use a label selector instead of a name selector. It's far more portable and less brittle (e.g. Managed offerings are not going to let you name nodes, but you can still label them, for example). Even if you want to do a single node selected you can just label one node with a particular value, this should be pretty easy to do on just about any cluster.

For more on doing this, see the official Kubernetes docs for ["Assigning Pods to Nodes"](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/)

I'd prefer to not add complexity to our stack in order to enable anti-patterns. `container name == hostname == kubernetes node name` has also avoided a lot of confusion both in the code and with users.

for now, closing this.

**Comment by BenTheElder** [comment]
I appreciate the input and understand the use cases, but I think these can be better served via other means. Thanks all.

**Comment by nadenf** [comment]
@BenTheElder  .. Just so you understand how some of us are using kind:

So I have 6 different types of worker nodes with typically around 10 nodes needed for us to run our full CI suite. We are definitely using label selectors but it would just be nice to name the workers. If you are using kubectl, Lens etc they just show this which makes it cumbersome to use:

```
kind-control-plane   Ready    master   4h45m   v1.17.0
kind-worker          Ready    <none>   4h44m   v1.17.0
kind-worker2         Ready    <none>   4h44m   v1.17.0
kind-worker3         Ready    <none>   4h44m   v1.17.0
kind-worker4         Ready    <none>   4h44m   v1.17.0
kind-worker5         Ready    <none>   4h44m   v1.17.0
kind-worker6         Ready    <none>   4h44m   v1.17.0
kind-worker7         Ready    <none>   4h44m   v1.17.0
kind-worker8         Ready    <none>   4h44m   v1.17.0
kind-worker9         Ready    <none>   4h44m   v1.17.0
kind-worker10         Ready    <none>   4h44m   v1.17.0
```

Also not sure why it should add much complexity. Just have an internal id that you reference nodes within kind by and a public name.

**Comment by BenTheElder** [comment]
It's true that `kubectl get nodes` only shows those fields. However you can do something like `kubectl -get no -o wide`. Lens probably ought to surface this sort of information...

The same argument applies to other types of clusters and they seem fine with it. All of the major providers provide only automatically named nodes. Ditto for our other test cluster tools (e.g. kube-up). 

In fact, I don't think any of the tools in the Kubernetes upstream ecosystem support this (kops, cluster-api, kubespray, ...). Automated naming is the defacto standard.

> Also not sure why it should add any complexity. Just use the name for the hostname, node, container etc and it should work exactly the same.

_Any_ feature adds complexity and support costs. It's not obvious that this one is worth any.

10 nodes is a lot for kind currently. What are you doing that needs workloads on 10 different nodes, out of curiosity?

**Comment by voltbit** [comment]
> What are you doing that needs workloads on 10 different nodes, out of curiosity?

For example, testing a system that spreads and balances instances on multiple AZs/regions can lead to many nodes. To test a config with just 3 AZs and 3 nodes per AZ you get to a 10 node Kind cluster.

**Comment by xh3b4sd** [comment]
This issue should not have been closed. Letting people name their nodes should not be rocket science. There are probably a lot of people who want to have control over node names so I do not understand why this is still not solved. Feels like one of these issues in vsCode where 15 million user-working-hours went down the drain because a hand full of people decided it is not reasonable to adjust the font size in the explorer.

**Comment by BenTheElder** [comment]
See all previous discussion 🤷‍♂️

No workloads should depend on node names. We're not interested in expending our resources to enable non portable options when the portable solution exists (node labels and selectors), we'll have native support for labeling in config in the next release. Lots of much bigger cluster providers don't support this and none of them need to.

**Comment by nadenf** [comment]
[AWS is proposing to support it](https://github.com/aws/containers-roadmap/issues/781) and it is the one of the most popular requests.

We use node labels/selectors everyday but they are not a replacement for this especially when it comes to testing.

**Comment by BenTheElder** [comment]
https://github.com/aws/containers-roadmap/issues/781 is about having names based on the node group be tagged on the ec2 instances, not about user control of individual node names. The behavior described there is precisely what tools like kind do: given a set of nodes names are assigned automatically based on other parameters.

That issue is also about the AWS side of things, the node objects at the Kubernetes level must already be named.

**Comment by nathanblair** [comment]
> See all previous discussion man_shrugging
> 
> No workloads should depend on node names. We're not interested in expending our resources to enable non portable options when the portable solution exists (node labels and selectors), we'll have native support for labeling in config in the next release. Lots of much bigger cluster providers don't support this and none of them need to.

> "Big companies don't do this thus the rest of the world shouldn't need to

That sounds like a pretty hamstrung argument to make. Maybe `kind` isn't the tool for general purpose clustering, then? That may be me misunderstanding the intent of `kind`.

I, luckily, do not have a strict need for naming nodes (at least, not a use-case yet), but its sad to see this sort of feature being dismissed so easily.

Are node `names` less portable than node `labels`? Is one more `docker`-centric than the other? Genuinely asking, I'd gladly embrace a portable solution as long as its not coupled with "because that's what Google does".

**Comment by aojea** [comment]
> Maybe `kind` isn't the tool for general purpose clustering, then? That may be me misunderstanding the intent of `kind`.

https://kind.sigs.k8s.io/docs/contributing/project-scope/

**Comment by nathanblair** [comment]
> > Maybe `kind` isn't the tool for general purpose clustering, then? That may be me misunderstanding the intent of `kind`.
> 
> https://kind.sigs.k8s.io/docs/contributing/project-scope/

https://kind.sigs.k8s.io/docs/contributing/project-scope/#p1-support-testing-kubernetes-applications

**Comment by BenTheElder** [comment]
> > "Big companies don't do this thus the rest of the world shouldn't need to"

Please don't place a false quotations like this and / or presume our motivations & intentions.
We've been very clear about this. **NONE** of the cluster provisioning tools in the Kubernetes project have user defined node names. **ALL** of them automatically name nodes out of groups of nodes. This includes:
- [kops](https://github.com/kubernetes/kops)
- [kubespray](https://github.com/kubernetes-sigs/kubespray)
- [Cluster API](https://github.com/kubernetes-sigs/cluster-api)
- [kube-up.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh)

These tools do not represent "big companies". 
With the exception of Cluster API I'm not personally aware of anyone working on these at a large company for their dayjob.

Further, this is not how any of the production cluster offerings we've looked at work, and they're mentioned because *if* this was widely portable to production, then we might be interested, even if it's still going to couple applications to "pet" nodes, which is a discouraged practice.

From https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

"[...] **the recommended approaches all use label selectors to make the selection**. Generally such constraints are unnecessary, [...]"

> That sounds like a pretty hamstrung argument to make.

I don't know how to respond to this. Presumably you have an argument you're not at all attempting to present about why this feature does need to exist. 

> Maybe kind isn't the tool for general purpose clustering, then? That may be me misunderstanding the intent of kind.

No, it isn't for general purpose clustering.
We've been extraordinarily clear about this. Here is the first two lines of the [README.md](https://github.com/kubernetes-sigs/kind/blob/main/README.md):
> kind is a tool for running local Kubernetes clusters using Docker container "nodes".
> kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.

Do not use kind for general purpose clusters. KIND is for disposable testing with local test clusters.
The same text is present on our homepage at https://kind.sigs.k8s.io.


> Are node names less portable than node labels? 

Yes. Nearly all options for creating a Kubernetes cluster give you little to no control over node names. Nodes are disposable and workloads are expected to shift around across nodes over time.

> Is one more docker-centric than the other? 

This issue has no relation to docker, other than kind may use it (or podman).

> Genuinely asking, I'd gladly embrace a portable solution as long as its not coupled with "because that's what Google does".

Happy to help with that. Please see:
See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

However:
> [...] "because that's what Google does". [...]

This is not "that's what Google does", nobody said that in any way, shape, or form.

This is what the Kubernetes project / ecosystem considers best practice. As such we've shipped https://github.com/kubernetes-sigs/kind/issues/1574 to make this easier to do in the next release.

**Comment by ghislain-bernard** [comment]
A proposal solution with overloaded names :
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster
nodes:
  - extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: 127.0.0.1
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
          name: control
    role: control-plane
  - labels:
      color: blue
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: worker-blue
    role: worker
  - labels:
      color: red
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: worker-red
    role: worker
  - labels:
      color: white
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: worker-white
    role: worker
```

Results :
```console
$ kubectl get nodes worker-blue --output=yaml | grep blue
    color: blue
    kubernetes.io/hostname: worker-blue
  name: worker-blue
  - address: worker-blue

$ kubectl get nodes control --output=yaml | grep control
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
    kubernetes.io/hostname: control
    node-role.kubernetes.io/control-plane: ""
  name: control
  providerID: kind://docker/cluster/cluster-control-plane
    key: node-role.kubernetes.io/control-plane
  - address: control
    - registry.k8s.io/kube-controller-manager-amd64:v1.33.1
    - registry.k8s.io/kube-controller-manager:v1.33.1

$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                                                                     NAMES
3bf46b37cfe2   kindest/node:v1.33.1   "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes                                                                             cluster-worker3
1823a9fe2723   kindest/node:v1.33.1   "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes                                                                             cluster-worker
056bc09227aa   kindest/node:v1.33.1   "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes   127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:37315->6443/tcp   cluster-control-plane
4ce8c14db1c6   kindest/node:v1.33.1   "/usr/local/bin/entr…"   4 minutes ago   Up 4 minutes                                                                             cluster-worker2
```

**Comment by BenTheElder** [comment]
Doing something like that is entirely likely to be broken in the future, it is widely assumable that node names == hostname == container name.

I would recommend instead labeling the nodes if you must, it is better to use label selectors than node names.

Naming nodes *is not portable*, they are usually auto-generated.

We support labeling nodes more easily since this was opened. This issue is closed.

**Comment by NickLarsenNZ** [comment]
I would like custom names for making things clear in documentation/guides that revolve around pod placement (which is based on labels, not node names).

I am happy to manage conflicts myself, or even just let you add numbering on the end.

This is likely an unusual case, but I feel it's "another" reason to just allow people to do this.

**Comment by natereid72** [comment]
So how does one label a node after the Kind cluster is up and running without resorting to some other anti-pattern? Straight from every K8s documentation on labeling node `kubectl label nodes <your-node-name> foo=bar`

**Comment by BenTheElder** [comment]
> So how does one label a node after the Kind cluster is up and running without resorting to some other anti-pattern

https://kind.sigs.k8s.io/docs/user/configuration/#extra-labels

This is similar to concepts like node pool and topology labeling in production grade clusters. They're applied by the thing creating the nodes.

**Comment by natereid72** [comment]
Whether it”s production grade cluster or a kind cluster, things could need to be labeled after the nodes are created. The docs for kind you included say the method is ported from kubeadm. But even kubeadm lets you specify host name.

**Comment by BenTheElder** [comment]
> Whether it”s production grade cluster or a kind cluster, things could need to be labeled after the nodes are created.

That is done based on properties of the nodes. A controller or tool will inspect the nodes and apply labels based on other metadata or measured properties.

That sort of thing works through standard APIs, and should not be based on node names.

> But even kubeadm lets you specify host name.

Because kubeadm is a building block of creating your own cluster creation tools, like kind. This is an integration mechanism for the cluster provisioner (which is kind here).

Unless you are rolling the nodes yourself by hand (in which case you *are* the cluster provisioning tool), the tool that manages your cluster will name them and handle the lifecycle.

In all cases you should avoid depending on individual nodes, Kubernetes is designed to make nodes fungible.

Depending on individual nodes is a huge anti-pattern and something essentially no "real" clusters support, we're not going to add complexity to enable it. As far as development clusters, minikube does not either.

The tools for labeling nodes are documented, and label based node selectors are well documented.

Also, unless you are testing some very particular behaviors (e.g. working on rollout controller), you should use a single node in your kind clusters. All nodes share the same host kernel / CPU / memory and have limited isolation.

**Comment by natereid72** [comment]
Agree to disagree
