### ISSUE TITLE
Allow users to configure MTU on kindnet

### ISSUE THREAD

**Issue by faiq** [kubernetes-sigs/kind#1468]
**What would you like to be added**:

There should be an easy way to configure MTU values on the bridge that kind net creates.

**Why is this needed**

We're using KIND heavily for our CI testing purposes. Our CI workflows run on Kubernetes and in order to get kind to run properly we run a pod with a dind container that starts kind and our tests run against this cluster. We were running into many issues running our tests that make network request from this docker in docker in docker environment. After hours of debugging we realized that the MTU was configured too high and once we ran our inner most container with the following args 

 `args: ["-c", "ip link set mtu 1400 dev eth0 && /manager --enable-leader-election"]`

the issue was mitigated.

If we were able to pass in some configuration via our kind-config.yaml it would be greatly appreciated! 

Please let me know if you'd like me to add in more information.

Thank you for you time and consideration.

**Comment by BenTheElder** [comment]
cc @aojea 
/priority backlog

**Comment by aojea** [comment]
>  Our CI workflows run on Kubernetes

what CNI uses that Kubernetes? is it an overlay?

Because you should not have MTU issues if there is no overlay involved, because kindnet does not encapsulate anything, neither docker does. 

Anyway, kindnet uses the ptp CNI plugin and it does have an option to configure the MTU :smile: 

https://github.com/containernetworking/plugins/tree/master/plugins/main/ptp

**Comment by aojea** [comment]
Ok, I've tested and the MTU option works, we just need to add `"mtu": 1400, ` to the CNI config manifest

https://github.com/kubernetes-sigs/kind/blob/54471c23b742b75c8c9baaa6979bd63576c618f3/images/kindnetd/cmd/kindnetd/cni.go#L60-L62

@BenTheElder what will be the easier way to make it configurable? 

passing it as an environment variable to kindnet and templating it, like we are doing with the POD_SUBNET?
https://github.com/kubernetes-sigs/kind/blob/54471c23b742b75c8c9baaa6979bd63576c618f3/pkg/build/node/cni.go#L157-L158

**Comment by faiq** [comment]
@aojea I think passing it in via an environment variable would be completely fine :) i didn't realize that it was using the ptp module (or that it even existed) thanks so much for looking into this!

**Comment by aojea** [comment]
> @aojea I think passing it in via an environment variable would be completely fine :) i didn't realize that it was using the ptp module (or that it even existed) thanks so much for looking into this!

@faiq in the meantime you can workaround it manually, processing the file`/etc/cni/net.d/10-kindnet.conflist`,  using `docker exec` per example,  and adding the MTU option.

**Comment by faiq** [comment]
@aojea I'm looking at this again we're using Calico and running an Overlay network with IPIP encapsulation. We set an mtu on that network of 1480. 

Furthermore, we run the following command to start the docker daemon in our entrypoints for our node images 

```
dockerd \
  --cgroup-parent="${CGROUP_PARENT}" \
  --bip="${DOCKERD_BIP:-172.17.1.1/24}" \
  --mtu="${DOCKERD_MTU:-1400}" &
```

I hope this helps give insight into the problem that we're facing.

I'd like to submit a patch for mtu configuration. I'm going to try to put some stuff together for review

**Comment by aojea** [comment]
@faiq please bear with me, so we can try to find a standard solution for KIND to this problem:

So, we have the docker bridge that in this case emulates the underlay network of the KIND cluster. 
By default the docker network sets the mtu to 1500.
Inside the docker containers (kind nodes) we have the pods, that take the MTU from the CNI plugin (by default we have kindnet)

And from your explanation, you are running kind inside a k8s cluster that uses calico and forces you to have your docker bridge to 1400.

So, I think that the best way to solve this is:
- Add an option to kind to configure the MTU in the docker bridge (we create it since 0.8.1)
- Make kindnet to detect the node interface and autoconfigure the MTU of the pods.

The changes are relatively easy and this way the API has better semantics

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  mtu: 1480
``` 
will set the cluster MTU here
https://github.com/kubernetes-sigs/kind/blob/7620a6b488866a57cac5e73fc4540c348c6437d0/pkg/cluster/internal/providers/docker/network.go#L94

adding ` --mtu networking.mtu` 

For kindnet instead of taking the MTU value from an environment variable, it can search for the default interface or just for ` eth0` directly, and take it's  mtu, 
i.e. https://ispycode.com/GO/Network/System-network-interfaces

@BenTheElder thoughts?

**Comment by jieyu** [comment]
I like `Make kindnet to detect the node interface and autoconfigure the MTU of the pods.`

**Comment by faiq** [comment]
Both of those suggestions seem good to me. 

I can adjust the code that I wrote here https://github.com/kubernetes-sigs/kind/pull/1686 to make it modify the mtu value on the docker bridge. Right now my code takes in the value there and sets for tempting. 

Having kindnet detect node interface and autoconfigure the MTU sounds straightforward as well.

**Comment by aojea** [comment]
@faiq I prefer to submit one PR per feature if you don't mind.

Let's address first the kindnet MTU autodiscovery because this will automatically solve your issue, since you are already modifying the docker bridge mtu

> Add an option to kind to configure the MTU in the docker bridge (we create it since 0.8.1)

I've talked with Ben offline and I think we should analyze more possible consequences of this change, what happen on upgrades, with different clusters on the same bridge, if the bridge was already created with a different mtu, ... are we going to support different bridges per cluster?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1690 allows this to be configured on kindnet(d) (by way of the bridge)

_technically_ this is now possible if you create the kind network custom yourself before kind does.

next up we should consider how that might be done better, for example kind should probably copy the mtu from the default bridge when creating the custom bridge (we'd be using the standard network if it had the DNS bits)

**Comment by aojea** [comment]
I think we can close this issue because of https://github.com/kubernetes-sigs/kind/pull/1690
/close

**Comment by hellt** [comment]
Hi @aojea 
I an wondering, what is the option to set MTU on the `kind` network (which is 1500 by default)? There was a snippet from that adds `mtu` setting under `networking`, but as I see it hasn't been implemented?

**Comment by aojea** [comment]
> Hi @aojea
> I an wondering, what is the option to set MTU on the `kind` network (which is 1500 by default)? There was a snippet from you that adds `mtu` setting under `networking`, but as I see it hasn't been implemented?

it uses the mtu from the container, and the containers gets it from the docker bridge.
Do, if your docker network has an mtu 1400, the kind node will have mtu 1400 in eth0, and kindnet will configure the pods with that mtu

**Comment by hellt** [comment]
> it uses the mtu from the container, and the containers gets it from the docker bridge.
> Do, if your docker network has an mtu 1400, the kind node will have mtu 1400 in eth0, and kindnet will configure the pods with that mtu

yes, but I was referring to `kind` docker network that is created as a management network for kind nodes. `kind` cli creates it here 
https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/docker/network.go#L151

**Comment by BenTheElder** [comment]
I'd like to see the `kind` docker network match the default docker network (`bridge`) MTU, that part was missed here.

**Comment by aojea** [comment]
> yes, but I was referring to `kind` docker network that is created as a management network for kind nodes. `kind` cli creates it here
> https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/docker/network.go#L151
> 
> and I need to change mtu on this network

I can't remember now exactly, but I think that if you modify the mtu of that bridge, the containers will pick the new mtu

**Comment by hellt** [comment]
@BenTheElder yes, that would be very nice to have
The use case I have here is that I run kind on a VM inside the private cloud. The private cloud VM has 1450 MTU on its `eth0`.

Docker daemon setting for mtu only affects the default `bridge` network, thus anytime a user needs to create a customer bridged network with docker they need to use a custom option - https://docs.docker.com/engine/reference/commandline/network_create/#bridge-driver-options

So I am wondering if that would be possible to add in the spec or as a CLI option for `kind create cluster` cmd

**Comment by aojea** [comment]
That is fair enough, let me send a PR in a few minutes, are you volunteering to test it @hellt ?

**Comment by aojea** [comment]
here you go https://github.com/kubernetes-sigs/kind/pull/2153
still need to test it

**Comment by aojea** [comment]
tested and working https://github.com/kubernetes-sigs/kind/pull/2153#issuecomment-805290238
