### ISSUE TITLE
Ingress with HA Proxy

### ISSUE THREAD

**Issue by rubensa** [kubernetes-sigs/kind#1566]
Please, note that I'm trying to learn Kubernetes using kind so I can be wrong in any/all my understanding of how all should/is work/ing.

**What would you like to be added**:
As far as I know, when more than one control-plane is deployed for Hight Availability control-plane configuration an HA Poxy is automatically deployed.  This allows trafic to the cluster to be routed throw the HA Proxy so, if the control-plane leader goes down, another control-plane can take the leadership and the cluster keeps running.
The same should occur for the Ingres Controller.

**Why is this needed**:
The problem comes when you want to add an Ingress controller to the cluster.

Looking at the [doc](https://kind.sigs.k8s.io/docs/user/ingress/) you can only attach an Ingress controller to a single control-plane and map its 80 and 443 ports (using extraPortMappings) to that single control-plane.

I think that:
  * Ingres controller should be able to be deployed on any pod
  * There sould be a way to inform HAProxy where is/are deployed the Ingress Controller/s so it can map the ports and route the traffic (as is currently doing for the control-plane)

**Comment by BenTheElder** [comment]
We do not ship ingress out of the box currently, and I don't think we're looking to go beyond leaving it pluggable at the moment.

HA is there to test Kubernetes itself and not the most suitable for end-user-usage beyondd that.

Please note that these are _test_ clusters NOT production clusters.

**Comment by BenTheElder** [comment]
Basically, in the future if we solve type=LoadBalancer for docker on mac / windows then this feature is completely obviated, and is more or less what the robust version should look like.

Otherwise, you can already deploy metallb to get type=LoadBalancer on linux, in which case you can deploy your preferred ingress completely normally against type=Loadbalancer and it will work in this case as well.

https://kind.sigs.k8s.io/docs/user/resources/#how-to-use-kind-with-metalllb

LoadBalancer is tracked in https://github.com/kubernetes-sigs/kind/issues/702 and is non-trivial.

**Comment by BenTheElder** [comment]
For the implementation detail loadbalancer used internally to do "HA" we do not want to even expose this node to the user, it's just automatic.

Let's focus on solving https://github.com/kubernetes-sigs/kind/issues/702 for now.

**Comment by rubensa** [comment]
@BenTheElder thank you for your time and comments.
