### ISSUE TITLE
Update documentation with new feature gate configuration

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1572]
**What should be cleaned up or changed**:

Documentation explains how to enable feature gates in KIND patching the kubeadm configuration

**Why is this needed**:

Since 0.8.0 feature gates can be enabled from the KIND configuration

https://github.com/kubernetes-sigs/kind/pull/1263

**Comment by BenTheElder** [comment]
/help
I'll try to get to this soon but I have a few ongoing PRs. if anyone wants to beat me to it, basically just make sure the example configs are all using the v1alpha4 api version and then use the `featureGates` field instead of config patches, the featureGates field is a map of string feature gate name to bool enabled

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/1577
