### ISSUE TITLE
Keep essential CNI plugins like "bridge"

### ISSUE THREAD

**Issue by lolin9** [kubernetes-sigs/kind#1575]
For some reason, most CNI plugins are deleted in the [base Dockerfile](https://github.com/kubernetes-sigs/kind/blob/master/images/base/Dockerfile#L103
). Please do NOT remove these plugins because some of us actually need them, especially essential ones like `bridge`. The image size is very big already and deleting these handful binaries won't make any considerable difference.

**Comment by BenTheElder** [comment]
We do *everything* possible to shrink the image size.

CNI binaries should be installed at the desired versions by the CNI installer.

All major CNI overlays do this, except flannel, which seems to be relatively unmaintained.

**Comment by BenTheElder** [comment]
We make zero guarantees about the CNI binaries, except that they will allow kindnetd as default installed to function.

Non default CNI setups should copy in their own binaries, as weave, calico, etc. do.

**Comment by BenTheElder** [comment]
Kubernetes upstream also decided to stop shipping all of these in the Debian / rpm packages used by kubeadm installs, except the plugins used by kubernetes directly. CNI configs are expected to continue working by installing the plugins they need.

Kind does not use the bridge plugin.

https://groups.google.com/d/msgid/kubernetes-sig-cluster-lifecycle/a068d26c-a302-212f-86ed-32f16efcec00%40redhat.com

**Comment by lolin9** [comment]
Thanks for the quick response as expected from you @BenTheElder. Honestly this isn't serious for me since I can just install missing binaries via `docker exec`. But I only knew it was missing after spending lots of time debugging and I assumed that the bridge CNI plugin was installed by default like in almost all kubernetes installations.

Also if the whole issue of removing these plugins is due to the image size, I should tell you it is now `1.25GB` in the latest stable version so adding 20-50 MB won't really make that big of a difference.

Anyway this isn't a serious issue unless you're dealing with kubernetes networking and assuming that the default plugins are installed. You can close it if you have no intention to add them and maybe reopen it if you see others complaining in the future.

**Comment by BenTheElder** [comment]
Kubernetes networking should manage the plugins in the installer to ensure
they're the expected versions etc. They should avoid shipping unused
plugins as I said calico etc. do. KIND's supported CNI configuration uses
ptp instead of bridge currently.

The image is 1.25 GB _on disk_ but it compresses considerably smaller for
pulling from docker hub and images on disk are ~COW. A lot of duplicated
bits are across the static k8s binaries.

That 1.25 GB is hard won, including upstream KEPs for alternate lighter
build nodes.

Keeping the image pull size down is especially important. The compressed
image size (Download size) is 444.5MB for the current 1.18.2 image. IIRC
these compress poorly and 50MB is considerable in that light

**Comment by lolin9** [comment]
Yeah, I know that the download size should be much smaller but there is publicly no way to know it exactly. The compressed CNI plugins tgz file downloaded from github is about 36MB. So The overall size could simply be around 480MB or something. Anyway, I am closing it since you obviously have no intention to add them. But again, please rethink at least keeping the `bridge` plugin. It's as important as `ptp`.
