### ISSUE TITLE
Helm Chart for using ingress-nginx

### ISSUE THREAD

**Issue by amarsgithub** [kubernetes-sigs/kind#1693]
**What would you like to be added**:
I'm trying to run a custom build and have ingress-nginx do a lot of the routing inside my kind cluster. The documentation has a manifest that contains kind specific patches to forward the hostPorts to the ingress controller, set taint operations, and schedule it to the custom labelled node. Is there a helm chart that would do this for me? Mainly looking at this part: https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
and specifically this manifest: 
https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

**Why is this needed**:
Easy of accessibility for the ingress-nginx service. My environment automation works really well with helm charts but doesn't work so well with just kubectl apply -f.

**Comment by BenTheElder** [comment]
Sorry no, helm charts are out of scope for this project.
This is only one way of running ingress-nginx and is dependent on the rest of the guide. These operations are designed to be relatively independent of the ingress so we can maintain guides for multiple ingresses.

**Comment by aledbf** [comment]
@amarsgithub the manifest you see in the kind docs is generated with helm. Please check [here](https://github.com/kubernetes/ingress-nginx/blob/master/hack/generate-deploy-scripts.sh#L129-L153)

**Comment by BenTheElder** [comment]
If you have a helm chart for ingress nginx it's probably not difficult to add these operations to it.

Even for the ingress nginx yaml, the ingress nginx team maintains the yaml you kubectl apply in their repo as part of their installation guide, we're not maintaining this.

**Comment by BenTheElder** [comment]
Thanks as always @aledbf, GitHub hadn't loaded your comment :-)

**Comment by nickjj** [comment]
@aledbf that template link is unbelievable useful, thanks a lot for posting it! If you use Helm to install `ingress-nginx` with the default parameters it tries to use a LoadBalancer and always gets stuck with pending for an external IP and times out / fails.

Your set up worked perfectly. Question: Do we need to set every single one of those properties to make it work? Does this become an exact replica of what is done in https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml when you install the ingress without Helm?

If so, IMO adding this to the ingress docs for kind would be very helpful. Basically a copy / paste'able Helm command that folks can use if they want to install ingress-nginx with Helm instead of applying it with `kubectl`.

**Comment by mattfenwick** [comment]
For anybody coming across this issue in the future -- we switched over to using the `ingress-nginx` helm chart from https://kubernetes.github.io/ingress-nginx on KinD v0.11.1 with node images of 1.20 - 1.23 and it works great!  Just have to set a couple of overrides for host port and node port and you're good to go!

Here's what we do:
```
    helm install --namespace $NS $RELEASE ingress-nginx \
      --version 4.0.17 \
      --repo https://kubernetes.github.io/ingress-nginx \
      --set controller.hostPort.enabled=true \
      --set controller.service.type=NodePort
```

**Comment by BenTheElder** [comment]
FWIW, if someone's willing to help maintain it, this could be added to the ingress guide in the docs.

We do not tend to add comments like this ourselves, because we try hard to make sure anything we document works as documented and we don't have the bandwidth to regularly test all the ingress guides etc., this stuff is exponential 😅 

Right now we depend on the graces of the maintainers of these projects quite a bit for upkeep of these guides, and they've generally opted to have manifests for install. I'm a bit concerned that the guide is already a tad lengthy and confusing for some users.

**Comment by darkedges** [comment]
> For anybody coming across this issue in the future -- we switched over to using the `ingress-nginx` helm chart from https://kubernetes.github.io/ingress-nginx on KinD v0.11.1 with node images of 1.20 - 1.23 and it works great! Just have to set a couple of overrides for host port and node port and you're good to go!

values.yaml
```
controller:
  extraArgs: 
    publish-status-address: localhost
  publishService:
    enabled: false
  service:
    type: NodePort  
  hostPort:
    enabled: true
  watchIngressWithoutClass: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Equal
  nodeSelector:
    kubernetes.io/os: "linux"
    ingress-ready: 'true'
```

```    
helm install --namespace $NS $RELEASE ingress-nginx \
      --version 4.0.18 \
      --repo https://kubernetes.github.io/ingress-nginx \
      -f values.yaml
```

**Comment by victor-sudakov** [comment]
This is what I do now, probably someone will find it useful:

```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update ingress-nginx
helm install -n ingress-nginx --create-namespace \
  --values https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/hack/manifest-templates/provider/kind/values.yaml \
  --set controller.allowSnippetAnnotations=true ingress-nginx ingress-nginx/ingress-nginx
```
