### ISSUE TITLE
create a known issues guide

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#175]
there are some known issues that are not written down and distinct from things we may be attempting to patch, we should track things users may run into (eg issues with docker installed via snap).

/assign
/priority important-soon

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/136#issuecomment-457170199 <-- this should be one of the first known issues, image pulls with this dind version are known to not work, upgrading fixes it.

**Comment by alejandrox1** [comment]
May be also adding these:
* https://github.com/kubernetes-sigs/kind/issues/229#issuecomment-454857614 - failure to build node image
* https://github.com/kubernetes-sigs/kind/issues/156#issue-388448705 - kind cluster not responding due to not enough storage being available

These are briefly mentioned in the user-docs but may be it would be better to go a bit more in depth in a "known issues guide."

I'll start working on documenting this issues today.
/assign

**Comment by alejandrox1** [comment]
Should we close this? #287 addresses this issue.

**Comment by BenTheElder** [comment]
yes, thank you!
