### ISSUE TITLE
How to use legacy storage class?

### ISSUE THREAD

**Issue by FxKu** [kubernetes-sigs/kind#1803]
Hey, we are [using](https://github.com/zalando/postgres-operator/pull/871#) kind for our operator e2e tests and want to upgrade from 0.5.1 to 0.8.1. We face one problem with the local volume provisioner which is in use since 0.7.0. It uses the [node name](https://github.com/rancher/local-path-provisioner/issues/68) for volume node affinity, which prevents pod from getting scheduled to other nodes in our tests. From the [code](https://github.com/kubernetes-sigs/kind/blob/09b20ed639427c050efa86df4e59258b1e350228/pkg/cluster/internal/create/actions/installstorage/storage.go#L68), I've seen you are still using the former storage class for e2e tests, too. How can we make use of it? Via configuration?

**Comment by BenTheElder** [comment]
> It uses the node name for volume node affinity, which prevents pod from getting scheduled to other nodes in our tests.

Only the node from that PV? so as to ensure your data is actually persistent ... Each PV is local to a node because the driver is local. If it didn't do this you'd lose data on pod reschedule.

> From the code, I've seen you are still using the former storage class for e2e tests, too. 

That assertion is not correct. We have the old storage class present temporarily to smooth the transition to the new images with the new storage class built in.

> How can we make use of it? Via configuration?

You can install your own storage class yourself with `kubectl` etc. including deleting or replacing the one kind provides by default if you wish.

This is not configurable. (but it doesn't need to be).
StorageClasses are just objects, and the driver does nothing other than be available if you don't use it (e.g. by replacing the storage class).

If you want to use k8s.io/hostpath just install it via `kubectl apply -f` the yaml:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/host-path
```

Note that this storage driver has significant issues though. In particular it cannot handle fsGroup / only works with root / UID=0 pods.

**Comment by BenTheElder** [comment]
Hope that helps!

**Comment by BenTheElder** [comment]
I think this is answered, closing. Please comment and let me know if not or file a new issue, thanks!

**Comment by FxKu** [comment]
Yes, @BenTheElder it's answered. Thanks for the fast reply. I let you know, if it worked for us. Could not test it locally yet.
