### ISSUE TITLE
Docker and Fedora 32

### ISSUE THREAD

**Issue by mazzystr** [kubernetes-sigs/kind#1807]
**What would you like to be documented**:
Please add  the [Docker and Fedora 32 article](https://fedoramagazine.org/docker-and-fedora-32/) to kind / [Known Issues](https://kind.docs.kubernetes.io/docs/user/known-issues/#known-issues) page

**Why is this needed**:
Since kind currently only supports Docker it would be kind to make life easier for Fedora users.

**Comment by BenTheElder** [comment]
The cgroupsv2 part is true for all of the kubernetes ecosystem still, as cgroupsv2 support is not in a release yet.

Basically the entry in https://kind.docs.kubernetes.io/docs/user/known-issues/#fedora32-firewalld is somewhat kind specific since kind actually uses a user defined network and most casual docker usage does not.

The rest of the issues are required to have docker function _at all_ and are not really in scope for kind.

Podman is actually experimentally supported since v0.8.0, see the release notes https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0

**Comment by mazzystr** [comment]
podman fails ...
```
# kind create cluster
Creating cluster "kind" ...
ERROR: failed to create cluster: failed to ensure docker network: command "docker network create -d=bridge --ipv6 --subnet fc00:8866:27d0:bd7e::/64 kind" failed with error: exit status 125
Command Output: Error: unknown flag: --ipv6
```
....And it will keep failing for as long as it takes issues/1778 is WIP. 

This is just a suggestion to help your community along and get the information glued together.  The next user will come along will hit the same blockage, Google search, find this issue, and get the needed info to get moving.

**Comment by BenTheElder** [comment]
> podman fails ...
>  ERROR: failed to create cluster: failed to ensure docker network: command "docker network create -d=bridge --ipv6 --subnet fc00:8866:27d0:bd7e::/64 kind" failed with error: exit status 125
> ....And it will keep failing for as long as issues/1778 is WIP.

This is only failing because you have a fake "docker" in path that is actually podman.
We can detect this and use the podman code anyhow in kind @ HEAD, and we have a release pending to match kubernetes 1.19 release now re-scheduled for tomorrow.

"docker" that is actually podman doesn't work, there's too many bugs and incompatibilities so we need to use the podman specific codepaths.

You can set`KIND_EXPERIMENTAL_PROVIDER=podman` to force podman mode.

**Comment by BenTheElder** [comment]
To be clear #1778 is about changes we want before declaring podman "stable". Most functionality already works. 
Some may never simply because it's not available in the underlying tool.

I'd gladly accept a PR to include this link in the existing entry at https://kind.docs.kubernetes.io/docs/user/known-issues/#fedora32-firewalld
