### ISSUE TITLE
connection to the server localhost:8080 was refused - did you specify the right host or port? On running kubectl

### ISSUE THREAD

**Issue by dgajendran** [kubernetes-sigs/kind#1846]
**What happened**: On running dind with kind, got the following in the docker container running kind `connection to the server localhost:8080 was refused - did you specify the right host or port?`

**What you expected to happen**: `kubectl get nodes` to work

**How to reproduce it (as minimally and precisely as possible)**: setup docker compose with dind and kind as services, and expose docker service in dind to kind to create cluster.

**Anything else we need to know?**:

**Environment:** mac to run docker compose

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
we don't expect kind to be run in another layer of docker in docker and doing so correctly requires some work.

`localhost:8080` is never the actual apiServer address in kind, unless you configured it manually, but it is the default in kubectl, suggesting that you're not using the kubeconfig kind generated.

**Comment by BenTheElder** [comment]
See https://github.com/kubernetes-sigs/kind/issues/303 for some pointers related to docker in docker.

Additionally note in the release notes that in kind 0.8+ the nodes are on the "kind" network, and to get a kubeconfig generated for usage by containers within the network you can use `kind get kubeconfig --internal`.

None of the standard issues explain using `localhost:8080` though, that most likely means wherever you're running kubectl the kubeconfig doesnt exist at all.

**Comment by dgajendran** [comment]
@BenTheElder Sorry that was not the exact address. Following is my kind_cluster_config.yaml
```kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
networking:
  apiServerPort: 19090
  apiServerAddress: 0.0.0.0```

And I got the following error when I ran `kubectl cluster-info` inside container where I setup kind:
```kind      | Kubernetes master is running at https://0.0.0.0:19090
kind      |
kind      | To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
kind      | The connection to the server 0.0.0.0:19090 was refused - did you specify the right host or port?```

I didn't see any related thing in netstat as well:
```kind      | Active Internet connections (w/o servers)
kind      | Proto Recv-Q Send-Q Local Address           Foreign Address         State
kind      | tcp        0      0 b1d5197b644c:50370      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50372      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50362      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50368      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50358      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50366      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50364      mph-workflow-backe:2375 TIME_WAIT
kind      | tcp        0      0 b1d5197b644c:50360      mph-workflow-backe:2375 TIME_WAIT
kind      | Active UNIX domain sockets (w/o servers)
kind      | Proto RefCnt Flags       Type       State         I-Node   Path```

**Comment by BenTheElder** [comment]
`0.0.0.0` is not going to work well.
- 0.0.0.0 means ~"any IP", but you want to reach the apiServer via something the certs are signed for
- the apiServerAddress in config is for the port forward from the host. but you're trying to connect from within another container

You still haven't filled in the issue template details, but I'll guess you're using at least kind v0.8, in which case you need the other container to be on the `kind` network and you do not need the apiserver address / port config. you also need to get the internal kubeconfig as I previously mentioned, since you're not reaching it via the host.

> I didn't see any related thing in netstat as well:

I don't know where you ran this netstat but on the host you'll only see dockerd running a port forward.

**Comment by BenTheElder** [comment]
Running in in a dind service is going to further make it a mess to get a route from your second container.

if you *must* use kind via a container instead of from the host I reccommend:
- mount the docker socket to the container running `kind` instead of using a dind service
- ensure that all containers are attached to the correct network (see above comments and the release notes)
- use `kind get kubeconfig --internal` to get a kubeconfig intended for internal usage instead of usage from the host (similar to what a pod in the cluster would receive)
- make sure the kuebconfig you get is supplied to kubectl
- don't set `0.0.0.0`, it's unnecessary. the nodes are already reachable via container IP, container name (inside the network), and the port forward on the host / loopback

I don't recommend sticking kind itself in a container though, the kind binary is < 10mb statically linked, meant to be used like a tool like docker compose itself. We don't test, recommend, or support this.

I will continue responding to comments but I don't think this is a bug in kind and I'm going to take this out of the actively tracked issues.
