### ISSUE TITLE
kind port-forward

### ISSUE THREAD

**Issue by felipecrs** [kubernetes-sigs/kind#1861]
## Motivation

We use `kind` in CI to run tests in our project in a K8s environment. At some point, we have to access the ports running in the containers for the tests to run. To do that we have some alternatives (that I remember now):

- Use `extraPortMappings`, but we have to know the port even before starting the cluster.
- Search for the container running the service (there can be more than one), find the port on it, and try to access using the container's IP address.
- Use `kubectl port-forward` and somehow make it work in the background.

None of these solutions are optimal.

## Suggestion: `kind port-forward`

A new command for `kind`, which mimics `kubectl port-forward` with a key difference:

- It exposes the container's port in the background, probably doing [something stated here](https://stackoverflow.com/questions/19897743/exposing-a-port-on-a-live-docker-container).

So let's say we call:

```
kind port-forward service/backend 3000
```

KinD would: 

1. Find what's the container running that service
2. Find what's the port on the container running that service (it can be different than the pod's port)
3. Expose the container's port on the host "permanently"

I know that VSCode Remote - Containers extension is able to expose ports from a running container to the host machine without stopping it, but I don't know their procedure.

**Comment by BenTheElder** [comment]
> Use extraPortMappings, but we have to know the port even before starting the cluster.

You need to know how many ports you want to have available for mapping. You can still run some further forwarding action (e.g. creating a nodePort object or a hostPort container) at runtime.

> Search for the container running the service (there can be more than one), find the port on it, and try to access using the container's IP address.

We don't discuss this one much because it only works on linux.

> Use kubectl port-forward and somehow make it work in the background.

`kubectl port-forward ... &` ...? Backgrounding tasks is a pretty standard shell operation for example.

> KinD would:
> 1. Find what's the container running that service

How do we know it's pinned to a node and won't move...?

> 2. Find what's the port on the container running that service (it can be different than the pod's port)

Pods do not have ports? Containers have ports. Services can target ports (or have a nodePort).

> 3. Expose the container's port on the host "permanently"
> I know that VSCode Remote - Containers extension is able to expose ports from a running container to the host machine without stopping it, but I don't know their procedure.

It's not possible to directly expose ports from a running container. They're running a process somewhere to do this.

In your CI are you unable to use `kubectl port-forward ... &` (background the task yourself?)

**Comment by felipecrs** [comment]
`kubectl port-forward` has some drawbacks, such as not supporting UDP traffic.

By the way, I believe that `kubectl port-forward ... >/dev/null &` would be the alternative rather than only `&`, since I don't want port-forward logs to overlap between other logs.

**Comment by felipecrs** [comment]
My final `kubectl port-forward` statement is:

```sh-session
nohup kubectl port-forward [...] > kubectl-port-forward.log &
```

**Comment by BenTheElder** [comment]
A nodeport service is just a standard service type where the service is reachable on some port on every node at the host level. By default it's only in a high power range but you can pick a few of these and pre map them to any kind node to the same port from the host above the kind nodes and then at runtime you can make services on each of these and have the same port mapped from your dev machine to a kind node to the nodeport mechanism to the service to the pod. The kubernetes upstream docs for services have more on nodeport.

> My goal with this suggestion was to somehow make the port forwarding seamless by using some kind of standard docker port forwarding method (which is something that kind has the ability to use but kubectl does not).

The standard docker port forwarding mechanism must be done during container creation unfortunately. That is already available in the kind config extraPortMappings option, but has the same upstream limitation that it's not dynamic.

We could create dedicated socat containers to forward to a node IP:port or something but a) you can pretty easily hack this up without kind b) the UX for this may be a bit problematic c) it still wouldn't be forwarding to a kubernetes object unlike kubectl port-forward.

As for UDP, this is because not even CRI natively had UDP port forward so ...

**Comment by felipecrs** [comment]
> The standard docker port forwarding mechanism must be done during container creation unfortunately. That is already available in the kind config extraPortMappings option, but has the same upstream limitation that it's not dynamic.
> 
> We could create dedicated socat containers to forward to a node IP:port or something but a) you can pretty easily hack this up without kind b) the UX for this may be a bit problematic c) it still wouldn't be forwarding to a kubernetes object unlike kubectl port-forward.

That's true. But I wonder how VSCode is able to forward ports from the Remote - Containers when they are running, without any sibling containers.

> As for UDP, this is because not even CRI natively had UDP port forward so ...

Good to know, so it does not matter. :)

**Comment by felipecrs** [comment]
Socat could be useful for this.
