### ISSUE TITLE
Connection refused when using nodeport

### ISSUE THREAD

**Issue by hwk42** [kubernetes-sigs/kind#1890]
**What happened**:
I got `Connection refused` error  when access from node public ip and svc/nodeport,but all resources is running and it works well with `port-forward`,what happend? Is there difference with native k8s?
```
kubectl get svc
traefik      NodePort    10.106.154.77    <none>        8000:30009/TCP,8080:30572/TCP,4443:30044/TCP   3h49m
curl http://public_ip:30000
Connection refused
```

```
kubectl port-forward --address 0.0.0.0 service/traefik 30000:8000
curl http://public_ip:30000
all is well 
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**
kind v0.9.0 go1.15.2 linux/amd64
kubectl version v1.19.2
docker Version: 19.03.13

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by BenTheElder** [comment]
Why are you curling 30000? 
> traefik      NodePort    10.106.154.77    <none>        8000:30009/TCP,8080:30572/TCP,4443:30044/TCP   3h49m

The port for 8000 is 30009

When you use `kubectl port-forward` the kubectl command creates a socket on the port you specified that it forwarding traffic into the cluster via the API Server and then Kubelet, so it is 30000 there because you specify it.

**Comment by hwk42** [comment]
Apologized for my fault ,I am sure that I use 30009 port and I try more again.It looks like that
```
kubectl get svc
traefik      NodePort    10.106.154.77    <none>        8000:30009/TCP,8080:30572/TCP,4443:30044/TCP   3h49m
curl http://public_ip:30009
Connection refused
```
```
kubectl port-forward --address 0.0.0.0 service/traefik 30009:8000
curl http://public_ip:30009
all is well
```
And thanks for help.

**Comment by BenTheElder** [comment]
what is "public_ip" here?

**Comment by hwk42** [comment]
> what is "public_ip" here?

It is VM's ip for external access

**Comment by wrbbz** [comment]
The same issue is here.

I'm trying to acces Service with NodePort:
```
NAME      TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
gateway   NodePort   10.109.208.153   <none>        8101:31896/TCP   22h

```

Cluster info says:
```
$ kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:39667
KubeDNS is running at https://127.0.0.1:39667/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
So, I'm trying to curl and get 'Connection refused':
```
➜ curl https://localhost:31896
curl: (7) Failed to connect to 127.0.0.1 port 31896: Connection refused
```
The same with:
```
➜ curl localhost:31896
curl: (7) Failed to connect to localhost port 31896: Connection refused

➜ curl http://localhost:31896
curl: (7) Failed to connect to localhost port 31896: Connection refused
```

**Comment by BenTheElder** [comment]
@wrbbz you can't just curl a nodeport on loopback unless you also have a matching port forward configured in the kind cluster config.
If you're on Linux you can skip that but you must curl the node IP instead.
You also need to check your firewall. See the known issues in the docs as well, e.g. fedora has broken networking recently.

**Comment by wrbbz** [comment]
I'm on ArchLinux and curling of loopback port worked fine previously. As I remember
I checked firewall and there are no rules that can forbid such behaviour

**Comment by BenTheElder** [comment]
curling loopback will only work if you've configured a port mapping in the
kind config or done something equivalent.

the loopback on the host and in each container is separate, part of the
network namespace. 127.0.0.1 inside a pod is one, in the node is another,
and again on the host.

**Comment by wrbbz** [comment]
But as I understand, the purpose of NodePort is to map port of a service to a host, isn't so?

Also, I've tried to access node IP directly. There was no success

**Comment by BenTheElder** [comment]
@wrbbz nodeport is to map to the *kubernetes* host, which in this case is the kind container, which is not your host host :-)

`host [kind "node" container running kubelet etc. [pod container]]`

nodeports map from where kubelet is running to a pod.
_that_ loopback is still not your physical host loopback.

Each of these has it's own network namespace and therefore it's own loopback interface:
- host
- kind node
- container in a kubernetes pod
 

> Also, I've tried to access node IP directly. There was no success

That should work on linux. If it's not, you have a firewall issue. If you're not on linux, docker doesn't support reaching containers by IP from the host.

**Comment by dc-weizhenhua** [comment]
Hi, Have you solved the issue?  I encountered the same problem

**Comment by dc-weizhenhua** [comment]
@hwk42

**Comment by leeqiang** [comment]
BAD!!! Same problem.

**Comment by BenTheElder** [comment]
> Hi @BenTheElder, What do you mean by IP from the host?

If you're on linux you can reach the node container's IP. docker will assign one on the bridge network. You can see these with e.g. `kubectl get nodes -o wide`.

With the docker desktop app on macOS/Windows this will not work, and you'll need to take some additional steps, such as configuring a port forward in the kind config from the host to the node, due to limitations in docker.

----

https://github.com/kubernetes-sigs/kind/issues/1890#issuecomment-721964691

I'm not sure how else to explain this best, perhaps a bit more detail would be helpful (this is complicated / confusing I know, I'm doing my best!),

First it is important to remember that kind nodes are themselves an additional layer of container, and we need to route traffic through that layer, in addition to the usual Kubernetes networking.

So when you run your application and it listens on some port, this is within a container in the kubernetes pod. It is reachable within the cluster at the virtual pod IP and that port. That container is within the kind node container.

Step one is to then map something to this container's port, unless you use host networking for the pod*, we'll come back to host network pods later.

So one approach to this is a [Kubernetes NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport), a nodePort allows you to tell Kubernetes "I want to assign a port on every node that will go to these pods's port". You can either manually pick a nodePort or let it be auto-assigned. The kubernetes docs have more on this. https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

The nodePort will then ensure on every node that this port forwards traffic to your application pod(s).

At this point the application is now reachable within the cluster or on the linux host or VM where docker is running (your machine, or within the docker desktop VM if you're on macOS/Windows) either via the address of the node, or via localhost / 127.0.0.1 within the nodes, at the nodePort. The traffic will go to kube-proxy on the node to then one of the pods, and will map from the nodePort either auto-allocated or assigned to the selected port on the pod container.

If you're on Linux, this is typically enough. You just need to pick the address of any of the nodes at this point to reach it from your host machine. You can find those with for example `kubectl get nodes -o wide` and just pick an IP from any of the nodes.

If you're on macOS/Windows the problem is that kind nodes are also containers "within" which the pod containers are running. And docker doesn't setup container addresses to be reachable from the host. Docker's networking in the desktop app is a bit ... strange.

So if you want to be portable to macOS/Windows, you also need to tell docker to use a port forward (`-p` flag to `docker run`) to map a port from some address on the host to the container. Unfortunately these can only be configured when creating the container, so what you can do with kind is still kind that you want to map some port from the host to one of the nodes when you create the kind cluster. 

The configuration guide has a section on this:
https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings

Then later you can use the port you chose on the node side for a nodePort service and the traffic will go: 
listener on the host on some port --- * docker magic networking * --> the node container on another port --- * kubernetes kube-proxy nodePort system * --> routed to the pod port.

There's a complete guide on doing this approach to map to an ingress which can then point to other HTTP apps here: https://kind.sigs.k8s.io/docs/user/ingress/

Instead of an ingress, you can run your app directly behind a nodePort.

----
OK so remember I said host networking pods are different?
If you use a host networking pod, then basically your application is listening directly on that node, and you can just worry about either accessing the node address on linux or extraPortMapping to the node your application will run on in macOS/Windows. For a single node just map the port. For multi-node you may need to consider using labels/taints to ensure the application runs on the node you're extraPortMapping traffic to -- the ingress guide has an example of this.

**Comment by BenTheElder** [comment]
Sorry, that's perhaps a bit too much text :-)

Our community is also typically really helpful on the kubernetes slack (invite: https://slack.k8s.io), we are in #kind, if anyone wants to drop in and ask more specific questions there we usually have a better response time as a community, there are more people helping to respond there than on github.

**Comment by gastrodon** [comment]
I'm running into the same issue. Am I missing anything here?

![image](https://user-images.githubusercontent.com/10934565/140023561-f590c0a7-90b9-44e0-941e-de2899e9fc58.png)

I'm deploying a consul image, but `curl`ing the node's ip with the port that kubernetes exposed doesn't seem to do anything. I'm using k3s via k3os, if that matters.

**Comment by BenTheElder** [comment]
@gastrodon k3os is not the same as kind at all and I'm not familiar with it, you should file an issue with that project instead please.

**Comment by xxtanisxx** [comment]
Helpful tips after facing the same issue where NodePort is properly initiated with the correct entrypoint and wasn't able to curl.

I end up running below command taken from [here](https://github.com/docker/for-mac/issues/3594#issuecomment-621487150)
```
rm -rf ~/Library/Group\ Containers/group.com.docker/pki/
```

Then restart docker.

Then curl works perfectly. Took me a day of search the entire internet, but this works

**Comment by aojea** [comment]
WHAT?? :upside_down_face:

**Comment by BenTheElder** [comment]
That seems to be related to the certs for the Kubernetes cluster offering built into the docker desktop app. To be clear: this repo is a completely different project from the Kubernetes cluster option built into the docker Mac app.

Please folks, this issue tracker is for clusters created with the open source tool in this repo, with open source upstream Kubernetes. Not forks and commercial projects.

**Comment by lmbleandro** [comment]
I know the topic is old but I had the same problem.
I'm on a machine studying and I couldn't access it.
After checking the cluster IP with: kubectl get nodes -o wide
kubectl get nodes -o wide
```
NAME                       STATUS   ROLES           AGE   VERSION         INTERNAL-IP                   
multinodes-control-plane   Ready    control-plane   18h    v1.27.3         172.18.0.4     
multinodes-worker          Ready    <none>          18h    v1.27.3         172.18.0.2   
multinodes-worker2         Ready    <none>          18h    v1.27.3         172.18.0.3
```
    
I was able to access it through the IP's listed in INTERNAL-IP  and using NodePort
