### ISSUE TITLE
Allow docker runtime option

### ISSUE THREAD

**Issue by Danny-m08** [kubernetes-sigs/kind#1930]
**What would you like to be added**:
Would it be possible for an option that would allow the user to use docker container runtime as the kubernetes container runtime as opposed to CRI? 
**Why is this needed**:
I think this would be useful in avoiding the additional overhead of loading images on the the cluster container. If we can mount the docker.sock to the cluster then it should have access to the host machine's images and can deploy pods, bypassing the need to load them. Our images are pretty big and we have a number of services which causes the process of pulling then loading images to be inconveniently long. Has this been considered and if so, why was it denied?

**Comment by BenTheElder** [comment]
> I think this would be useful in avoiding the additional overhead of loading images on the the cluster container. If we can mount the docker.sock to the cluster then it should have access to the host machine's images and can deploy pods, bypassing the need to load them. Our images are pretty big and we have a number of services which causes the process of pulling then loading images to be inconveniently long. Has this been considered and if so, why was it denied?

It won't work, which is why it's not implemented. The runtime needs to be "in the node".

- kubelet must have a consistent filesystem view with the runtime
- kubelets (plural) cannot share a runtime (so you'd only have one cluster and no multi-node)

Once we're shipping it within the node, you're not using the one on the host, so we run the one that works best for us as a provisioning tool. As an end user at that point it should be more or less the same.

Additionally, docker support is deprecated in favor of CRI, so in the future running docker instead of containerd will require an additional component, which so far nobody is stepping up to work on / maintain (which is part of why it's being removed from kubelet).

**Comment by BenTheElder** [comment]
In the future the recommendation instead of loading is a local registry. We're also going to roll out some other optimizations to loading for those that still use loading (like load multiple images at once natively, maximum deduplication).

If you want a cluster running on the host machine without containerization you can just use `kubeadm`, but to ship containerized kubernetes we cannot use the host runtime.
