### ISSUE TITLE
Use only LTS base images

### ISSUE THREAD

**Issue by SimonHarrisonSH** [kubernetes-sigs/kind#1978]
**What would you like to be added**:
Please only use Ubuntu LTS as the base for the node images

**Why is this needed**:
The base Dockerfile appears to track the Ubuntu releases. This means that anyone who is using kind where older versions of k8s are required, will have issues when if they customise the node image and perform any apt operations, as they will fail when the release goes out of support.

**Comment by aojea** [comment]
> kind where older versions of k8s are required

how older?
and what kind of dependencies are those that are not present in the new releases?

**Comment by BenTheElder** [comment]
Customizing the node image is not really something we actively support at the moment. If you are doing it, you're free to build your own custom images anyhow though.

We don't even necessarily stick to ubuntu, we've switched between ubuntu and debian.

*kubernetes* users should not be depending on the host packages.

**Comment by SimonHarrisonSH** [comment]
> > kind where older versions of k8s are required
> 
> how older?
> and what kind of dependencies are those that are not present in the new releases?
We have some legacy branches of code that use older k8s api features. Simplest is to just use the older node images.

> > you're free to build your own custom images anyhow though.
I guess we'll have to. It does seem a bit foolish using non-LTS base images though. Even Ubuntu agree - their 'latest' appears to track LTS.

**Comment by BenTheElder** [comment]
It isn't foolish if the images are not even meant to be mutated, ubuntu provides these for a reason, using :latest otoh is often pretty foolish, it's not a meaningful tag.

These images are meant to contain everything. Kubernetes doesn't even have LTS.

What are you installing, exactly?

**Comment by BenTheElder** [comment]
Kind provides prebuilt images at the latest patch version for every Kubernetes minor version that will function correctly under that version of kind. Eventually we have to make changes that will no longer support especially old minor versions.

Kubernetes the project does not support older patch releases, further fixes and support only go into future patch releases.

Many of the minor versions kind enables are long since not supported by Kubernetes either, but we do our best to continue supporting them anyhow 

If you use a kind image from and old kind release older than the oldest minor version we publish for a release, it will not function fully, or else we'd have published a new image for that version as well.

**Comment by aojea** [comment]
/close
There is always a trade off between the stability of LTS distros and being able to use latest features, i.e iptables is a good example of how modern distros are switching to nftables and causing issues with old ones.

I agree with Ben we shouldn't depend on images OS versions, I would love also if we can be distroless :)

There is the possibility of creating and maintaining custom images, I'm doing it for some personal projects https://github.com/aojea/kind-images
