### ISSUE TITLE
show `docker logs` automatically on early error

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes-sigs/kind#2016]
**What would you like to be added**:

`kind create cluster` should run `docker logs <CONTAINER>` automatically on early error

**Why is this needed**:
Mostly for showing `entrypoint` errors to the user.

**Comment by BenTheElder** [comment]
Hmm:

Errors visible in the node container logs are pretty rare for end users, right now for users wishing to debug the error we point to `kind create cluster --retain; kind export logs` which captures much more info, generally enough to find the actual root cause.

 Unless you're specifically working on kind itself (in which case you probably know how to grab these easily with docker) I'm not sure these are helpful.

Further, dumping lots of logs from e.g. kubeadm to the console has mostly led to users pasting snippets containing "errors" or warnings that are not actually problematic without providing the full context with the real errors, versus asking to upload the full exported logs.

**Comment by AkihiroSuda** [comment]
> Errors visible in the node container logs are pretty rare for end users

Error output introduced in #1935 might be helpful

> Further, dumping lots of logs from e.g. kubeadm to the console

`docker logs` doesn't show so many logs.
Showing kubeadm errors require `journalctl`.

**Comment by BenTheElder** [comment]
> Error output introduced in #1935 might be helpful

#1935 is not landed yet, but that may be fair enough then.

> docker logs doesn't show so many logs.

nearly all of it is irrelevant though, especially for e.g. multi-node.

> Showing kubeadm errors require journalctl.

no, kind invokes kubeadm, not systemd, and when invoking it fails the output is displayed. it's generally not the root cause though.

similarly if container creation fails or containers terminate early, usually the error requires more info than the container logs.

**Comment by stmcginnis** [comment]
I agree with Ben's assessment above. I don't see it adding a lot of value, and I don't see kind adding this. Should this be closed?
