### ISSUE TITLE
Binary release cadence

### ISSUE THREAD

**Issue by alexellis** [kubernetes-sigs/kind#208]
Hi folks,

I wrote a blog post on the heels of KubeCon Seattle explaining what KinD is and how it can be used for testing with Kubernetes. I wanted to write a follow-up but wasn't sure if `go get` is still the preferred installation method?

There is a binary 0.1 release but it looks out of date to me vs. master (I may be wrong)

What would you recommend here? It would be ideal if people didn't need go as a pre-req - especially if testing on a minimal VM.

Thanks 👍 

Alex

**Comment by BenTheElder** [comment]
/assign

I've been slightly hesitant to publish binaries I know I'll outright break compatibility with, but that should clear up as we finish fleshing out multi-node.

I want to make another change or two to the v1alpha2 API today and then get another release out.

The overall release cadence should pick up, and the intention is to stop making breaking changes if at all possible by the Kubernetes 1.14 release.

**Comment by BenTheElder** [comment]
I want to get a release in early next week, I'm unhappy with the fact that the current mid-refactor config API is not fully respected by the implementation in some known ways, I'd like to get that patched before releasing again, but not much more since we already have some fairly substantial changes since the last alpha.

**Comment by luxas** [comment]
You can always do an intermediate 0.1.0 release or something. I'd advocate for releasing fairly often while things change much, before starting to talk about stability. This also overlaps with k8s.io/component-base as said, and I hope that will become more stable over the coming weeks as well.

**Comment by BenTheElder** [comment]
Expect another alpha release tomorrow (with windows support and
multi-node!), it slipped today.

The aggressive pace to stable is intentional, building CI etc around
unstable APIs / CLIs is not fun.
Being stable & reproducible is a core goal. By k8s 1.14 users should be
able to build on kind and not worry about breaking changes.

**Comment by BenTheElder** [comment]
Binaries are now up at https://github.com/kubernetes-sigs/kind/releases/tag/0.1.0, we will strive to release more often going forward, this was quite a large release. 😅
