### ISSUE TITLE
Traefik ingress

### ISSUE THREAD

**Issue by jasonatball** [kubernetes-sigs/kind#2115]
I don't see Traefik as one of the known to work in the [Ingress](https://kind.sigs.k8s.io/docs/user/ingress/) page but I've been trying to get it to work and feel like I'm close. I created an issue with them here: https://github.com/traefik/traefik-helm-chart/issues/388

Love to get some extra eyes on it from the kind experts because I think Traefik would be a great addition to the Ingress options in Kind.

**Comment by BenTheElder** [comment]
Sorry this isn't the most helpful comment, but a bit of context ...

The existing options in our docs have received support from their project owners vetting the install guides / maintaining these, as maintainers of KIND we can't really afford to actively support all of these, they're fairly out of [scope for the project](https://kind.sigs.k8s.io/docs/contributing/project-scope/).

We're mostly interested in having an ingress option or two documented from the perspective of "this is a Kubernetes API that should be supported".

The incompatible extensions between these tools are less than desirable to us, and otherwise they're expected to be interchangable, so I don't think we can afford to prioritize this. (=> labeling backlog)

If docker's networking didn't require these workarounds with the port forward etc., we'd probably pick ingress-nginx (because it's part of the upstream org / not a vendor project) and just ship that by default.

**Comment by BenTheElder** [comment]
I skimmed https://github.com/traefik/traefik-helm-chart/issues/388 but there's a lot going on there, it might help to create a more minimal example of "hello-world" with traefik + kind, though it looks like the owners haven't gotten to it just yet anyhow.

**Comment by jasonatball** [comment]
I feel like it's more of a Traefik configuration issue than Kind but I thought I'd ask in both places in case there was something specific in Kind that would prevent Traefik from working. Hopefully they get back and this becomes a viable ingress option on Kind.

Thanks for all the awesome work on Kind!

**Comment by BenTheElder** [comment]
It's possible it's something related to configuring the port forwards but that does not appear to be the case from what I see. I'm not sure about traefik internals

thank you 😅
