### ISSUE TITLE
Add new feature to check if k8s is up and running

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/kind#2126]
**What would you like to be added**:

I would love a CLI command that would check to see if Kubernetes is up and running.  `kind` starts a cluster and then really does not have a check to determine if the cluster is operational.  

**Why is this needed**:

When using kind for e2e tests we are sending calls into the cluster without clusterDNS even running beforehand.  We could run an external command, but when you change something in the control plane an external command that is maintained outside of kind would fail.

Also, thank-you for the wonderful tool!!!

**Comment by BenTheElder** [comment]
The problem is that cluster readiness has many levels and we can never satisfy everyone.

`kind create cluster` returns to the caller when there's nothing further we need to do for bootstrapping so you can continue on with e.g. building your app image. If you need to wait for a control plane node to be ready we have `--wait=<timeout>`.

To wait for a particular app / component to be ready, kubectl actually offers this already:


`kubectl wait pod -n=kube-system --for=condition=ready -l k8s-app=kube-dns`

We tend to prefer portable tools as much as possible. This should be pretty portable as `kube-dns` must also be the service name even when it's actually coreDNS. I think this will do what you want.

Also we recently merged some changes to the networking stack that should improve readiness times for coreDNS 😅 

And thank you!

**Comment by chrislovecnm** [comment]
We just started using this https://github.com/cockroachdb/cockroach-operator/blob/master/hack/k8s/verify_k8s_running.goand it has helped a ton.

@BenTheElder if you are interested in including this in kind or kubetest2 let me know

**Comment by BenTheElder** [comment]
That looks like a useful utility but we absolutely cannot import something with client-go into kind:
- we need to minimize dependency hell for embeddeders of kind as a library
- we need to test Kubernetes itself and avoid circular dependencies (currently the only staging code we consume is api Machinery sets and error utils and I've been meaning to cut that one out too)

I'm not sure if it would be acceptable in kubetest2, but probably not in the main repo anyhow for similar reasons.

**Comment by chrislovecnm** [comment]
I understand. Sounds good!
