### ISSUE TITLE
quick-install yaml file for kindnetd

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/kind#2168]
We do have one... it's part of a go file:
https://github.com/kubernetes-sigs/kind/blob/main/pkg/build/nodeimage/const_cni.go#L27-L141

Can we please have it as a yaml file and use say `go:embed` to populate the const_cni.go?

( context : following up on discussion in https://github.com/kubernetes/kubeadm/issues/2420#issuecomment-808524090 )

**Comment by BenTheElder** [comment]
One issue is currently in order to support passing in all the info we need with backwards compatibility etc. the yaml is actually templated / patched before applying to the cluster.

It's hard to have a CNI installation that doesn't depend on this sort of thing. cc @aojea 

We also support `go get` and not everyone is on go 1.16 yet, so we can't use that particular embed mechanism I think.

**Comment by aojea** [comment]
Last year we had a request to test kindnet outside of kind and I've created a standalone version of kindnet. https://github.com/aojea/kindnet/blob/master/install-kindnet.yaml

It differs from the in-tree version in:
- the manifest install the cni plugins
- obtains the parameters from the kubeadm or kube-proxy configmaps
Those things are not needed in KIND because that info is known beforehand.

If kinder is based on KIND, is not able to use the kindnet CNI logic directly?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubeadm/issues/2420 seems to have moved on without this. for now I am closing this out of the tracker, but if renewed need is seen we can reconsider.
