### ISSUE TITLE
kind gen config

### ISSUE THREAD

**Issue by FotiadisM** [kubernetes-sigs/kind#2169]
**What would you like to be added**:
It would be nice to have a `kind gen config` commands that generates a yaml file with all the default config values used.

**Why is this needed**:
While this is not needed, it's would be a nice feature to be easily generate the config file instead of reaching for the website.

**Comment by BenTheElder** [comment]
While we could technically do this it will only be so helpful because the fields are defaulted dynamically for each type.

Consider for example that port mappings don't exist by default but the address has a default if you add any. Or that we only have one node but each node will be defaulted.

The best way to have fields defaulted is to simply not set them ...?

**Comment by BenTheElder** [comment]
Currently I don't think this is something we should pursue. Thanks for filing the issue.
