### ISSUE TITLE
`kind delete cluster --name NAME` with non-existent NAME should fail

### ISSUE THREAD

**Issue by makkes** [kubernetes-sigs/kind#2182]
**What would you like to be added**:
Currently running `kind delete cluster --name doesnotexist` succeeds (returns status code 0) but should return a status code > 0.

**Why is this needed**:
IMHO it would be more straightforward and in line with other utilities (e.g. `rm doesnotexist` returns status code 1) as well as easier to use that command in scripts.

**Comment by BenTheElder** [comment]
There's no such thing as an existent cluster, only existent nodes or existence in a KUBECONFIG file.
Kind cleans up all of these on delete and delete is idempotent. This has been discussed in multiple previous issues if you search the tracker.

**Comment by makkes** [comment]
Oops, I actually tried to find a related issue but wasn't able to come up with a fitting query apparently. Sorry for the dup. Feel free to close the issue.

**Comment by BenTheElder** [comment]
apologies for the tone, it's difficult to convey in issue comments sometimes, I didn't mean anything other than we've discussed it a fair bit before and decided to continue with the current exit code behavior. github's search isn't the greatest, I've filed plenty of "dupes" myself 😅 

it might make sense to modify the logging, but otherwise I think we'll indeed close this.
