### ISSUE TITLE
Documentation should tell you how to upgrade kind to latest version

### ISSUE THREAD

**Issue by omerbensaadon** [kubernetes-sigs/kind#2198]
**What would you like to be documented**:
How to upgrade kind to the latest version! 

`brew upgrade kind` actually works but is nowhere to be found on the site! 

**Why is this needed**:
Some programs have a dependency on a certain version of kind, and the website doesn't explain how to update an existing installation

**Comment by BenTheElder** [comment]
Excepting homebrew and perhaps chocolatey, users may not have a specific upgrade command for their installation and don't really need one. They should install the latest version instead. There are no upgrade specific steps.

Neither of these contain "upgrade" either:
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/

I would think `brew upgrade` is covered by homebrew's docs ..?

**Comment by benmoss** [comment]
I concur with @BenTheElder , it seems beyond the scope to cover all the functionality that each package manager might have.

**Comment by omerbensaadon** [comment]
That is helpful context, thanks for taking the time to respond!

The only thing I'm asking for here is to make it clear to folks that you can do "brew upgrade kind" as it is not present on the site :)

**Comment by omerbensaadon** [comment]
I would think all it requires is a little note next to the download option?

**Comment by benmoss** [comment]
I think the objection is just that if we document how to install via curl, homebrew, curl on Windows, chocolatey, and you are saying we should have documentation on how to upgrade as well, doesn't that imply that we then need to have upgrade documentation for *all* the installation methods? And then where does it stop, do we need to have uninstall documentation too?

That all said, I don't think it's that bad an idea if it was organized properly, the install section is already a little sprawling in my opinion. If you feel passionately about this I'd encourage submitting a PR rather than requesting that someone else do it.

https://github.com/kubernetes-sigs/kind/blob/216edda697a37f8bf16651af6c23b7e2bb7ef42f/site/content/docs/user/quick-start.md

**Comment by BenTheElder** [comment]
AFAIK it's expected with homebrew that you can `brew upgrade <X>` for anything you install with it?

The Kubernetes docs have a guideline to deduplicate content and prefer upstream / third party content remain in their own docs, for example to install kind, minikube, etc. the Kubernetes docs just link to our docs without going into detail. (see: https://kubernetes.io/docs/tasks/tools/).
Their intention is to both avoid duplicated effort / stale content and to avoid favoring any third party tools, vendors, etc.

We try to follow the same thing. I'm not sure that need anything special for this, the upgrade options should be well documented upstream by homebrew etc.

With respect to kind specifically: Any version specific upgrade details or special actions that need taking by users are documented in the release notes.
https://github.com/kubernetes-sigs/kind/releases

For example we document breaking changes there that you should be aware of when upgrading. But similarly we don't cover this in the install guide.

**Comment by BenTheElder** [comment]
The main reason I'd be hesitant to add this is the "quick start" is already unnecessarily lengthy / bloated and I'd already expect homebrew, `go get`, `choco`, etc. users to use the docs for their tool which should cover upgrades, leaving only `curl` + `chmod` + add to `PATH`, and I think users dropping binaries into their `PATH` can be left to manage them themselves.

**Comment by FedericoAntoniazzi** [comment]
Hi folks, in my opinion this is not a goal of kind's documentation since you use external tools and you should know how to use them. Adding this will also imply explaining how to uninstall kind and other operations and I think it's like adding to much bloat.

As an alternative we could prompt the user to read the documentation for the tool but I think we need a new section and it's still too much for kind's docs

**Comment by omerbensaadon** [comment]
I'll close this issue, sorry for the bother and thanks for the quick response...

**Comment by BenTheElder** [comment]
I think this was a good discussion and I'm happy to see so much input from the community. Thank you all!
