### ISSUE TITLE
Does kind currently support creating k8s in k8s, in addition to Podman and Docker?

### ISSUE THREAD

**Issue by QQGoblin** [kubernetes-sigs/kind#2314]

**Comment by BenTheElder** [comment]
you can run docker or podman inside k8s and then run kind inside k8s

see: #303 

we _Really_ don't recommend it, but do it ourselves because kubernetes's in-house CI runs on kubernetes (which... has issues), you can find a running log of what we've found necessary there.

we've intentionally not put up a guide yet, as I don't think the current state is ideal, it's insecure, and we woudn't recommend it.

but it is possible yes.

**Comment by QQGoblin** [comment]
Thanks，We create clusters of k8s for personal development/learning via kind, and we may need a scheduling tool to manage these kind-k8s. 

This may not match the original application scenario of kind, but running kind in a pod is probably the best solution.

**Comment by BenTheElder** [comment]
I think you'll find what you need in #303 and it's probably relatively fine for that purpose, mostly it's a bit annoying to do kubernetes-in-kubernetes because none of this was designed to nest and there are some global / non-namespaced limits to deal with (like inotify). That's all discussed in the running conversation there.

P.S. I think this is cool, we just don't want people doing it for more serious use cases, and it's possible to do from #303 😅 

In other scenarios trying to run nested containers is pretty insecure right now, and a lot more alarming when it's potentially exposed to the internet alongside other infrastructure.
