### ISSUE TITLE
Error starting control plane: failed to join node with kubeadm

### ISSUE THREAD

**Issue by fgimenez** [kubernetes-sigs/kind#2316]
**What happened**: After moving a Prow job that uses kind to a new cluster it started failing, used to work fine previously on a different cluster. 

The main error we get is `✗ Joining worker nodes 🚜\nERROR: failed to create cluster: failed to join node with kubeadm: command \"docker exec --privileged kind-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6\" failed with error: exit status 1\n\nCommand Output: ..............`. 

In the logs there are lots of `Failed to request cluster-info, will try again: Get \"https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s\": dial tcp 172.19.0.2:6443: connect: connection refused"`, full logs here https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1341/rehearsal-pull-project-infra-prow-deploy-test/1405928445820538880/artifacts/

**Environment:**

- kind version: kind v0.9.0 go1.15.2 linux/amd64
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: 19.03.13
- OS: Debian GNU/Linux 10 (buster)

**Comment by BenTheElder** [comment]
Are you able to consider upgrading? we've had a few releases since v0.9.0

also for running in kubernetes #303

**Comment by BenTheElder** [comment]
something is killing your processes all over the place. sounds like a dupe of https://github.com/kubernetes-sigs/kind/issues/1614 which was fixed mostly in v0.10.0 and we've improved the related logic again since then.

**Comment by BenTheElder** [comment]
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1341/rehearsal-pull-project-infra-prow-deploy-test/1405928445820538880/artifacts/kind-control-plane/journal.log

> Jun 18 16:43:02 kind-control-plane systemd[1]: systemd-journald.service: Main process exited, code=killed, status=9/KILL

This is in the logs many times, plus all the core pods etc are working but kubelet keeps losing the connection, if you look at the pod logs you will see 7.log, 8.log, they keep restarting because they keep getting killed. pretty much every process in your cluster has been killed and restarted, which is almost certainly #1614, and should be fixed by upgrading to the latest stable release (currently v0.11.1)

if you're settting up a new cluster to try to do kubernetes-in-kubernetes, please also take a look at all the discussion in #303, there are a number of other things you'll want to look out for.

**Comment by fgimenez** [comment]
Awesome thanks a lot @BenTheElder!! using v0.11.1 definitely resolves the issue, all working fine (and even faster?) now :heart: This is how the logs look like https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1341/rehearsal-pull-project-infra-prow-deploy-test/1405961292103028736/artifacts/

**Comment by BenTheElder** [comment]
awesome! yeah it should be a teeny bit faster and the logs should be less spammy, we fixed the "kubeadm crashloops kubelet until configuring it" thing besides some of the cgroups handling :-)

we're hacking on smaller images and some other bits for the next go round to try to get more 😅
