### ISSUE TITLE
Add git to kindest/node

### ISSUE THREAD

**Issue by collivier** [kubernetes-sigs/kind#2356]
**What would you like to be added**:
Git could be added to the docker image (kindest/node)

**Why is this needed**:
Git is needed to successfully pass [sig_storage] [Slow] via Kind
e.g. [sig-storage] EmptyDir wrapper volumes [It] should not cause race condition when used for git_repo [Serial] [Slow] 

It would allow adding the slow tests in kind release testing.
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.21.yaml#L709

Please see https://build.opnfv.org/ci/job/functest-kubernetes-v1.21-daily/22/ (git installed by hand)

**Comment by BenTheElder** [comment]
We've not had good experience with bothering to run the `Slow` tests and that particular job is supposed to match what we run on Kubernetes presubmits, so we won't be changing that one. We could add another job but I'd like to know what the reason is -- Are you interested in this particular test, or on some other slow test being in CI?

In any case IMO this test should be re-written if it depends on git being installed on the host. Where possible kind has always taken the approach to make tests work for more clusters instead of changing kind, kind is a good way to find these sort of bad assumptions in tests.

**Comment by BenTheElder** [comment]
Actually:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/e2e/storage/empty_dir_wrapper.go#L197

This test is for the deprecated in-tree GitRepo volume type, I do not think we should expend resources on these volume types.

If we add git to the node image we increase the download size and when we try to remove it in the future when this volume type is removed from the project we will find out that users inevitably now depend on git being installed in the node images.

**Comment by collivier** [comment]
I'm basically interested to run any e2e tests which could make sens in context of [Functest](https://www.linkedin.com/pulse/opnfv-xtesting-functest-c%C3%A9dric-ollivier) Kubernetes or [Anuket](https://anuket.io/) Reference Conformance suite for Kubernetes. I do also precise that Kind has been successfully used for both [patch set verification](https://build.opnfv.org/ci/view/functest-kubernetes-review/job/functest-kubernetes-v1.21-review/12/) and [container verification](https://build.opnfv.org/ci/view/functest-kubernetes/job/functest-kubernetes-v1.21-daily/22/) in Functest for a while.

Of course we included the classical non-disruptive [Conformance] tests (we rather focus on deployment testing before onboarding) but we are trying to include additional e2e tests excluded in [Conformance]. In our Telco context, we could add requirements which could increase the classical K8s interoperability testing (e.g. Feature:IPv6DualStack). 

Then we recently started adding new test cases per sig (still under work). 
Here are the current test case descriptions if you're interested in them:
https://git.opnfv.org/functest-kubernetes/tree/docker/smoke/testcases.yaml?h=stable%2Fv1.21

Going back to the previous topic, I fully agree that here git seems too much and we should rather skip this particular test.
Else about increasing CI part, it was not my topic here but yes it would help if there is an upstream verification especially on the slow tests.
(about the wish list, I would love to see alpha or beta docker images especially due to clusterapi ;))

I could send you the report of slow tests I successfully executed vs Kind if it helps.
https://build.opnfv.org/ci/view/functest-kubernetes/job/functest-kubernetes-v1.21-daily/22/

@BenTheElder Thank you for your quick answers.

**Comment by BenTheElder** [comment]
> Of course we included the classical non-disruptive [Conformance] tests (we rather focus on deployment testing before onboarding) but we are trying to include additional e2e tests excluded in [Conformance]. In our Telco context, we could add requirements which could increase the classical K8s interoperability testing (e.g. Feature:IPv6DualStack).

I definitely recommend this, FWIW.

> (about the wish list, I would love to see alpha or beta docker images especially due to clusterapi ;))

We need to rethink docker image publishing in general, right now it has to be manual, and Kubernetes makes it self-inflictedly painful to publish automatically, k8s.gcr.io requires a human to PR a manifest to promote images and a review + approval process. With dockerhub we're not sure we should invest further.

Either way, kind currently has no developers focused on it fulltime, so big work like this is not happening, only maintaining it and smaller features.

There is a big problem here in that even when we get this working we will publish images that will not work without using kind at HEAD.

For users adventurous to keep kind at HEAD instead of a stable supported release, the quick start guide covers how to build kubernetes images, and kind at HEAD will always work with Kubernetes at HEAD as we are part of how Kubernetes is tested (the original motivation for the project, and main focus when we are doing supported work at work).

Currently upstream does more storage coverage in a job running on real GCE clusters, for these slow expensive tests it makes sense to use a larger dedicated temporary test cluster than kind running on our CI.

I think we will just continue to recommend avoiding the gitrepo volume in testing and in usage, as I understand it SIG storage would prefer to just remove it and there are alternatives available.
