### ISSUE TITLE
401 when trying to pull my local image. Do I need to load all of my local images into my kind cluster manually?

### ISSUE THREAD

**Issue by red8888** [kubernetes-sigs/kind#2446]
Completely new to kind and this unclear to me

I built a local image named this:
"gcr.io/myproject/apps/myapp01:testing"

Its in GCR format because thats what I use for my registry but I built it locally

My expectation was kind would be able to get any local images I have but I'm seeing this error:
Failed to pull image "gcr.io/myproject/apps/myapp01:testing": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/myproject/apps/myapp01:testing": failed to resolve reference "gcr.io/myproject/apps/myapp01:testing": unexpected status code [manifests testing]: 401 Unauthorized

**Comment by pseudonator** [comment]
Perhaps this is useful for you https://kind.sigs.k8s.io/docs/user/local-registry/

**Comment by red8888** [comment]
Just to add to this I uploaded my image but I still get the exact same error:
`kind load docker-image "gcr.io/myproject/apps/myapp01:testing"`

**Comment by BenTheElder** [comment]
> My expectation was kind would be able to get any local images

No, that expectation is incorrect. KIND looks like this:
<img width="807" alt="Screen Shot 2021-09-07 at 1 39 26 PM" src="https://user-images.githubusercontent.com/917931/132407849-d0803a53-c5aa-4203-954f-ab9aa9978282.png">

For various reasons we need to run a container runtime per-node. It does not and cannot share storage with the top level runtime on your host.

To make images available to your nodes you must either:
- "side load" them into the node runtimes with `kind load ...` 
- push them to a registry (local or otherwise) reachable by the nodes

We have more on both approaches in the docs.

> Just to add to this I uploaded my image but I still get the exact same error:
> kind load docker-image "gcr.io/myproject/apps/myapp01:testing"

Can you check if the issue is any of the NOTEs here: https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

There are multiple gotchas for using this command that are easy to miss, particularly `--name` and `ImagePullPolicy`.
