### ISSUE TITLE
remove the need for cp/mkdir/kill from haproxy image

### ISSUE THREAD

**Issue by jaxesn** [kubernetes-sigs/kind#2455]
**What should be cleaned up or changed**:
By using docker/podman cp/kill directly we can avoid needing [cp/mkdir/kill](https://github.com/kubernetes-sigs/kind/blob/main/images/haproxy/Dockerfile#L46) in the final haproxy container image.  Files could be tar'd and passed via stdin to docker cp directly. docker kill can be used to trigger config reload instead of calling kill inside the container.

**Why is this needed**:
This would be a pretty small optimization, but wanted to see if there was any interest in coming up with a solution to remove these so the final haproxy image really only has haproxy (plus distroless cc) in it.

**Comment by BenTheElder** [comment]
It probably makes sense at some point but as you said the optimization is pretty small.

The downside is it will increase the surface area of the otherwise still relatively minimal node provider, and we may need to consider what that looks like for future providers. Currently nearly everything is drop-in portable to any container runtime with support for exec.

We do have some code comments noting that this may make sense to investigate anyhow. I'm not sure it will actually be more clean though.

**Comment by BenTheElder** [comment]
I think we decided not to go forward with this, it's such a small optimization and we're not actually worried about e.g. code exec in this container. We may have to revert the whole distroless version of this image anyhow due to issues upgrading versions. (lost track of it, but there's discussion on a PR where we ran into this).

thanks so much for taking a stab at this and filing the issues and PRs anyhow! 🙏
