### ISSUE TITLE
start-cluster.sh failed in Azure Red Hat Enterprise Linux 8.2

### ISSUE THREAD

**Issue by sarangrana** [kubernetes-sigs/kind#2459]
I am using Azure to setup a kubernetes cluster with kind.

I have installed the Pre-req and when I run the ./start-cluster.sh its failing giving below error.
[However it works in my windows 1-0 wsl but docker windows is making the machine unresponsive]

I am getting below error on RHEL 8.2 Azure VM.
`Registry Host: kind-registry
ERROR: failed to create cluster: unexpected end of JSON input`

Docker version is as below.

`Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Version:            1.4.2-stable3
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64`

Kind version 
`kind v0.11.1 go1.16.4 linux/amd64`

JQ Version
`jq-1.5`

**Comment by BenTheElder** [comment]
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg. Version: 1.4.2-stable3 RemoteAPI Version: 1 Go Version: go1.12.12 OS/Arch: linux/amd64

The local registry script is not tested with podman.

`kind` podman support is experimental and needs to detect that it is NOT docker, because podman is NOT docker compatible. thankfully https://github.com/kubernetes-sigs/kind/blob/31d33511ae0a86f04e5bd475acc422407349122c/pkg/cluster/internal/providers/docker/util.go#L33 should be detecting that it is not actually docker, but probably the registry script still does not work.

note that `start-cluster.sh` is not the name of any file in this project.
