### ISSUE TITLE
Add nerdctl to kind 

### ISSUE THREAD

**Issue by jonyhy96** [kubernetes-sigs/kind#2517]
**What would you like to be added**:

Add [nerdctl](https://github.com/containerd/nerdctl) to kind because it is very friendly to people who are familiar with docker-cli rather than ctr.

**Why is this needed**:

And add `nerdctl` to kind will make it more easy to use on testing purposes.

**Comment by BenTheElder** [comment]
I think probably we should be considering adding support for nerdctl/lima (especially if someone wants to outline the approach and take it on themselves), but currently even the podman support is a bit lacking (see e.g. #2038).

Within the nodes I think we should not add this additional tool, preferring the Kubernetes API instead (and we do also provide `ctr` since we depend on it internally, and probably others do now).

**Comment by BenTheElder** [comment]
#3445, #3429
