### ISSUE TITLE
Failed to build Kubernetes: failed to parse source version: could not parse "" as version

### ISSUE THREAD

**Issue by lunz1207** [kubernetes-sigs/kind#2529]
**What happened**:

`
Failed to build Kubernetes: failed to parse source version: could not parse "" as version
`

**What you expected to happen**:

bulid  a node-image 

**How to reproduce it (as minimally and precisely as possible)**:

run `kind build node-image`

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 darwin/arm64
- Kubernetes version: (use `kubectl version`): 1.22.2
- Docker version: (use `docker info`):20.10.8
- OS (e.g. from `/etc/os-release`): mac os m1  11.6

**Comment by BenTheElder** [comment]
You need to setup a working Kubernetes development environment. This error means kind was unable to detect the version  from your local sources but ultimately likely means either the source path is wrong (because we couldn't auto detect the $GOPATH/src/k8s.io/kubernetes like Kubernetes checkouts still require upstream or you didn't supply it) or the upstream build code in Kubernetes is failing (probably missing dev tools like a new enough version of bash).

1.22.2 definitely builds on my machine and @aojea and CI.

**Comment by BenTheElder** [comment]
See: https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

> **NOTE**: Building Kubernetes node-images requires everything building upstream Kubernetes requires, we wrap the upstream build. This includes Docker with buildx. See: https://git.k8s.io/community/contributors/devel/development.md#building-kubernetes-with-docker

**Comment by lunz1207** [comment]
@BenTheElder  thanks , my clone kubenets repo miss gitversion . now i fix it

**Comment by aojea** [comment]
can we detect and warn about this @BenTheElder , I did hit this and it took me some time to figure it out

**Comment by BenTheElder** [comment]
@aojea 🤷‍♂️ I don't think getting the Kubernetes development environment setup is a task kind should be opinionated about. Maybe if the Kubernetes build fails we can drop a hint about checking the upstream docs? But otherwise any opinions about what constitutes a proper build environment really belong in the Kubernetes repo, not here.

**Comment by aojea** [comment]
> But otherwise any opinions about what constitutes a proper build environment really belong in the Kubernetes repo, not here.

yeah, was more a general question
