### ISSUE TITLE
Define "unkind"

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/kind#255]
As discussed in kind meeting the 29th of January (see https://github.com/kubernetes-sigs/kind/issues/252 for @neolit123 notes), it is necessary to define how to extend kind for supporting additional use cases like e.g. "use kind for upgrade tests" or "use kind for kubeadm development".

Even if details about the possible solutions for the aforementioned use cases are not yet defined, there is a general agreement that the only a "core" part of this should be implemented in the kind main binary, while the "not-core" part should be another go binary that reuses/extends the kind.
 
The bar of what is "core" and what is "non-core" for kind is not defined yet, but at first following question could be addressed:

Where this binary should live?
a) in the kind repo (my preferred option)
b) in the kubeadm repo
c) in another repository (please, don't...)

What will be the name of this binary 😜?
a) unkind 
b) kindest (from kind extensions, my preferred option despite unkind proposal was brilliant) 
c) ...

**Comment by pablochacin** [comment]
> Even if details about the possible solutions for the aforementioned use cases are not yet defined, there is a general agreement that the only a "core" part of this should be implemented in the kind main binary, while the "not-core" part should be another go binary that reuses/extends the kind.

I'm confused about this statement. I was expecting that non-core o more accurately "use case specific" code should live out-of tree in the project that brings this requirement (For example in `kubeadm`) or as individual projects. 

What I think is important within kind project is to provide the capability to use `kind` as a library and be able to customize its behavior by means of custom actions. Alternatively, defining a plugin mechanisms that allows those extensions to be dynamically loaded could also be an option. 

I think that providing an extended `kind` binary is  non sustainable on the long term.

**Comment by inercia** [comment]
I was wondering wether it is really necessary to have some external binaries. Do we really need that level of customization? Because interfacing with those external tools would bring some complexity to the acrhitecture...

I think most users would have enough with some mechanism for 1) running some shell commands in containers 2) copying stuff to/from containers. These things could either a) ovewrite currents tasks or b) be run as some `hooks` at some points in time.

**Comment by neolit123** [comment]
> I think most users would have enough with some mechanism for 1) running some shell commands in containers 2) copying stuff to/from containers. These things could either a) ovewrite currents tasks or b) be run as some hooks at some points in time.

absolutely, this is what i proposed in https://github.com/kubernetes-sigs/kind/issues/252
if we think about nodes over the internet one just needs `ssh` and `scp`. for kind we need the same over containers.

**Comment by BenTheElder** [comment]
> if we think about nodes over the internet one just needs ssh and scp. for kind we need the same over containers.

`docker cp $NODE_NAME`, `docker exec $NODE_NAME`

**Comment by BenTheElder** [comment]
> I'm confused about this statement. I was expecting that non-core o more accurately "use case specific" code should live out-of tree in the project that brings this requirement (For example in kubeadm) or as individual projects.

Ideally yes, in this case we it's odd.

So for _kubernetes_ the project, it makes sense to do EG kubeaedm upgrade testing. We need a place for that code. But it will not be generally supported for kind users to upgrade their nodes, that's absolutely not something we should support. The point of ""unkind"" is to have kubeadm-project CI glue that we _do not_ support for re-use. Which is why it should not live in the main CLI at all.

> I was wondering wether it is really necessary to have some external binaries. Do we really need that level of customization? Because interfacing with those external tools would bring some complexity to the acrhitecture...

usage as a library is a supported feature. the cluster-api already does this for example. this tool just might not happen to live in another repo for :reasons:

**Comment by neolit123** [comment]
whatever this ends up being, i'm not fond of the name `unkind`. :)

**Comment by BenTheElder** [comment]
yeah, `kinder` might be a better name (`kind` cli , `kinder` extras cli, `kindest` image registry / image tags)

**Comment by BenTheElder** [comment]
So far the primary use case we've agreed to for this is #256. Let's solve that one instead, and better document what the project scope is in our docs as opposed to just the initial scope ... (working on that).
