### ISSUE TITLE
Status of KinD running inside Kubernetes/cri-o

### ISSUE THREAD

**Issue by FWiesner** [kubernetes-sigs/kind#2550]
I am monitoring #303 once in a while. As running KinD in Kubernetes is discouraged, we so far ran Docker in VMs to then run KinD on them although our CI (Gitlab) normally runs all builds in a big Kubernetes (Oracle Container Engine) cluster.

Now several things happen that make us craving for a KinD in Kubernetes solution again.
1. The Kubernetes container runtime we use now is based on cri-o and we would like to be as close as possible to the later production
2. Our builds now actually use podman/buildah as the old Docker-in-Docker approach didn't translate well to Docker-in-cri-o/crun
3. Docker desktop for our developers is no more free (as we are too big)
4. Some developers start to get M1 Macs

So, we truly would love to see KinD successfully running in a pod managed by cri-o. Also CLI support for
`kind create cluster --nested --config ...` - so that developers could quickly spawn a new cluster in a host cluster - would be awesome.

Or as a user story:

As a developer writing Kubernetes operators that control state across whole clusters, I need to quickly bring up fresh K8s clusters as part of acceptance tests in CI and dispose them afterwards. Also I would like to be able to quickly bring up K8s clusters for me to program against remotely as my local development computer is not necessarily able to run x86_64 code despite the fact that our production is. A solution to both in the scope of KinD and supporting K8s/cri-o/crun as host runtime would allow me and my organisation to only wait moments for my cluster to come up in both development and CI use cases and also would allow me to efficiently leverage shared compute instances that already run Kubernetes with enough capacity for growth

Is this aligned with your planned roadmap and if so, could you perhaps share the current status?

**Comment by aojea** [comment]
> So, we truly would love to see KinD successfully running in a pod managed by cri-o.

The runtime should be transparent in #303 , kubernetes project runs kind inside of kubernetes and I know a few other projects that runs it too using crio runtime.

I think that discouraged here means "you need to fully understand what your are doing  and you may hit weird issues that probably you need to fix by yourself " , see the great blog post thee users posted https://github.com/kubernetes-sigs/kind/issues/303#issuecomment-628241352

You may understand that from the kind project perspective is impossible to support these complex setups, but patches are welcome and help will be always provided if is possible

**Comment by FWiesner** [comment]
The challenge is that many users of KinD actually use managed Kubernetes clusters where settings like cgroups configurations cannot be modified. So the question is whether there is a roadmap target to make KinD Kubernetes-aware and free of clashes with the host Kubernetes/container runtime.

**Comment by BenTheElder** [comment]
> I think that discouraged here means "you need to fully understand what your are doing and you may hit weird issues that probably you need to fix by yourself " , see the great blog post this users posted #303 (comment)

+1, running Kubernetes inside Kubernetes has numerous footguns, we do our best to make it possible but we do *not* recommend it. We have to cover it to a limited extent because Kubernetes's own CI is Kubernetes based. As a result we test that specific configuration due to our own need, but we've found it to be pretty difficult to deal with portably. You can see more in #303. There are so many other leaky host problems besides the container runtimes.

> So the question is whether there is a roadmap target to make KinD Kubernetes-aware and free of clashes with the host Kubernetes/container runtime.

There is not. Antonio and I are pretty much running on fumes maintaining the existing support. As-is podman support alone has been pretty expensive, let alone podman-in-cri-o when we don't even officially recommend/support kubernetes in kubernetes period, regardless of runtime.

There's no single Kubernetes environment at this low level and it costs time we don't have to debug this for every pluggable option and without CI we can't ensure there aren't regressions.

We already have an explosion of CI that is overloading GitHub actions, and Kubernetes project's own CI is run on GKE clusters donated by Google, which do not support cri-o.


This simply isn't part of our roadmap or project-scope, both of which are published under [the contributing guide](https://kind.sigs.k8s.io/docs/contributing/getting-started/):

https://kind.sigs.k8s.io/docs/contributing/project-scope/
https://kind.sigs.k8s.io/docs/contributing/1.0-roadmap/

also +1:
> You may understand that from the kind project perspective is impossible to support these complex setups, but patches are welcome and help will be always provided if is possible


See also: https://github.com/kubernetes-sigs/kind/issues/2506

**Comment by BenTheElder** [comment]
Or a shorter version:

We will do our best to review any bug-fix PRs related to podman-in-cri-o quirks but we won't be / shouldn't need to add a flag for this, `kind create cluster` is expected to work in all supported environments, and I don't forsee either of us personally developing for this environment. 

We do test for KIND + `podman`, and even with crun currently,  cgroups v1 and v2, along with docker x (cgroupsv1, cgroupsv2) on linux, and at least the Kubernetes upstream CI in Kubernetes.

If KIND in podman in cri-o in a Kubernetes cluster is not working we'd be happy to see more details and logs and make some effort to point in the right direction of developing a fix, but our support matrix is already barely sustainable given the limited time we have to work on this project.

**Comment by FWiesner** [comment]
Thanks @BenTheElder for the explanation. Sometimes stating what your "no-a-target" thinking is, is a valuable as stating your target. I'll check whether my company is fine with me hacking around a bit.
