### ISSUE TITLE
The configuration uses ipv4, but still uses ipv6 in the configuration

### ISSUE THREAD

**Issue by zyfjeff** [kubernetes-sigs/kind#2567]
**What happened**:
The configuration uses ipv4, but still uses ipv6 in the configuration

[tianqian.zyf@k69c07377 ~]$ kind create cluster --config=config.yaml
Creating cluster "demo-tianqian" ...
ERROR: failed to create cluster: failed to ensure docker network: command "docker network create -d=bridge -o com.docker.network.bridge.enable_ip_masquerade=true -o com.docker.network.driver.mtu=1500 --ipv6 --subnet fc00:f853:ccd:e793::/64 kind" failed with error: exit status 1
Command Output: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
[tianqian.zyf@k69c07377 ~]$ cat config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-tianqian
networking:
  ipFamily: ipv4
  podSubnet: "172.16.0.0/16"
  serviceSubnet: "10.96.0.0/12"

**What you expected to happen**:
 uses ipv4 to create network

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):

**Comment by aojea** [comment]
> Command Output: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

The error is because is not able to create a `docker network` , IPv6 subnet is only used if is available, otherwise should fall back to ipv4 only

```
	if isIPv6UnavailableError(err) {
		// only one attempt, IPAM is automatic in ipv4 only
		return createNetworkNoDuplicates(name, "", mtu)
	}
```

**Comment by BenTheElder** [comment]
And the error / failure is because it can't find an IPv4 subnet, not an ipv6 subnet.

> Command Output: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

You need to configure docker to have more subnets in the IPAM pool, or delete some networks to free up space.
Or for now you can manually pre-create the `kind` network and kind will not delete an object it did not create.

https://docs.docker.com/config/daemon/

https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

"default-address-pools" is the configuration key.

https://support.getjoan.com/hc/en-us/articles/360008889859-How-to-change-the-Docker-default-subnet-IP-address
