### ISSUE TITLE
Create cluster Failed When set '--image=kindest/node:v1.21.1'

### ISSUE THREAD

**Issue by Charlie17Li** [kubernetes-sigs/kind#2570]
**What happened**:

When I create a cluster use the cmd, it's just keep showing '⢎⡱ Ensuring node image (kindest/node:v1.21.1) 🖼 ':
```
kind create cluster --name=karmada-host --kubeconfig=/root/.kube/karmada.config --image=kindest/node:v1.21.1
```
but I use the cmd, it works:
```
kind create cluster --name=karmada-host --kubeconfig=/root/.kube/karmada.config
```

And I notice there are no image with v1.21.1 or latest 
```
[root@k8s-master karmada]# docker images
REPOSITORY                                                                 TAG       IMAGE ID       CREATED        SIZE
kindest/node                                                               v1.20.7   14c4b042989b   6 months ago   1.08GB
kindest/node                                                               <none>    32b8b755dee8   6 months ago   1.12GB
alpine                                                                     3.7       6d1ef012b567   2 years ago    4.21MB
```

**What you expected to happen**:

When I set the 'image', it's still working

**How to reproduce it (as minimally and precisely as possible)**:

```
kind create cluster --name=karmada-host --kubeconfig=/root/.kube/karmada.config --image=kindest/node:v1.21.1
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):kind v0.11.1
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):20.10.11(both client and server)
- OS (e.g. from `/etc/os-release`):centos 8(core)

**Comment by aojea** [comment]
maybe your connection is slow?

try to prepull the image first with `docker pull kindest/node:v1.21.1`

**Comment by aojea** [comment]
most probably it is taking too long to download the node image

**Comment by emirhandogandemir** [comment]
Yeah I have same problem and I doesnt not work kind create cluster --name=emirhan-host --kubeconfig=/root/.kube/karmada.config command . How can ı create with kind a k8s cluster

**Comment by missgriffith** [comment]
I was facing the issue but turns out the problem is indeed my slow connection. Notice the size of each component. I suggest pulling the node first.

` docker pull kindest/node:v1.17.0
v1.17.0: Pulling from kindest/node
cc5a81c29aab: Pull complete
81c62728355f: Pull complete
ed9cffdd962a: Pull complete
6a46f000fce2: Pull complete
6bd890da28be: Pull complete
0d88bd219ffe: Downloading [================================>                  ]  46.32MB/70.94MB
af5240f230f0: Downloading [===>                                               ]  23.72MB/361.4MB`

**Comment by BenTheElder** [comment]
kind actually issues a `docer pull` internally but it must be timing out differently or something

It's true that these are fairly large images unfortunately, I've worked with Kubernetes upstream on multiple release size optimizations and tried pretty hard to exclude non-essential content from kind's own base image. By design these images are a self-contained snapshot of Kubernetes, which does dedupe some of the kubernetes content and ensure everything is compressed when downloading.

**Comment by saeedlk** [comment]
I couldn't even `docker pull` the image. 

When I run 'docker pull kind/node' , this happens:
Using default tag: latest
Error response from daemon: manifest for kindest/node:latest not found: manifest unknown: manifest unknown

I visited the docker hub to get an older version, I tried some versions yet the result was the same. I thought that the images is not for Mac - as I saw only linux/amd64 in OS/ARCH in the tags section in the site. I got confused. what should I do?

**Comment by BenTheElder** [comment]
> When I run 'docker pull kind/node' , this happens:

> When I run 'docker pull kind/node' , this happens:
>Using default tag: latest
> Error response from daemon: manifest for kindest/node:latest not found: manifest unknown: manifest unknown

you have to do one of the images listed in the release notes, we do not publish a "latest" tag.

see:
https://kind.sigs.k8s.io/docs/user/quick-start/#creating-a-cluster

>  I thought that the images is not for Mac - as I saw only linux/amd64 in OS/ARCH in the tags section in the site. I got confused. what should I do?

There's no such thing as a macOS docker image. docker images are linux or windows. Docker on mac is running Linux images in a Linux Virtual Machine.

The images we publish are multi-architecture so CPU architecture doesn't matter.
