### ISSUE TITLE
Kind installation issue

### ISSUE THREAD

**Issue by Kirubason** [kubernetes-sigs/kind#2573]
While trying to install KIND in Linux OS, I am getting below error.

**curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
chmod +x ./kind
mv ./kind /some-dir-in-your-PATH/kind**

![image](https://user-images.githubusercontent.com/59027905/146141152-523c0ba1-00fb-4955-88a2-c64560acddf5.png)

**Comment by aojea** [comment]
some-dir-in-your-PATH is an example, it is not supposed to be taken literally :)

**Comment by BenTheElder** [comment]
you could technically skip this and just use `./kind`, but you'll most likely want to move (`mv`) the program into your PATH in order to be able to use it in the same way as `curl` etc.

https://en.wikipedia.org/wiki/PATH_(variable)

the example is only a place-holder example for where that is, because `PATH` is a configurable list, and we don't know which one you'll want to use on your system, and there's no guarantee of any single standard location across all systems, it's fully configurable.

**Comment by BenTheElder** [comment]
FTR https://github.com/kubernetes-sigs/kind/pull/2859
