### ISSUE TITLE
Docs: Why not minikube?

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/kind#2577]
**What would you like to be documented**:

I would like to have documented: Why not minikube? Why is Kind better?

**Why is this needed**:

Every beginner is facing this question: Which tool to use to play with K8s on the local machine?

I think this answer should be directly on the first page. On this one: https://kind.sigs.k8s.io/

**Comment by aojea** [comment]
We have already a `Why Kind?` section

https://github.com/kubernetes-sigs/kind#why-kind

I personally don't like this idea of adding this comparison to the official docs, sounds more to the typical commercial software looking for users ...

**Comment by afbjorklund** [comment]
I promised earlier to do a FAQ about it.

**Comment by afbjorklund** [comment]
> I think this answer should be directly on the first page.

There is some kind of "answer" on the **Getting started** page:

https://kubernetes.io/docs/setup/learning-environment/

But it doesn't really explain when to choose which tool ?

I think that question is more relevant than "why not" or "is better"

**Comment by guettli** [comment]
Newcomers like me are confused if the should make a decision like this: Should I use minikube or kind?

Thank you for understanding me.

**Comment by afbjorklund** [comment]
It _should_ be more obvious, when to use which of the Kubernetes tools: minikube, kind, kubeadm

It's confusing enough, and then comes all the other k8s vendors and _their_ particular distributions.

**Comment by BenTheElder** [comment]
Why kind exists is that kind was created for the purpose of testing Kubernetes itself. This is outlined very early in the readme and in the landing page of our docs:

> kind is a tool for running local Kubernetes clusters using Docker container "nodes". kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.

Users have since found it useful for other purposes and at the time kind started getting more attention for other purposes minikube supported only VMs and bare hosts, not containers, as that support is directly derived from kind's work) and by user demand we've added more to support these other use cases.

Since then, I'd like to think that the projects collaborate intermittently, as time permits and overlapping issues crop up with nested container hijinks (hi and thank you @afbjorklund!), but they have existing user bases to support and differing driving demands. KIND is still most focused on testing Kubernetes itself, from a staffing perspective, Antonio and I are somewhat supported to work on this.

At this point, users should use whatever suits their needs best, but it is not in the interests of the maintainers of this project to get into some sort of competition with other projects, and comparison matrices tend to serve as vehicles for FUD, even if not intentionally, by virtue of becoming out of date.

You will hopefully find that KIND is very cheap to try out -- we have numerous quick and well documented installation methods as fast as `go get` or `brew install` for one couple megabyte statically linked binary with no external dependencies and you likely already have docker or podman available, at which point you can just `kind create cluster` and see if it suits you.

As mentioned above, https://github.com/kubernetes-sigs/kind/#why-kind covers a bit more about why you might use kind.

We're not interested in documenting why you *wouldn't* want to use minikube, that is not our project, and the state is ever changing, and we'd rather not disparage another project, especially a friendly one  🙃  

> I personally don't like this idea of adding this comparison to the official docs, sounds more to the typical commercial software looking for users ...

And to this comment specifically, from one of my co-maintainers here: 💯 , we are not paid by the user and as such have no desire to engage in these sort of behaviors, we provide kind because we've found it useful ourselves and hope it may be useful to others.

I think the best answer is to inspect the documented feature set for each from their respective docs, and if that's insufficient, just try them out for yourself.

**Comment by guettli** [comment]
@BenTheElder thank you very much for your answer. I created the issue, and will close it again now, since it is much more clear now. I will use `kind` for learning kubernetes, and up to now it works fine. "Thank you" to you and your employer.

**Comment by afbjorklund** [comment]
We're also trying to provide good "exit" information, how to move from a Learning Environment to a Production Environment.

The best place would be the Kubernetes website, at https://kubernetes.io/docs/setup/, that can link further to all the projects.
