### ISSUE TITLE
Docker in Docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by keypointt** [kubernetes-sigs/kind#2598]
Hi,
I'm still beginning stage and maybe this is a naive question...

I'm using KIND to launch k8s cluster and need some docker operation inside the docker node, i.e. Docker in Docker.

And I got below issue `Cannot connect to the Docker daemon`, when parent docker i.e. the node is creating a child docker to do a docker push
```shell
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Pushing container image 11111111.dkr.ecr.us-west-2.amazonaws.com/xxx
Login did not succeed, error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: Cannot perform an interactive login from a non TTY device
Authenticating with existing credentials...
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Docker image could not be updated after 3 attempts
Task exited with error code 1. Raising pod failure

```

I tried below with recommendation to have flag `--priviledged` to access parent docker's mounted location. 
* https://stackoverflow.com/questions/49390573/docker-dind-cannot-connect-to-the-docker-daemon
* https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker
* https://stackoverflow.com/questions/31381322/docker-in-docker-cannot-mount-volume
* https://stackoverflow.com/questions/55055488/jenkins-in-docker-cannot-connect-to-the-docker-daemon-at-unix-var-run-docke/55061100

But when I login to the parent docker (i.e. the node), it seems parent docker is not correctly mounted and docker is not there.

```
>>> exec -it -n namespace some-pod-67fd85d9c5-f4fms -- /bin/bash
(base) root@some-pod-cogitoflow-67fd85d9c5-f4fms:/myapp# docker ps
bash: docker: command not found
(base) root@some-pod-cogitoflow-67fd85d9c5-f4fms:/myapp# docker --priviledged ps
bash: docker: command not found
(base) root@some-pod-cogitoflow-67fd85d9c5-f4fms:/myapp#

```

Is there some step I missed during creating a KIND cluster and have the docker properly up running in a parent docker/pod?

Thank you very much.
Xin

**Comment by keypointt** [comment]
Thank you Benjamin for your explanation on KIND!
Execuse me for my tech terms of KIND/Docker, I'm trying to learn as much as possible while I'm fully understanding the internals.

Maybe a minor follow up question, so my use case is, I created KIND cluster and deployed my app on it, one of the pods of my app was trying to git clone some code then build image then push the built image to aws ecr. 

Then in the pod log I got `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` as I posted above. Meanwhile, no such error msg when I deployed the same app to AWS EKS (where nodes are not docker but regular EC2-instance).

So I guess I might be missing some configuration for the docker-node in KIND cluster, so it behaves differently as in AWS-EKS?

Thank you very much :)

**Comment by BenTheElder** [comment]
this is a bit confusing to talk about 😅 

> Meanwhile, no such error msg when I deployed the same app to AWS EKS (where nodes are not docker but regular EC2-instance).

So to be clear, in either case, the fact that the node is a docker container or AWS EC2 VM or whatever is not actually relevant, just noting that kind does in fact use docker, but only to create the nodes.

To your kubernetes app, all that matters is what is running _within_ the nodes. within the EKS nodes I would guess that they are running docker. KIND nodes do not run docker within them, they run containerd. Your kubernetes pods are containerd containers _within_ the docker container "node", and are not using the docker runtime. Kubernetes does not see docker, your app does not see docker.

People usually call mounting the socket something other than "docker in docker" which usually refers to _running_ a full docker instance inside a docker container. In that respect kind is "containerd in docker" typically.

If you are trying to simply mount the docker socket from the node to your pod, kind nodes do not have a docker socket, because at the node level they are running containerd. kubelet is talking to a per-node containerd instance. Due to the nature of kind, that instance itself happens to be "inside" a docker container "node", but kubelet / kubernetes do not see this.

Portable Kubernetes workloads should *not* assume that docker is running on the node. In the future most kubernetes providers are unlikely to be doing this due to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation

You could run docker inside a kubernetes pod (not mounting the socket, but running a full dockerd instance), though that has security problems in production (as does kind!) and will create additional headache.

I would recommend pushing docker images from your application using something other than docker if you need to do this within Kubernetes, there are a lot of options such as podman, kaniko, etc that can avoid some of the security issues and headache of running docker-in-kubernetes. In the same respect I would not use KIND in production either though 🙃

**Comment by BenTheElder** [comment]
> But when I login to the parent docker (i.e. the node), it seems parent docker is not correctly mounted and docker is not there.

This is by design. Your applications should not expect a docker socket to exist at the node level and it would make kind even less secure to mount the socket from the host to the nodes.

You could add an additional mount to do this with https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts, but I do not recommend it. And your application will soon not work on most major Kubernetes offerings as they transition to containerd or cri-o as the node runtime following https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation

**Comment by keypointt** [comment]
> within the EKS nodes I would guess that they are running docker.
Yes that's right, AWS EKS supports both

> In that respect kind is "containerd in docker" typically.
Thank you, now I fully understand!

> there are a lot of options such as podman, kaniko, etc 
Will try them out, thank you again!

> In the same respect I would not use KIND in production either though
Thanks, only using for internal dev testing

And I'll not stick to docket and explore containerd option, as you recommended from the changelog.

All in all, thank you so much for this long explaining and now I got a quite solid leverage to start with my shadow understanding of container concept. 

I'll close this issue. 

All the best to you! 👍👍👍
