### ISSUE TITLE
Support fedora/centos based node image

### ISSUE THREAD

**Issue by pbxqdown** [kubernetes-sigs/kind#2634]
**What would you like to be added**:
Support fedora/centos based node image

**Why is this needed**:
Sometimes  container inside node is coupled with underlying node OS(e.g. when mount a hostpath)
One example is: https://github.com/kubevirt/kubevirt/issues/4303
In that issue, the problem is caused by ubuntu and fedora having different path of kvm(one is at /usr/libexec/qemu-kvm, other at /usr/bin/kvm). This causes hostpath not loaded correctly.

**Comment by BenTheElder** [comment]
Sorry, but we've already decided in the past that we're not going to support that ourselves, we don't have the bandwidth for this.

You're welcome to build your own custom images, the tooling supports this, but we're not going to build + debug + support this upstream (see `images/base` makefile + `kind build node-image --base-image`).

The details of what is installed in the kind node image are internal to the project, they're just what we need to run Kubernetes, and users are expected to use the Kubernetes API.

Power users depending on the node OS contents are doing so at their own risk, and are beyond what we have the bandwidth to support. The images we supply are subject to change, so we're certainly not going to start advertising any particular OS. They happen to be Ubuntu based at the moment, they've been Debian at other points in time (and dockerd + dockershim instead of containerd / CRI ...). We don't specify, portable Kubernetes usage does not depend on this anyhow.

**Comment by BenTheElder** [comment]
> In that issue, the problem is caused by ubuntu and fedora having different path of kvm(one is at /usr/libexec/qemu-kvm, other at /usr/bin/kvm). This causes hostpath not loaded correctly.

This seems like something that should probably be bind-mounted from the underlying host using https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts

Also, kubevirt should perhaps not expect a particular path for something that can have multiple paths? In kubernetes e.g. cgroup mount point is configurable.

**Comment by pbxqdown** [comment]
Thanks for fast response! 
I'm wondering whether building node-image ourselves is simply replacing BASE_IMAGE var with "centos" or there is large effort to make it work.
Yeah agree that better support may be needed on kubevirt side to support multi-OS environment.

**Comment by BenTheElder** [comment]
Sorry, just getting back to this:
> I'm wondering whether building node-image ourselves is simply replacing BASE_IMAGE var with "centos" or there is large effort to make it work.

Unfortunately no, given that debian/ubuntu and centos/fedora have different package management systems.
The node image build process only depends on a few things though, the general image layout and tool installations, so it would be possible to fork the image and build one that works with the rest of the tooling. It will be tricky to maintain though.

I think it would be best to configure kubevirt instead, or add some small patch on top of the standard node image you are using (something like `FROM $NODEIMAGE; RUN # add symlink or other workaround`)
