### ISSUE TITLE
Rootless docs do not explain the security aspects of Delegate=yes

### ISSUE THREAD

**Issue by danwinship** [kubernetes-sigs/kind#2800]
**What would you like to be documented**:

https://kind.sigs.k8s.io/docs/user/rootless/ notes that on some systems, you may need to set `Delegate=true` in the systemd configuration. However, it completely fails to explain why this is necessary, or more precisely, why systemd is not configured this way by default, and what the potential downsides of changing the configuration are.

**Why is this needed**:

Well, it immediately reminded me of the longstanding recommendation to configure docker so that you could run the `docker` command as any user, which no one ever bothered to mention was equivalent to giving passwordless `sudo` access to every user... makes me wonder what other things I can do if I make this `Delegate=true` change...

**Comment by AkihiroSuda** [comment]
>  why this is necessary

For supporting `.resources.limits.cpu`.

> why systemd is not configured this way by default

By default, systemd delegates the `memory` and `pids` controllers but leaves the `cpu` controller undelegated because
"the runtime impact of that is still too high".

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZMKLS7SHMRJLJ57NZCYPBAQ3UOYULV65/

> what the potential downsides of changing the configuration are.

Negative performance impact may happen. Benchmarking is wanted.
