### ISSUE TITLE
Kind 0.14.0, M1: ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 0 lines

### ISSUE THREAD

**Issue by pigmej** [kubernetes-sigs/kind#2890]
**What happened**:

I tried to setup a kind cluster on my mac m1. Sadly it fails with an error like:
```
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 0 lines
```

The full stack trace is:
```
pigmej ~ $ kind create cluster -v 1 --retain=true
Creating cluster "kind" ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e present locally
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✓ Preparing nodes 📦
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: file should only be one line, got 0 lines
Stack Trace:
sigs.k8s.io/kind/pkg/errors.Errorf
	sigs.k8s.io/kind/pkg/errors/errors.go:41
sigs.k8s.io/kind/pkg/cluster/nodeutils.KubeVersion
	sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go:42
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.getKubeadmConfig
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:158
sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config.(*Action).Execute.func1.1
	sigs.k8s.io/kind/pkg/cluster/internal/create/actions/config/config.go:90
sigs.k8s.io/kind/pkg/errors.UntilErrorConcurrent.func1
	sigs.k8s.io/kind/pkg/errors/concurrent.go:30
runtime.goexit
	runtime/asm_arm64.s:1263
```

I tried to check what's the problem more deeply but there seem to be no obvious enough way to debug that. The docker container started fine.

**What you expected to happen**:

The cluster running :)

**How to reproduce it (as minimally and precisely as possible)**:

```kind cluster create``` 

**Anything else we need to know?**:

I have attached cluster logs from `kind export logs`:  [1862585104.zip](https://github.com/kubernetes-sigs/kind/files/9380807/1862585104.zip)

**Environment:**

- kind version: (use `kind version`): 0.14.0
- Kubernetes version: (use `kubectl version`): 1.24.0
- Docker version: (use `docker info`): I'm using podman instead of docker but I have enabled docker compatibility there.
[docker.txt](https://github.com/kubernetes-sigs/kind/files/9380797/docker.txt)
- OS (e.g. from `/etc/os-release`): macOS Monterey 12.5.1

**Comment by BenTheElder** [comment]
The first problem is that this is running in docker mode instead of podman mode. On Linux we're usually able to detect that the podman docker is fake and actually podman, podman is *not* docker compatible.

KIND_EXPERIMENTAL_PROVIDER=podman can force podman mode.

> there seem to be no obvious enough way to debug that. The docker container started fine.

You can increase verbosity to see more but the check on preparing nodes means the containers started.

I think podman on Mac had other issues in the tracker.

**Comment by BenTheElder** [comment]
> I'm using podman instead of docker but I have enabled docker compatibility there.

Hmmm, are you? the `docker info` output appears to be genuinely from docker, can you elaborate? Is this the docker CLI but talking to podman? (as opposed to a symlink/script called "docker" that is the podman binary).

I don't think we support this yet, because we need to know it's really podman so we can support podman's differences.


From [1862585104.zip](https://github.com/kubernetes-sigs/kind/files/9380807/1862585104.zip)  we can see the container is running (inspect.json) and that kind thinks it is running with docker. But for some reason `docker exec --privileged kind-control-plane cat /kind/version` failed to print any lines even though that internal file is statically in all our images.

**Comment by pigmej** [comment]
Hey,

Yes normal docker cli talking to podman docker socket directly with docker API. But maybe there is some bug there that prohibits correct operation in *all* cases.

Let me check directly with podman without docker API compatible socket.

**Comment by pigmej** [comment]
So I have checked directly with docker (lima for the rescue) and it works ok. So there was something weird happening there I think.

**Comment by BenTheElder** [comment]
> Yes normal docker cli talking to podman docker socket directly with docker API. But maybe there is some bug there that prohibits correct operation in all cases.

kind is a pretty deep user and they don't quite have identical behavior at least in local podman (no socket just podman) mode. We haven't tested docker socket mode currently, our CI matrix is on these dimensions:
- docker or podman
- rootfull or rootless
- cgroupsv2 or v1
- kubernetes versions

> lima for the rescue

lima seems to be a great option 👍
