### ISSUE TITLE
Improve output of kind delete cluster

### ISSUE THREAD

**Issue by mk46** [kubernetes-sigs/kind#2924]
**What would you like to be added**:
cluster delete cmd should acknowledge whether a cluster was `deleted successfully` or `cluster not found`
**Why is this needed**:
`kind delete cluster --name <--existing-cluster-->`  and 
`kind delete cluster --name <--not-existing-cluster--> ` are
giving the output as below
`Deleting cluster <clustername>  ...`
which silent the information about non-existing cluster or deleted successfully.

**Comment by stmcginnis** [comment]
This is expected and by design. See first note under https://kind.sigs.k8s.io/docs/user/quick-start/#deleting-a-cluster

Basically you are telling kind that you don't want `foo` to exist, and it returns that it doesn't. Whether it existed beforehand or not does not matter.

If for some reason you need to know whether it exists first, you would need to get clusters to see if it is in the list. There shouldn't be a reason on delete to care.

**Comment by BenTheElder** [comment]
This command is like `rm`.
We could provide more debug output around the specific actions taken but it's meant to be reentrant and safe to call from multiple tear down points in a script (like trapping EXIT).

**Comment by BenTheElder** [comment]
/triage accepted
I think we should probably log if we take any actions ("deleting node xyz", "removing entry from kubeconfig"), or a message about not needing to take any action, to limit the confusion.

**Comment by oxr463** [comment]
@BenTheElder I'd like to take a crack at adding this.
