### ISSUE TITLE
does it possible to let kind k8s use host's docker context?

### ISSUE THREAD

**Issue by jian1106** [kubernetes-sigs/kind#2944]
i am using kind in my wsl2 and i found that kind does not use images which i pulled from my private registry. Pods in k8s keeps reporting `ImagePullBackOff`.

**Comment by stmcginnis** [comment]
Since the Kubernetes cluster is running inside containers it does not have access to your image. You have a couple options.

You can manually load the images into your cluster using `kind load docker-image`. Instructions on doing that can be found here: https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster

You can also run a local image registry. Similarly to above, you would need to push the images you want to use into this registry to access them. Details for that are here: https://kind.sigs.k8s.io/docs/user/local-registry/

**Comment by jian1106** [comment]
OK, i got it. Thanks for your replying.
