### ISSUE TITLE
How can I resolve a domain name through the host machine? 

### ISSUE THREAD

**Issue by Polyhistor** [kubernetes-sigs/kind#2945]
We've got a dev environment setup in which a part of our services are inside Kubernetes (using kind) and a part of it is not. Inside the Kubernetes pod, a request is made to a certain host (localdev.companyName.com), we own this domain and return 127.0.0.1 everytime a request is made (this was to avoid having to resolve host locally in dev computers).

While this is fine when we run our docker instances on the host ( app instance is listening on 127.0.0.1 on port 80, so the frontends can easily communicate ), this is not okay when we want to make a network request from inside the Kubernetes pod to that app instance.

This is due to the fact that 127.0.0.1 inside the kubernetes cluster is not associated to any docker instance, and we need the docker instance from the host. So my question is how can I configure my pod to resolve localdev.companyName.com to the loopback address of the host instead of Kubernetes node one ?

I tried [ExternalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) with the following configurations to no avail ( it's a Terraform Code )

```
resource "kubernetes_service" "my-service-external-name" {
  metadata {
    name      = "my-service-external-name-external-name"
    namespace = namespace name
enter code here
    annotations = {
      "app.kubernetes.io/name" = "localdev.companyName.com"
    }
  }

  spec {
    type          = "ExternalName"
    external_name = "host.docker.internal"
  }

}
```

I've also researched about [headless services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services). I've read this [question](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) too.

**Comment by BenTheElder** [comment]
> So my question is how can I configure my pod to resolve localdev.companyName.com to the loopback address of the host instead of Kubernetes node one ?

loopback addresses are local to the local namespace, they cannot cross network namespaces.

You would have to resolve to something else that routes to the host and either proxies or is an address the host application is listening on.

For anyone finding the issue title "How can I resolve a domain name through the host machine?"

KIND *does* resolves non-cluster DNS entries with the host's resolver when running with docker (not podman).
So the issue here is "how do I resolve to something that routes traffic to the host".

Which is the host.docker.internal IP.

One possible option: Add a `/etc/hosts` entry to your pods, pointing at the host.docker.internal IP.
https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
