### ISSUE TITLE
Is kinds Kubeapi allowing anonymous access?

### ISSUE THREAD

**Issue by miathedev** [kubernetes-sigs/kind#3134]
Dear **kind** community,

Im using kind for my bachelor thesis cluster setup.
Is the kind kubeapi protected against anonymous access?

I took a look at the cfg configured by kind:
```
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    ...
```

Is it correct, that only client with the corresponding certifcate is able to connect? I searched for the flag:
```
--anonymous-auth=false
```
but couldnt find it there. Should i create a dedicated RBAC User and add the flag?

Im quite new into the kubernetes topic and want to be sure that if one of my deployed pods are hacked no one is able to misuse my cluster.

Im pipeing https (443) and http (80) into the kind cluster with an external ip. Im feeling really uncomfortable doing this.

**Comment by BenTheElder** [comment]
> Im quite new into the kubernetes topic and want to be sure that if one of my deployed pods are hacked no one is able to misuse my cluster.
>
> [...]
>
> Im pipeing https (443) and http (80) into the kind cluster with an external ip. Im feeling really uncomfortable doing this.

Don't expose kind to the internet. It isn't by default. See the warning on the config that would without adding pipes:
https://kind.sigs.k8s.io/docs/user/configuration/#api-server

If nothing else, kind doesn't have upgrades etc, because it's meant for disposable test clusters and Kubernetes is testing that with a hackier extension not focused on other use cases.

No upgrades means you're not getting security patches. That alone should be reason enough to not expose the cluster.

However, only the user with the cert has cluster-admin access.

If you want to host a cluster exposed to the internet, see https://kubernetes.io/docs/setup/production-environment/, https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/

**Comment by miathedev** [comment]
Thank you both for your response. Im going to go further exactly like you said.
