### ISSUE TITLE
Release support matrix for kind

### ISSUE THREAD

**Issue by humblec** [kubernetes-sigs/kind#3141]
I was trying to figure out the release cadence of kind releases. That said, the last kind release available here `1.17.0` also have below node image hashes with it.. 

```
New Node images have been built for kind v0.17.0, please use these exact images (IE like kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1 including the digest) or build your own as we may need to change the image format again in the future 😅

Images built for this release:

1.25: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
1.24: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
1.23: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
1.22: kindest/node:v1.22.15@sha256:7d9708c4b0873f0fe2e171e2b1b7f45ae89482617778c1c875f1053d4cef2e41
1.21: kindest/node:v1.21.14@sha256:9d9eb5fb26b4fbc0c6d95fa8c790414f9750dd583f5d7cee45d92e8c26670aa1
1.20: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
1.19: kindest/node:v1.19.16@sha256:476cb3269232888437b61deca013832fee41f9f074f9bed79f57e4280f7c48b7
```

my questions are :

1) as seen above, this release have built for Kubernetes releases which are EOL too. for ex: v1.19.0 was EOL @26 Aug 2020, is it expected that, `kind` build at least 6 Kubernetes node image versions with each of its releases , starting from latest available release ?
2) Why the images are built for versioned which are EOL too?
3) is there any release cadence followed here ? the last release happened on Oct 26, 2022, when is next release expected ?
4) If there is a critical CVE fix available or has to be done on any of the images available with a kind release , does this project make a release to support the fix ? 

It would be appreciated if you can provide more details about the release process and expectations. I am more than happy to get it documented here too!

cc @aojea @BenTheElder

**Comment by BenTheElder** [comment]
This isn't documented more than it already is because we haven't made deeper commitments yet.

There's several issues discussing what to do about releasing prebuilt images, recently distracted by the various registry announcements 😅

kind pre-built images are best-effort, primarily built with kind releases, which are at least as often as Kubernetes minor releases but sometimes more often if we feel we've patched a critical bug. Images are always built at the latest available patch releases.

A core workflow for kind is users building their own node images, which is in our QuickStart guide.

The docs already note that pre-built images should come from the release notes both for security and as sometimes we have kind binary / node image skew issues when fixing tricky bugs / changes with kubernetes or Linux etc

We expect another release any time now. We've been delayed by #3124 and the registry.k8s.io redirect (I'm working on this more or less full time until we're at a better place keeping Kubernetes sustainably funded).

4) It depends? If the CVE is in kind or one of the third party dependencies like containerd we'd consider that a critical bug and cut a release. If it's found in an older kubernetes there's not much we can do .

**Comment by BenTheElder** [comment]
Kind also supports Kubernetes @ HEAD at all times but we don't publish official builds for that since it's aimed at Kubernetes developers.

We've been recently attempting -3 additional versions to help people test their applications etc but we previously kept as many as possible and found that didn't work well so we haven't committed to keep -3 forever either.

**Comment by BenTheElder** [comment]
2) would be https://kind.sigs.k8s.io/docs/contributing/project-scope/#p1-support-testing-kubernetes-applications

**Comment by BenTheElder** [comment]
For any given release we have best effort support back as far as we can go. When we need to depend on some change or drop dead code for a very old release the release notes state this, but only current versions can be fully supported since we do not fork Kubernetes.

For forward releases it's also YMMV, kind often works fine with newer Kubernetes releases that didn't exist when kind was released and we aim to make that true but it's not possible to 100% guarantee. Known good versions are in the release notes image list

**Comment by BenTheElder** [comment]
> At least n-3 versions of the node images are considered in priority for critical fixes and rest of the versions are ( n-3 to -6) are best effort basis.
> Also, there is no guarantee to continue producing the releases of N-6 versions with each kind release in future.
>
>Does that conclude to an extent ?

Pretty much! To clarify the "n-3" is actually "all supported versions of Kubernetes that the Kubernetes project supports, AND the latest unreleased Kubernetes source code (which may require using the latest kind source code as well, but will at least work with the latest kind source code)" https://kubernetes.io/releases/

Kubernetes at times has 3-4 minor versions being supported currently, and then we also have the latest unreleased changes on all supported release branches AND on Kubernetes `master`.

**Comment by BenTheElder** [comment]
If Kubernetes changed the core version support policy, we would follow and still consider our best to support some older releases that no longer receive patches to help users transition. But ensuring the latest Kubernetes works always comes first when prioritizing issues etc.

**Comment by BenTheElder** [comment]
On a related note working on updates for the runc CVEs :-)
