### ISSUE TITLE
consider to provide the feature like minikube  ，Point Docker CLI to minikube

### ISSUE THREAD

**Issue by misaya98** [kubernetes-sigs/kind#3187]
minikue has a feature   to use minikube as a Docker Desktop replacement;

https://minikube.sigs.k8s.io/docs/tutorials/docker_desktop_replacement/

**What would you like to be added**:

**Why is this needed**:
no need to  use load command to load local image;

i don't konw if it is possible in kind.

**Comment by aojea** [comment]
do you mean `kind load docker-image`?

**Comment by BenTheElder** [comment]
No our container runtime is containerd, not dockerd. Kubernetes hasn't supported dockershim mode since 1.24 and the external dockershim project is not something I'd recommend.

While something like buildkit against containerd could be setup, kind clusters are meant to be ephemeral and have had multi-node and multi-cluster support from the beginning, in which case building to a single node doesn't make much sense vs building to the host and pushing to a local registry or side loading with kind load.

**Comment by misaya98** [comment]
> do you mean `kind load docker-image`?

yes

**Comment by aojea** [comment]
then is already there, what else do you miss?

**Comment by afbjorklund** [comment]
If you want to build your container images on the control plane, or if you don't have access to Docker (or perhaps Podman), you might as well use minikube instead of kind... Since that is basically the major difference between them ?

I was hoping for `kubectl build` to provide an easy to use alternative, but its development seems to have stopped... I wouldn't recommend using the legacy `docker-env`, since it is stopping progress towards the more open standards.

**Comment by BenTheElder** [comment]
> If you want to build your container images on the control plane, or if you don't have access to Docker (or perhaps Podman), you might as well use minikube instead of kind... Since that is basically the major difference between them ?

I think there are a few more differences but, I wouldn't recommend leaning into cri-dockerd at this point.


For maximum efficiency I'd recommend something like https://kind.sigs.k8s.io/docs/user/private-registries/ (also something comparable with minikube and other tools)

- persists across clusters, including multiple clusters, restarts, etc.
- de-dupes layers
- only move new layers
- portable
- ~same setup can be used against production clusters just by changing out the registry hostname

otherwise `kind load` is the simple option and something like https://github.com/moby/buildkit/tree/master/examples/kubernetes is the advanced mode

**Comment by BenTheElder** [comment]
If the goal is to get a running daemon for building dockerfiles buildkit is a good alternative.

If the goal is to run containers and have a linux VM on mac/windows: then +1 to @afbjorklund's comment: use minikube in one of the VM driver modes, or else tools like lima / colima, etc. 

kind itself runs containers so it needs a container runtime to work, it can't host the initial container runtime, that's completely out of scope.

**Comment by afbjorklund** [comment]
> I think there are a few more differences but, I wouldn't recommend leaning into cri-dockerd at this point.

There are implementations available for all container runtimes, like buildkit for containerd and podman for cri-o.

**Comment by afbjorklund** [comment]
@BenTheElder : theoretically kind _could_ have some convenience wrapper, similar to `kind load docker-image` ?
As in something like `kind build docker-file`, but then again it would just be wrapper for `docker build`*...

\* like how the other one is a wrapper for `docker save`

That was the original goal of the `minikube image` command, to not have to learn Docker to use Kubernetes.
Well you did have to learn some Dockerfile, but not how to convert it into an image for loading into the cluster.

* https://github.com/kubernetes/minikube/issues/4868
