### ISSUE TITLE
Excuse me, does not support version 1.24.2?

### ISSUE THREAD

**Issue by shuncon** [kubernetes-sigs/kind#3200]
Excuse me, does not support version 1.24.2?

**Comment by shuncon** [comment]
I searched the tag again and couldn't find 1.24.2

**Comment by BenTheElder** [comment]
If you need a hyper specific version you'll have to build it yourself using the guide under the quick start in the docs.

otherwise every kind release comes with a set of images for the latest patch version of all supported kubernetes minor versions. Please see the docs or release notes for usage on these
