### ISSUE TITLE
Kind cluster not able to Pull the CNI image

### ISSUE THREAD

**Issue by tppalani** [kubernetes-sigs/kind#3203]
**What would you like to be documented**:

When the system is connected to VPN network kind cluster not able to pull the network CNI plugin due to this control plane component is not ready state not able to deploy a pod until getting ready.

**Why is this needed**:
POD is not getting ready due to control plane node is not ready state.

**Comment by tppalani** [comment]
Hi @BenTheElder  Thank you so much i can able to pull the image kindest/node:v1.27.1@sha256:c44686bf1f422942a21434e5b4070fc47f3c190305be2974f91444cd34909f1b, may i know the reason why I can't able to use the latest release image, and may i know what the changes has been added in the specific image (kindest).

This would be really helpful if you explain to understand, because we are going to rollout kind cluster to dev team.

**Comment by BenTheElder** [comment]
We were pre-loading some of the images by digest instead of tag in v0.18, the way we did this caused the image contents to be pre loaded in the node runtime but still require a lookup to the registry at runtime, breaking airgapping. The fixed image doesn't do this.

Unfortunately there are other problematic changes since v0.18 so we haven't cut a release yet, we need to either rollback runc or wait for kubernetes patches. The Kubernetes patches are in except one but the releases there aren't out yet and it won't be backported to releases Kubernetes doesn't support so ... not sure how we're handling this yet.

**Comment by BenTheElder** [comment]
In a PR that just merged I've decoupled the runc and containerd versions and overhauled how we ship those quite a bit so we have more options now
