### ISSUE TITLE
Add the customCNIManifest parameter in the deployment configuration file

### ISSUE THREAD

**Issue by whzghb** [kubernetes-sigs/kind#3285]
**What would you like to be added**:
The cni manifest is hard-coded in the source code. When deploying a kind cluster, is it possible to add a parameter to the configuration file to specify other manifests? For example
networking:
&ensp; customCNIManifest: "./calico.yaml"

**Why is this needed**:
The current implementation is that if we want to use other cni, we can only disable the deployment of cni when deploying the kind cluster, and then manually install other cni in the cluster. If we can specify it during deployment, there is no need for manual operation.

**Comment by aojea** [comment]
> f we can specify it during deployment, there is no need for manual operation.

this is on purpose, adding another cni manifest on the cluster creation can break the cluster startup and will increase the possibility of bugs and difficult the supportability, since all the bugs related to startup caused by external cni plugins will be directed to kind.

Existing method works well and the optimization is just one line of code on users scripts that will move from the kind startup script to the kind config
```
kind create cluster (disableCNI)
kubectl apply -f calico.yaml
```

**Comment by whzghb** [comment]
> this is on purpose

ok, got it, thanks for your reply
