### ISSUE TITLE
Namespace owned by another Namespace not deleted/garbage-collected when parent is deleted

### ISSUE THREAD

**Issue by opethema** [kubernetes-sigs/kind#3308]
**What happened**:
If I have two namespaces and one of them is owned by the other, and I delete the parent, then the child isn't deleted.
Namespaces are cluster-scoped so this should work...
I tried it on a bare metal cluster that I created using kubespray with the same kubernete version (1.26.3) and the child Namespace was deleted when the parent is deleted.
If I try on another resource like two configmaps in the same namespace it works fine (child configmap will be deleted when parent configmap is deleted).

this is an example of what I tried:

`cat <<EOF | kubectl create -f -`
`apiVersion: v1`
`kind: Namespace`
`metadata:`
`  name: parent`
`EOF`

========

`NS_UID=$(kubectl get namespace parent -o jsonpath="{.metadata.uid}")`

========

`cat <<EOF | kubectl create -f -`
`apiVersion: v1`
`kind: Namespace`
`metadata:`
`  name: child`
`  ownerReferences:`
`  - apiVersion: v1`
`    kind: Namespace`
`    name: parent`
`    uid: $NS_UID`
`EOF `

**What you expected to happen**:

when I delete the parent Namespace, the child Namespace should be deleted as well.

**Environment:**

- kind version: (use `kind version`): v0.18.0
- Runtime info: (use `docker info` or `podman info`): Server Version: 23.0.1  - runc version: v1.1.4-0-g5fd4c4d 
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.2 LTS - Kernel Version: 5.15.0-67-generic
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:34:50Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by stmcginnis** [comment]
It doesn't sound like this is anything related to Kind.

**Comment by stmcginnis** [comment]
Not really sure... maybe ask in #sig-api-machinery?

I do notice your `kubectl` client is more than one minor version behind the cluster. I don't really think it would make a difference, but to be using a supported configuration you could upgrade `kubectl`.

I still don't think `kind` would have an impact here, but you are also using an older release of kind. Maybe try reproducing with the latest release to see if it picked up anything that could be contributing.

You also didn't actually include the output from `docker info` or `podman info`. That could tell a little more about your environment, but that probably isn't actually needed.

So my advice would be to upgrade your tooling first and try to reproduce the failure to see if it's pulling in something that has since been fixed. Then ask in the API machinery slack channel what the best course would be to figure out what is going on.

**Comment by kundan2707** [comment]
i tried with kind -.20 and same events detected.
deleting parent namespace donot delete child namespace

**Comment by BenTheElder** [comment]
This isn't a kind bug, this logic comes from the kubernetes API server
/transfer kubernetes/kubernetes

**Comment by BenTheElder** [comment]
/close
I'm not sure if this is actually expected to be supported to be honest, but that would be a conversation with SIG API Machinery in https://github.com/kubernetes/kubernetes

This behavior is not kind specific, we're running an unpatched purely upstream api server.
