### ISSUE TITLE
When I use proxy, it tells me Unable to connect to 127.0.0.1:7890

### ISSUE THREAD

**Issue by LiDaiyan** [kubernetes-sigs/kind#3416]
In the container, i typed apt update, and it tells me Unable to connect to 127.0.0.1:7890. I know i have set the http_proxy, but i dont know how to fix it. there should be a way to set the proxy port.

`kind create cluster
docker ps -a
docker exec -it e8143bc1bb42 bash
apt install lspci`

All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to 127.0.0.1:7890 (127.0.0.1). - connect (111: Connection refused)
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to 127.0.0.1:7890:
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to 127.0.0.1:7890:
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Environment:**

- kind version: (use `kind version`):latest
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`): ubuntu22.04
- Kubernetes version: (use `kubectl version`):latest
- Any proxies or other special environment settings?:clash proxy: export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5://127.0.0.1:7890

**Comment by nekomeowww** [comment]
Where did you set the `HTTP_PROXY`, `HTTPS_PROXY` and `ALL_PROXY`? Did you set them on host or inside container?

Proxy issues have nothing to do with `kind` itself in general unless you have a complex `iptables` with container runtime and network stack in general. Please check and investigate it with executing

```shell
env
```

inside of the container `e8143bc1bb42` you are referring.

If you set all the `HTTP_PROXY`, `HTTPS_PROXY` and `ALL_PROXY` environment variables on host, these three environment variables won't be passed when you execute `docker exec`.

Please set the environment variables **inside of the container** or pass these environment variables with `-e`.

If you already set the proxy environment variables inside of the container as you stated:

```shell
export https_proxy=http://127.0.0.1:7890;export/ http_proxy=http://127.0.0.1:7890;export/ all_proxy=socks5://127.0.0.1:7890
```

Then this won't be going to work since `127.0.0.1` with the port `7890` is not exist inside of the container, therefore you will need to set the proxies environment variables like this in order to be able to use the proxy servers from host:

```shell
export https_proxy=http://host.docker.internal:7890 http_proxy=http://host.docker.internal:7890 all_proxy=socks5://host.docker.internal:7890
```

Or with Podman:

```shell
export https_proxy=http://host.containers.internal:7890 http_proxy=http://host.containers.internal:7890 all_proxy=socks5://host.containers.internal:7890
```

To learn more about the `host.docker.internal` and `host.containers.internal`, please refer to [Docker documentation](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) and [StackOverflow about the equivalent of `host.docker.internal` in Podman](https://stackoverflow.com/a/75913128/19954520).

If you encountered more connectivity issues with these two `host.docker.internal` and `host.containers.internal` hostnames, try investigate your hosts with the command below:

```shell
getent hosts host.docker.internal
```

or `host.containers.internal`:

```shell
getent hosts host.containers.internal
```

---

Tips: You could troubleshoot your HTTP connectivity with the following command:

```
curl  http://deb.debian.org/debian/dists/bullseye/InRelease -I -v
``` 

and try to locate the term `Uses proxy env variable` and `7890` the printed results when next time you are encountering the same issue.

For example, the output may look like this:

```shell
root@kind-control-plane:/# export https_proxy=http://host.docker.internal:7890 http_proxy=http://host.docker.internal:7890 all_proxy=socks5://host.docker.internal:7890
root@kind-control-plane:/# curl http://deb.debian.org/debian/dists/bullseye/InRelease -I -v
* Uses proxy env variable http_proxy == 'http://host.docker.internal:7890'
*   Trying fd07:b51a:cc66:f0::fe:7890...
* Connected to host.docker.internal (fd07:b51a:cc66:f0::fe) port 7890 (#0)
> HEAD http://deb.debian.org/debian/dists/bullseye/InRelease HTTP/1.1
```

**Comment by LiDaiyan** [comment]
Thanks, i learned a lot.
`HTTP_PROXY`, `HTTPS_PROXY` and `ALL_PROXY` is set in the `$HOME/.bashrc` on the host.
I tried the way to change to proxy in the container

> export https_proxy=http://host.docker.internal:7890 http_proxy=http://host.docker.internal:7890 all_proxy=socks5://host.docker.internal:7890

and then i get 

```
root@kind-control-plane:/# apt update
Err:1 http://deb.debian.org/debian bullseye InRelease
  Could not resolve 'host.docker.internal'
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Could not resolve 'host.docker.internal'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Could not resolve 'host.docker.internal'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not resolve 'host.docker.internal'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Could not resolve 'host.docker.internal'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Could not resolve 'host.docker.internal'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
then i test the  HTTP connectivity as you said
```
root@kind-control-plane:/# curl http://deb.debian.org/debian/dists/bullseye/InRelease -I -v
* Uses proxy env variable no_proxy == '172.20.0.0/16,fc00:f853:ccd:e793::/64,localhost,127.0.0.0/8,::1,10.96.0.0/16,10.244.0.0/16,kind-control-plane,.svc,.svc.cluster,.svc.cluster.local'
* Uses proxy env variable http_proxy == 'http://host.docker.internal:7890'
* Could not resolve proxy: host.docker.internal
* Closing connection 0
curl: (5) Could not resolve proxy: host.docker.internal
```
Thanks!

**Comment by tao12345666333** [comment]
no

You can just unset these environments

Don't need set any values to them

**Comment by nekomeowww** [comment]
> ```
> root@kind-control-plane:/# apt update
> Err:1 http://deb.debian.org/debian bullseye InRelease
>  Could not resolve 'host.docker.internal'
> ```

What kind of container runtime are you using? Docker or Podman? What will happen if you unset all the environment variables?

Actually, just like what @tao12345666333 have said, you can `unset` these environment variables since [http://deb.debian.org/debian/dists/bullseye/InRelease](http://deb.debian.org/debian/dists/bullseye/InRelease) should be accessible from all around the world.

You might need to investigate further more with your container runtime and setup due to the lack of information.

**Comment by LiDaiyan** [comment]
Thanks for @tao12345666333 and @nekomeowww !
I solved the problem.

**Comment by tao12345666333** [comment]
Congrats 🎈 

Since the issue has been resolved, I will close this one.

/close

**Comment by csb123452010** [comment]
Thanks to the above answer, the final solution is actually very simple. If you are using the desktop version of Ubuntu and have already prepared a proxy (Clash), you just need to refer to the following picture to set the IP. That is to say, do not set 127.0.0.1, but use the IP obtained from the command `ifconfig`.

<img width="230" alt="Image" src="https://github.com/user-attachments/assets/dcb756c3-b074-4d7d-b616-58e9c5c5e6e8" />
