### ISSUE TITLE
How to update and patch the configuration of existing deployed kind cluster

### ISSUE THREAD

**Issue by nekomeowww** [kubernetes-sigs/kind#3420]
## Summary

As title stated, how to update and patch the cluster configuration of existing deployed kind cluster? For example, `extraPortMapping`, `extraMounts`, or event add more workers nodes?

## Background

When creating demo clusters, develop helm charts, testing alerting components, integrating mechanisms such as ingress, OpenTelemetry and etc, it is often needed to add or extends more resources to Kubernetes cluster, which introduces more and more port mappings and volume mounts for newly deployed resources.

## Question

Docker doesn't provide a method to modify both of the network, and storage with a started container. (does it?)

How can I (as being a user) add more port mappings to my deployed kind? Is `kind delete cluster` and then recreate everything that needed with `kind create cluster --config ...`, `helm install` the only way to achieve this? Is `kind update` or `kind patch` possible to be implemented for such requirements and needs?

**Comment by BenTheElder** [comment]
> Docker doesn't provide a method to modify both of the network, and storage with a started container. (does it?)

Right, which is why kind doesn't either, you need to recreate the cluster.
We've optimized for the speed of cluster creation instead, they're meant to be disposable test clusters

You can forward ports via other means, like `kubectl port-forward` or running a `socat` docker container, but if you want to send traffic through an ingress you should plan up front for how many ports you need on the host at the moment.

**Comment by nekomeowww** [comment]
> You can forward ports via other means, like `kubectl port-forward` or running a `socat` docker container, but if you want to send traffic through an ingress you should plan up front for how many ports you need on the host at the moment.

Sure, this is viable. But what about mounts and nodes? Is that possible to implement something like `kind update` or `kind patch`, or perhaps `kind recreate` (feels like more aligned with the semantic for this sub-command IMO) to distribute an automated task for the node shutdown, recreation but in the way automatically while still align with the current design? More like a combination of `kind delete cluster --name` and `kind create --config <...> --name <...>`.

For example:

1. garbage collect the created nodes, resources gracefully as usual
2. recreate cluster with new supplied configuration

Furthermore, can we create an extra layer that holds the ports, mounts, nodes specs and install `kind` as a daemon so it could somehow behave like a Kubernetes resource where user could apply, patch, edit, describe and delete interactively or with more DX in it when used in development? I think such feature could gain significant performance and DX for developers for them to bootstrap their cluster more quickly, easily, and viably.

**Comment by BenTheElder** [comment]
I'm sorry but this is not worth the complexity, you should explicitly delete and recreate, we should not implement _partial_ mutation.

Recreation is destructive, should be acknowledged, and using delete + create is not much more work than one command.

"recreate" is not a built in semantic in any other project tool and I don't want to invent a new verb here for the sake of paring down two trivial commands to one.

We don't have "patch" because that behavior has an expectation to mutate in place and most of the aspects of the containers in docker are immutable. 

> Furthermore, can we create an extra layer that holds the ports, mounts, nodes specs and install kind as a daemon so it could somehow behave like a Kubernetes resource where user could apply, patch, edit, describe and delete interactively or with more DX in it when used in development? I think such feature could gain significant performance and DX for developers for them to bootstrap their cluster more quickly, easily, and viably.

This is a LOT of work and against the spirit of being a lightweight tool, kind is embedded in many test runners etc and should not become a daemon. 

https://kind.sigs.k8s.io/docs/contributing/project-scope/
https://kind.sigs.k8s.io/docs/design/principles/

**Comment by nekomeowww** [comment]
> https://kind.sigs.k8s.io/docs/contributing/project-scope/
> https://kind.sigs.k8s.io/docs/design/principles/

Thank you very much for the resources here, I read them depth and agreed with your opinion.
I will close since this is out-of-scope of what `kind` meant to be.
