### ISSUE TITLE
Create setup-kind GitHub Action 

### ISSUE THREAD

**Issue by mmorel-35** [kubernetes-sigs/kind#3472]
**What would you like to be added**:

Today there are several actions to setup kind in your GitHub Workflow.

- [By Helm ](https://github.com/marketplace/actions/kind-cluster)
- [By Container-tools](https://github.com/marketplace/actions/kubernetes-kind-cluster)
- [By Engineerd](https://github.com/marketplace/actions/kind-kubernetes-in-docker-action)
- [By ajayk](https://github.com/marketplace/actions/kind-kubernetes-in-docker-updated-action)

But none of them is officially maintained by kubernetes-sigs .

**Why is this needed**:

It would be nice to have an official kubernetes-sigs/setup-kind.

It would provide an up to date installation for kind-version and the already packaged configuration for metalLB or local-registry according to the official documentation.

I would be very interested to contribute to this project.

**Comment by aojea** [comment]
> It would be nice to have an official kubernetes-sigs/setup-kind.
>  already packaged configuration for metalLB or local-registry 

kind is widely used and with a lot of different options so this will end in a. lot of knobs and setups, per example, you mention metalLB, but people can use the cloud-provider-kind to offer a more similar loadbalancer experience to cloud providers in their kind clusters https://github.com/kubernetes-sigs/cloud-provider-kind

I think is better for the ecosystem that new projects flourish and users decide based on the adoption, instead of us favoring one project

Thanks for the offer
