### ISSUE TITLE
Unable to find a approach to using LoadBalancer on mac m1/2

### ISSUE THREAD

**Issue by zesiar0** [kubernetes-sigs/kind#3482]
I have tried the following two guides, but it's still not working for me
https://kind.sigs.k8s.io/docs/user/loadbalancer/
https://www.thehumblelab.com/kind-and-metallb-on-mac/

So is it any ways to use LoadBalancer on mac m1/m2 ?

**Comment by ashraf-minhaj** [comment]
I also tried MetalLb but as it seems (from forums I read) docker does not expose it's network on mac. That's why it's not possible. Still looking for ideas to implement load balancers in my local machine.

**Comment by kundan2707** [comment]
On macOS and Windows, docker does not expose the docker network to the host. Because of this limitation, containers (including kind nodes) are only reachable from the host via port-forwards, however other containers/pods can reach other things running in docker including loadbalancers. You may want to check out the [Ingress Guide](https://kind.sigs.k8s.io/docs/user/ingress) as a cross-platform workaround. You can also expose pods and services using extra port mappings as shown in the extra port mappings section of the [Configuration Guide](https://kind.sigs.k8s.io/docs/user/configuration#extra-port-mappings).

**Comment by BenTheElder** [comment]
Also very rough and WIP: https://github.com/kubernetes-sigs/cloud-provider-kind, theoretically eventually this may bridge that gap.

If you use metallb on a mac you'll be limited to interacting with it from within the docker VM because of limits in docker networking, as noted int he guide.

More recently there is this suggestion https://github.com/kubernetes-sigs/kind/issues/3448 but we haven't had a chance to review it

**Comment by electrocucaracha** [comment]
> Also very rough and WIP: https://github.com/kubernetes-sigs/cloud-provider-kind, theoretically eventually this may bridge that gap.
> 
> If you use metallb on a mac you'll be limited to interacting with it from within the docker VM because of limits in docker networking, as noted int he guide.
> 
> More recently there is this suggestion #3448 but we haven't had a chance to review it

@BenTheElder I'm not sure if using `Docker Mac net connect` approach can work, given that the service is listening for [Docker network creation events](https://github.com/chipmk/docker-mac-net-connect/blob/v0.1.3/main.go#L206-L214) to add routes to the host.

**Comment by BenTheElder** [comment]
I would currently recommend https://github.com/kubernetes-sigs/cloud-provider-kind and we have updated https://kind.sigs.k8s.io/docs/user/loadbalancer/ to reflect that since this issue was filed.

**Comment by BenTheElder** [comment]
mac is supported, if you run into issue please file one at https://github.com/kubernetes-sigs/cloud-provider-kind

**Comment by ddodoo** [comment]
It's still no working for me @BenTheElder 

Kindly refer to the issue I created: https://github.com/kubernetes-sigs/cloud-provider-kind/issues/220
