### ISSUE TITLE
Access from pod to host os network

### ISSUE THREAD

**Issue by adrianatrevinoe** [kubernetes-sigs/kind#3496]
Hello! 
I am using a docker image inside a kubernetes pod, all run with kind. 
I am setting up several virtual can buses and sending traffic through them in my host os (ubuntu 20:04).
When I used just my docker image I ran docker run --network="host" and that created the "bridge" from my host os to the image, so if i went to my docker container and did ifconfig -a | grep can i could see the same virtual buses from my host os and my container set up. 

I tried doing this with kubernetes by adding to my deployment yaml hostNetwork: true but the communication of the virtual buses  is not being made inside my pod, what could I do for this?
Thank you!

**Comment by BenTheElder** [comment]
On linux with `docker-ce` (not docker desktop), kind will be on a bridge network named `kind` and you should be able to reach the node IPs from teh host, from the nodes you can then reach the pods.

Going the other direction you have to hit the node network's bridge IP or other non-local IPs since loopback is local to the nodes. The nodes are not on the host's network directly and we will not support that (it wouldn't work right for multiple clusters or nodes anyhow if they were in host net, you could run a single node by just using `kubeadm init` directly on the host instead).

**Comment by adrianatrevinoe** [comment]
ok thankyou! so i just need to bridge my can bus messages to the specific ip for the pod? :)

**Comment by BenTheElder** [comment]
> ok thankyou! so i just need to bridge my can bus messages to the specific ip for the pod? :)

Sorry, I really don't know about your can bus, but ... it's roughly the same problem as getting any docker container on a bridge network to access the service. It's not particularly kind specific, I would recommend trying with a more trivial container on the network and working from there.
