### ISSUE TITLE
Adding kind exec feature to execute into cluster control plane shell

### ISSUE THREAD

**Issue by shinunandakumar** [kubernetes-sigs/kind#3665]
**What would you like to be added**: Adding kind exec feature to execute into cluster control plane shell

**Why is this needed**: If we have to debug something in the control plane we have to use docker / podman exec command,
instead of that, it is good to have a feature like this.

**Comment by BenTheElder** [comment]
> Why is this needed: If we have to debug something in the control plane we have to use docker / podman exec command,
instead of that, it is good to have a feature like this.

Hmm, we're generally expecting that you should use the Kubernetes API unless you're manually tinkering on Kubernetes itself, in which case ... docker exec should be sufficient? They're still docker containers, ultimately.

For end-user debugging, we generally expect `kind export logs` + `kubectl` to be sufficient. Wherever possible we encourage portable, conformant APIs.

You can do quite a lot with a debug pod typically, unless you're modifying Kubernetes source to contribute to the project and have broken kubelet, in which case interactive debugging with docker exec is expected and seems pretty sufficient ...?

What's the use case, more concretely?

**Comment by stmcginnis** [comment]
I've been trying to think through if there's a use case I'm not grasping here, so a little more detail might be useful. But this would require adding quite a bit of logic to `kind` to support this. There are things to consider like how should it behave when there are multiple control plane nodes? Do we want to be able to specify an individual node? Or just always connect with the first one found?

It complicates the user experience and would add a lot of code to maintain. I can't really see how that would be better than the two commands needed to do this now:

```
docker ps
docker exec -it $CONTAINER bash
```

**Comment by shinunandakumar** [comment]
Well if that's the case, then it's fine, I just thought it would very straightforward to exec into kind cluster, without knowing the understanding container technology and even docker and k8s provides and exec command.
Now that you've said about it I understand your concerns and yes there's no need of having this feature for now.
Thanks you

**Comment by BenTheElder** [comment]
I would encourage only exec-ing into the container if you're working on the underlying technologies, if you're working on a Kubernetes application you should be able to debug it with `kubectl` without depending on non-portable functionality.

FWIW: kind nodes are named 1:1 between the container runtime and kubernetes, so if you do `kubectl get nodes` it will match `kind get nodes` and what you see in `docker ps`, I don't think `kind exec` can be much simpler than `docker exec` and still be useful, and generally in Kubernetes you should not expect to have direct exec to the nodes, instead you can create a pod and `kubectl exec` in the pod.

**Comment by shinunandakumar** [comment]
Sure will keep that in mind
