### ISSUE TITLE
kind-node: add support for ping command 

### ISSUE THREAD

**Issue by cyclinder** [kubernetes-sigs/kind#3710]
**What would you like to be added**:

Add support for ping command

```
root@spider-control-plane:/# ping
bash: ping: command not found
```

**Why is this needed**:

I want to test the connection of the node and pod by using the ping command, but I found `ping` is not found.

**Comment by stmcginnis** [comment]
You can [build your own node image](https://kind.sigs.k8s.io/docs/user/quick-start/#building-images) with the additional tooling you want to use.

Or if you want to test from within the running cluster, you can run a testing image like busybox or one of the distros where you can install additional packages. You can also use [kubectl debug](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_debug/) to troubleshoot an existing pod.

You can also use `docker run --network kind` to test things at the Docker container level within the same network as the kind containers.

The kind images themselves try to be as minimal as possible. I don't believe we want to add more packages like this when the majority of the time it will not be needed.

**Comment by BenTheElder** [comment]
NOTE: ping is not a very useful tool in Kubernetes generally, ICMP is not supported by pod networking generally.

We only add essential tooling to the base image, because every user has to pay for the image size.
You should not depend on the contents of the node images other than kind can create working clusters with them, you can instead use the suggestions above by @stmcginnis for other ways to debug the network.
