### ISSUE TITLE
Release linux/s390x binaries

### ISSUE THREAD

**Issue by regel** [kubernetes-sigs/kind#3754]
**What would you like to be added**:

kind is available for many architectures, however, linux/s390x binaries are missing in Releases.

**Why is this needed**:

Ongoing work with IBM team; automation of Helm Chart testing for several architectures; we do have CI pipelines that use temporary kind clusters for automated system tests. The linux/s390x binaries are missing in Releases.

**Comment by BenTheElder** [comment]
We dropped these architectures because of excessive time and flakiness in the build processes.

Can you please elaborate more on your use case?

> Ongoing work with IBM team

Does this mean IBM employees?

We _just_ had a meeting this morning in SIG Release about potentially not building these architectures by default in kubernetes core, for similar reasons.

**Comment by BenTheElder** [comment]
See: https://github.com/kubernetes-sigs/kind/pull/3129

I think we're relatively unlikely to add back a platform that Kubernetes does not test, that we cannot test, that introduces more work for us to maintain with relatively little demand, that Kubernetes itself is actively considering dropping from the default release artifacts.

**Comment by BenTheElder** [comment]
If this is about https://github.com/helm/chart-testing/issues/682 ... Note that unless helm has s390x hardware available, kind support is not enough to actually test it on s390x, kind clusters do not create VMs, and cross-architecture container running is typically done in a way that only partially emulates and does not work for workloads that make the sorts of syscalls kind does. That isn't kind specific. A trivial process can be run across architectures with binfmt_misc + qemu user static (as docker desktop does) but that won't work once you start to make platform specific syscalls, because it only emulates userspace.

**Comment by tao12345666333** [comment]
FYI: [[URGENT] Proposal to Stop Building and Releasing Artifacts for mips64le, ppc64le, and s390x](https://groups.google.com/g/kubernetes-announce/c/04Ha9fBxSBI/m/zguHNNpdBAAJ)

**Comment by aojea** [comment]
I think the bottomline is that maintaining a new architecture is a considerable amount of work, so I think the best way to contribute to the community is to setup your own project in github or some place to publish these binaries, and build a community around it, if you find bugs or issues you can always send patches to the projects to fix them, if it has adoption I'm mostly sure the projects will absorb it .... offloading the work to the community is not the solution, maybe companies need to revisit their engagement with OSS, and think that if they want community then they need to invest on them, adding people and resources

**Comment by BenTheElder** [comment]
https://groups.google.com/d/msgid/kubernetes-sig-architecture/CAEHNk2ysE9_4M3OgcNTBAp91pc%3DPTfXZ%3D42xiwCuCYuw81k%2BGg%40mail.gmail.com

I don't think this is something we're going to do at this time.
