### ISSUE TITLE
api service running as anonymous is forbidden

### ISSUE THREAD

**Issue by dan-stock** [kubernetes-sigs/kind#571]
The "kind create cluster" creates a docker cluster but the api is not accessible because the running the "kube-dns:dns" service under the anonymous user is forbidden.

Here is the output when I start open the url for the local cluster. 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kube-dns:dns\" is forbidden: User \"system:anonymous\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "kube-dns:dns",
    "kind": "services"
  },
  "code": 403
}

After a short search there is a way to config the cluster to run but I'm not sure how you would config KIND to run this way.

"kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous"

**Comment by tao12345666333** [comment]
The current version of Kubernetes has RBAC turned on, and the situation you are experiencing is a normal behavior. 

I will close this issue now. If you still have questions about this, please feel free to reopen it. 
/close

**Comment by BenTheElder** [comment]
To elaborate: I think what you're commenting on is the URLs printed out by `kubectl cluster-info`, which is just meant to show that the cluster is running and where the endpoints are. They do not support unathenticated access, and won't for other recent clusters either.

These endpoints are meant to be used by something like `kubectl` using the contents of the KUBECONFIG file. With kind this currently should mean TLS certs for authentication.

They are _not_ browsable by simply clicking them,

We should consider suggesting a different command rather than `kubectl cluster-info` I suppose, but this "issue" is generic to any currently supported Kubernetes cluster.
