### ISSUE TITLE
Why service does not have any active Endpoint when install grafana from helm to kubernetes-sigs/kind?

### ISSUE THREAD

**Issue by patsevanton** [kubernetes-sigs/kind#674]
https://github.com/kubernetes-sigs/kind - version 0.4.0
Create kubernetes from kubernetes-sigs/kind

    kind create cluster
    Creating cluster "kind" ...
     ✓ Ensuring node image (kindest/node:v1.15.0) 🖼

kubectl create serviceaccount

    kubectl create serviceaccount --namespace kube-system tiller
    serviceaccount/tiller created

kubectl create clusterrolebinding

    kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
    clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-rule created

kubectl patch deploy 

    kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
    deployment.extensions/tiller-deploy patched

    helm init

    helm install stable/nginx-ingress

    helm install --name grafana stable/grafana --set=ingress.enabled=True,ingress.hosts={grafana.domain.com} --namespace demo --set rbac.create=true

kubectl logs loping-wallaby-nginx-ingress-controller-76d574f8b7-5m6n5

    W0629 17:13:59.709497       6 controller.go:797] Service "demo/grafana" does not have any active Endpoint.
    [29/Jun/2019:17:14:03 +0000]TCP200000.000
    I0629 17:14:45.223234       6 status.go:295] updating Ingress demo/grafana status from [] to [{ }]
    I0629 17:14:45.226343       6 event.go:209] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"demo", Name:"grafana", UID:"228cde81-cb97-4313-ad86-90a273b2206d", APIVersion:"extensions/v1beta1", ResourceVersion:"1938", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress demo/grafana

kubectl get ingress --all-namespaces

    NAMESPACE   NAME      HOSTS                ADDRESS   PORTS   AGE
    demo        grafana   grafana.domain.com             80      3m58s

kubectl get svc --all-namespaces -l app=grafana

    NAMESPACE   NAME      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
    default     grafana   ClusterIP   10.104.203.243   <none>        80/TCP    24m

kubectl get endpoints 

    NAME                                           ENDPOINTS                      AGE
    grafana                                        10.244.0.10:3000               21m
    kubernetes                                     172.17.0.2:6443                56m
    loping-wallaby-nginx-ingress-controller        10.244.0.8:80,10.244.0.8:443   48m
    loping-wallaby-nginx-ingress-default-backend   10.244.0.7:8080                48m

Thanks!

**Comment by BenTheElder** [comment]
:wave: 

Hey so, your service does in fact have an active clusterIP, but there's no external IP because that would require a loadbalancer implementation.

Kubernetes does not ship a LoadBalancer or Ingress implementation out of the box, and kind does not have one yet* We may add one in the future, but it will be a little less trivial than you'd suspect in order to handle docker for mac etc.

Ideally the app should not depend on an external IP, as this is not even a kubernetes conformance requirement (and kind is fully comformant).

For sending traffic to services, an ingress can be installed or a nodePort can be used directly using: 

https://kind.sigs.k8s.io/docs/user/quick-start/#mapping-ports-to-the-host-machine

* we do have an external LB for HA mode, but that's a bit different.

**Comment by BenTheElder** [comment]
tracking LB in https://github.com/kubernetes-sigs/kind/issues/702
