### ISSUE TITLE
KinD fails to start on GKE with DinD

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#677]
**What happened**:
I have two GKE nodes. I am running into two separate problems with them. 

On node 1, KinD fails to start with `Error: failed to create cluster: failed to apply overlay network: exit status 1`. Full logs attached.
On node 2, the control plane seems to be in an unhealthy state:

```
NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE
kube-system   etcd-test-control-plane                      1/1     Running   20         10m
kube-system   kube-apiserver-test-control-plane            1/1     Running   20         10m
kube-system   kube-controller-manager-test-control-plane   1/1     Running   20         10m
kube-system   kube-scheduler-test-control-plane            1/1     Running   20         10m
```

Note the 20 restarts in 10m, they also don't seem to go into crashloopbackoff, maybe intended though.

Logs show

```
E0701 14:41:23.412993       1 controller.go:148] Unable to remove old endpoints from kubernetes service: no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
E0701 14:42:55.880979       1 autoregister_controller.go:193] v1alpha1.certmanager.k8s.io failed with : apiservices.apiregistration.k8s.io "v1alpha1.certmanager.k8s.io" already exists
E0701 14:42:55.881134       1 autoregister_controller.go:193] v1alpha3.networking.istio.io failed with : apiservices.apiregistration.k8s.io "v1alpha3.networking.istio.io" already exists
E0701 14:42:55.881221       1 autoregister_controller.go:193] v1alpha1.authentication.istio.io failed with : apiservices.apiregistration.k8s.io "v1alpha1.authentication.istio.io" already exists
E0701 14:42:55.881253       1 autoregister_controller.go:193] v1alpha2.config.istio.io failed with : apiservices.apiregistration.k8s.io "v1alpha2.config.istio.io" already exists
```

I consistently get the same errors on the same nodes. I only have 2 nodes in my cluster.

**What you expected to happen**:

KinD successfully creates a cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Not exactly sure. It seems related to something with the image we are using, prow, or GKE, or something. See http://prow.istio.io/?job=istio-kind-simpleTest-master for a host of failures, including the `failed to apply overlay network` one (https://k8s-gubernator.appspot.com/build/istio-prow/logs/istio-kind-simpleTest-master/358). Note that link is *not* from my runs, that is a separate cluster attempting to do the same thing I am doing (run tests on prow with KinD).

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): v0.3.0. 
- Kubernetes version: (use `kubectl version`): 1.15
- Docker version: (use `docker info`): 18.06.1-ce
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

It's running in image gcr.io/istio-testing/istio-builder:v20190628-31457b43 on a GKE cluster.

I still have the nodes up if you need anymore debugging info

* [node1.log](https://github.com/kubernetes-sigs/kind/files/3346343/node1.log) shows failure to start
* [node2.log](https://github.com/kubernetes-sigs/kind/files/3346342/node2.log) shows succesful start on node 2
[kube-node2.log](https://github.com/kubernetes-sigs/kind/files/3346379/kube-node2.log) shows some attempts at getting logs from the crashing api server on node 2. Not sure if there is a better way since the logs come from the api server which is crashing.

**Comment by howardjohn** [comment]
Got the kind logs on node 2
[kind-logs.zip](https://github.com/kubernetes-sigs/kind/files/3346405/kind-logs.zip)

**Comment by howardjohn** [comment]
I think its related to https://github.com/kubernetes-sigs/kind/issues/303, trying out the steps there

**Comment by BenTheElder** [comment]
Quick comment: in addition to 303 ensure docker storage is a volume (eg emptyDir), typically /var/lib/docker

**Comment by howardjohn** [comment]
Got it working with those, thanks, seems to be running smoothly now!

Big +1 on #303 though

**Comment by BenTheElder** [comment]
I hear you on #303, just juggling priorities, glad you got it working! :sweat_smile:

will add a note about dind to 303 as well

**Comment by yeldhomathew** [comment]
I am also trying to run KIND from a POD and getting error below

kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.33.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✗ Starting control-plane 🕹️ 
Deleted nodes: ["kind-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0729 18:31:11.772070     234 initconfiguration.go:261] loading configuration from "/kind/kubeadm.conf"
W0729 18:31:11.772843     234 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "ClusterConfiguration"). Please use 'kubeadm config migrate --old-config old-config-file --new-config new-config-file', which will write the new, similar spec using a newer API version.
W0729 18:31:11.773622     234 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "InitConfiguration"). Please use 'kubeadm config migrate --old-config old-config-file --new-config new-config-file', which will write the new, similar spec using a newer API version.
W0729 18:31:11.774191     234 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "JoinConfiguration"). Please use 'kubeadm config migrate --old-config old-config-file --new-config new-config-file', which will write the new, similar spec using a newer API version.
W0729 18:31:11.774564     234 initconfiguration.go:362] [config] WARNING: Ignored configuration document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.33.1
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0729 18:31:11.776780     234 certs.go:112] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I0729 18:31:11.919141     234 certs.go:473] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kind-control-plane kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost] and IPs [10.96.0.1 172.18.0.2 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
I0729 18:31:12.810879     234 certs.go:112] creating a new certificate authority for front-proxy-ca
[certs] Generating "front-proxy-ca" certificate and key
I0729 18:31:13.208562     234 certs.go:473] validating certificate period for front-proxy-ca certificate
[certs] Generating "front-proxy-client" certificate and key
I0729 18:31:13.241549     234 certs.go:112] creating a new certificate authority for etcd-ca
[certs] Generating "etcd/ca" certificate and key
I0729 18:31:13.311627     234 certs.go:473] validating certificate period for etcd/ca certificate
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [kind-control-plane localhost] and IPs [172.18.0.2 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [kind-control-plane localhost] and IPs [172.18.0.2 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
I0729 18:31:14.745352     234 certs.go:78] creating new public/private key files for signing service account users
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
I0729 18:31:14.979299     234 kubeconfig.go:111] creating kubeconfig file for admin.conf
[kubeconfig] Writing "admin.conf" kubeconfig file
I0729 18:31:15.152230     234 kubeconfig.go:111] creating kubeconfig file for super-admin.conf
[kubeconfig] Writing "super-admin.conf" kubeconfig file
I0729 18:31:15.350317     234 kubeconfig.go:111] creating kubeconfig file for kubelet.conf
[kubeconfig] Writing "kubelet.conf" kubeconfig file
I0729 18:31:15.509020     234 kubeconfig.go:111] creating kubeconfig file for controller-manager.conf
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
I0729 18:31:15.695436     234 kubeconfig.go:111] creating kubeconfig file for scheduler.conf
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
I0729 18:31:15.906446     234 local.go:66] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
I0729 18:31:15.906533     234 manifests.go:104] [control-plane] getting StaticPodSpecs
I0729 18:31:15.906980     234 certs.go:473] validating certificate period for CA certificate
I0729 18:31:15.907090     234 manifests.go:130] [control-plane] adding volume "ca-certs" for component "kube-apiserver"
I0729 18:31:15.907100     234 manifests.go:130] [control-plane] adding volume "etc-ca-certificates" for component "kube-apiserver"
I0729 18:31:15.907106     234 manifests.go:130] [control-plane] adding volume "k8s-certs" for component "kube-apiserver"
I0729 18:31:15.907114     234 manifests.go:130] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-apiserver"
I0729 18:31:15.907118     234 manifests.go:130] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I0729 18:31:15.908534     234 manifests.go:159] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
I0729 18:31:15.908574     234 manifests.go:104] [control-plane] getting StaticPodSpecs
I0729 18:31:15.909141     234 manifests.go:130] [control-plane] adding volume "ca-certs" for component "kube-controller-manager"
I0729 18:31:15.909162     234 manifests.go:130] [control-plane] adding volume "etc-ca-certificates" for component "kube-controller-manager"
I0729 18:31:15.909167     234 manifests.go:130] [control-plane] adding volume "flexvolume-dir" for component "kube-controller-manager"
I0729 18:31:15.909173     234 manifests.go:130] [control-plane] adding volume "k8s-certs" for component "kube-controller-manager"
I0729 18:31:15.909179     234 manifests.go:130] [control-plane] adding volume "kubeconfig" for component "kube-controller-manager"
I0729 18:31:15.909184     234 manifests.go:130] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-controller-manager"
I0729 18:31:15.909188     234 manifests.go:130] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
I0729 18:31:15.910510     234 manifests.go:159] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
I0729 18:31:15.910546     234 manifests.go:104] [control-plane] getting StaticPodSpecs
I0729 18:31:15.910885     234 manifests.go:130] [control-plane] adding volume "kubeconfig" for component "kube-scheduler"
I0729 18:31:15.911865     234 manifests.go:159] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
I0729 18:31:15.911922     234 kubelet.go:70] Stopping the kubelet
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
I0729 18:31:16.089417     234 loader.go:402] Config loaded from file:  /etc/kubernetes/admin.conf
I0729 18:31:16.090139     234 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0729 18:31:16.090172     234 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0729 18:31:16.090180     234 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0729 18:31:16.090184     234 envvar.go:172] "Feature gate default state" feature="InOrderInformers" enabled=true
I0729 18:31:16.090190     234 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests"
[kubelet-check] Waiting for a healthy kubelet at http://127.0.0.1:10248/healthz. This can take up to 4m0s
[kubelet-check] The kubelet is not healthy after 4m0.000340795s

Unfortunately, an error has occurred, likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

The HTTP call equal to 'curl -sSL http://127.0.0.1:10248/healthz' returned error: Get "http://127.0.0.1:10248/healthz": context deadline exceeded

k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient.(*KubeWaiter).WaitForKubelet.func1
        k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient/wait.go:401
k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient.(*KubeWaiter).WaitForKubelet.func2
        k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient/wait.go:418
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2
        k8s.io/apimachinery/pkg/util/wait/loop.go:87
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
        k8s.io/apimachinery/pkg/util/wait/loop.go:88
k8s.io/apimachinery/pkg/util/wait.PollUntilContextTimeout
        k8s.io/apimachinery/pkg/util/wait/poll.go:48
k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient.(*KubeWaiter).WaitForKubelet
        k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient/wait.go:405
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:87
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:132
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:283
runtime.goexit
        runtime/asm_amd64.s:1700
failed while waiting for the kubelet to start
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:89
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:132
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:283
runtime.goexit
        runtime/asm_amd64.s:1700
error execution phase wait-control-plane
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:262
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:132
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:283
runtime.goexit
        runtime/asm_amd64.s:1700

#Below is my docker image

FROM ubuntu:22.04
RUN  apt-get update
RUN  apt-get install -y ca-certificates
RUN  apt-get install -y curl
RUN  apt-get install -y socat
RUN  install -m 0755 -d /etc/apt/keyrings
RUN  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
RUN  chmod a+r /etc/apt/keyrings/docker.asc
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
   tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN  apt-get update
RUN apt-get install -y docker-ce docker-ce-cli containerd.io
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs
RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
RUN chmod +x ./kind
RUN mv ./kind /usr/local/bin/kind
RUN useradd -m -s /bin/bash k8suser && echo 'k8suser:YourPasswordHere' | chpasswd
RUN curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin/
RUN curl -fOL https://github.com/coder/code-server/releases/download/v4.17.1/code-server-4.17.1-linux-amd64.tar.gz \
    && tar -xzf code-server-4.17.1-linux-amd64.tar.gz \
    && mv code-server-4.17.1-linux-amd64 /usr/local/lib/code-server \
    && ln -s /usr/local/lib/code-server/bin/code-server /usr/local/bin/code-server
COPY replacement.js /replacement.js
RUN replacement_code=$(cat /replacement.js) && \
    perl -i.bak -pe "s|Mc\\(ge\\)\\{|${replacement_code}|" /usr/local/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.main.js && \
    pattern=$(grep -o 'this.capabilities.get(2)?.hasInput.*)(100)),' /usr/local/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.main.js) && \
    sed -i "s|$pattern||g" /usr/local/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.main.js

RUN sed -i '/<\/html>/i \
<script> \
    console.log("Script loaded"); \
    function handleMessage(e) { \
        console.log("data", e.data); \
        console.log("message received inside devpod", e.data); \
        const terminalInputEvent = new CustomEvent("terminalInput", { detail: e.data }); \
        document.dispatchEvent(terminalInputEvent); \
    } \
    if (window.addEventListener) { \
        window.addEventListener("message", handleMessage, false); \
        window.addEventListener("keydown", handleKeydown, true); \
    } else if (window.attachEvent) { \
        window.attachEvent("onmessage", handleMessage); \
        window.attachEvent("onkeydown", handleKeydown); \
    } \
</script>' \
/usr/local/lib/code-server/lib/vscode/out/vs/code/browser/workbench/workbench.html
RUN mkdir -p /root/.vscode
COPY .vscode /root/.vscode
EXPOSE 3000
CMD ["sh", "-c", "if [ ! -d /root/.vscode ]; then cp -r /vscode/.vscode /root/.vscode; fi && dockerd & sleep 10 && code-server --bind-addr 0.0.0.0:3000 --auth none /root"]

#Below is my Deployment.yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $deploymentname
  namespace: $namespace
  labels:
    $labelkey: $labelvalue
spec:
  replicas: 1
  selector:
    matchLabels:
      $labelkey: $labelvalue
  template:
    metadata:
      labels:
        $labelkey: $labelvalue
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - $nameserverip1
          - $nameserverip2
      containers:
      - name: $deploymentname
        image: dockerimagewithkindinstalled
        securityContext:
          privileged: true
        ports:
        - containerPort: 3000
        env:
        - name: FOLDER_NAME
          value: $foldername
        args:
        - "sh"
        - "-c"
        - |
          mkdir -p /workspaces/$foldername /workspaces/.internal && \
          dockerd --host=unix:///var/run/docker.sock & \
          sleep 5 && \
          code-server --disable-workspace-trust --host 0.0.0.0 --port 3000 --auth none /workspaces/$foldername
        volumeMounts:
        - name: dind-storage
          mountPath: /workspaces
        - name: vscode-config
          mountPath: /workspaces/$foldername/.vscode
        - name: docker-lib
          mountPath: /var/lib/docker
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        resources:
          requests:
            memory: "8Gi"
            cpu: "4"
          limits:
            memory: "12Gi"
            cpu: "4"
      volumes:
      - name: dind-storage
        persistentVolumeClaim:
          claimName: $PVCname
      - name: vscode-config
        configMap:
          name: vscode-config
      - name: docker-lib
        emptyDir: {}
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory

Is there anything i am missing here

**Comment by BenTheElder** [comment]
@yeldhomathew this issue was closed more than 6 years ago, please use a new support issue, a lot has changed.

That said, for running in a pod see #303, previously linked here. There are a lot of footguns for running kubernetes inside Kubernetes and it's not something we actively recommend.
