### ISSUE TITLE
Is this related to https://github.com/bsycorp/kind

### ISSUE THREAD

**Issue by ensonic** [kubernetes-sigs/kind#71]
Since your project looks newer (by a few days), maybe pick a distinct name? Or at least disambiguate?

**Comment by neolit123** [comment]
ANAT - all names are taken.
there are literally hundreds of projects sharing names in github.

> disambiguate
"this project is not the same https://github.com/bsycorp/kind, but it has a similar scope"

the "open source way" of solving that would be for the smaller project ideas to merge into the larger project and for the smaller project to eventually disappear.

kubernetes-sigs/kind would see a lot more work, with support by the k8s community.

**Comment by BenTheElder** [comment]
I was not aware of https://github.com/bsycorp/kind. This project was in incubation in a directory of https://github.com/kubernetes/test-infra for a while. That is unfortunate...

I see now the readme there mentions https://github.com/kubernetes/test-infra/tree/master/dind, this repo is that cleaned up / rewritten and moved to it's own repo. @munnerz suggested the name as part of cleaning it up sometime last year, I looked around and didn't see this other project then. Naming is hard :(

... We will have to think more about names.

In the meantime the scope does appear to be different, as we're focused on being able to build Kubernetes from source and do not use minikube at all for this, and bringing multi-node back is planned. This is being built in part to test Kubernetes changes.

----

As an aside the readme at bsycorp states:
> Excluding no.1 which uses localkube (which is deprecated), both no.2 and no.3 create a proper cluster, with separate instances for a master and node(s). Because they start a multi node cluster they need to use dind inside dind, creating docker in docker in docker. As you can imagine adding another levels of abstraction can change how things behave, so disk access can be even slower than normal as we are two levels deep. Depending on the setup this can be caused because a fast storage driver like overlay2 can't be used on overlay2, so docker will fall back to slower / more compatiable choices like AUFS (depends on Docker version). It can also have an impact on reliability, if you are hitting docker+kernel edge cases that trigger strange behaviour, it is likely you will see more strange behaviour with docker in docker in docker.

This is not really a problem, both of these solutions avoid this issue by ensuring the docker graph is a volume afaik (at least this project and the old test-infra DinD variant do), so the faster drivers can be used just fine rather than vfs fallback. kubeadm-dind-cluster also only starts one layer of DinD, as does this project currently, they do no more DinD than any other DinD project (though test-infra DinD did) :-) At a glance, bsycorp is also doing DinD...? 🤷‍♂️

----

/assign
/assign @munnerz

**Comment by munnerz** [comment]
Yep, echoing what @BenTheElder says I think this is an unfortunate clash.

We'd started referring to this as 'kind' in Slack chats for quite a long time before anything moved into the public repos, and I think as a result we've ended out landing on the same name 🙈 

It seems both projects do have a similar scope, although not identical by any means.

+1 to having a section comparing alternatives - it'd be helpful for users to disambiguate what does what, and what is best to use for situation X, Y and Z 😄

**Comment by BenTheElder** [comment]
I'm still not sure what else to do here. The name is widely in use at this point and I don't have any better ideas. FWIW while the repo is possibly newer, the project predates the repo, it graduated out of [test-infra](https://github.com/kubernetes/test-infra) over to here.

I'm open to suggestions but for now I'm closing this. We're starting to write more documentation and will outline comparisons when things are more complete. I'd rather not outline how exactly kind compares while we have large changes underway though (like multi-node / HA cluster support inbound, or performance changes to the startup), since by the time users see this it likely won't be true for long at this point.

---

Somewhat related to discussion above: We've made some improvements related to startup time, on my linux workstation it takes <= 40s to create a default cluster currently. I don't expect any local cluster to get too terribly much faster than that.
