### ISSUE TITLE
Support a "bare" node type

### ISSUE THREAD

**Issue by danderson** [kubernetes-sigs/kind#728]
**What would you like to be added**:

In addition to the `control-plane` and `worker` node types, add a `bare` type that creates a "machine" that does not participate in the Kind k8s cluster, but is still included in the cluster's lifecycle (i.e. `kind delete cluster` destroys the bare node container).

**Why is this needed**:

I'm revisiting running MetalLB's end to end tests on kind, as Docker's networking in practice gives me 80% of the behaviors I need to test, and kind is _very_ easy to use compared to my VM-based alternatives.

One somewhat unusual requirement for MetalLB tests is that I need a "client" machine that sits on the same network as the k8s nodes, but is not part of the k8s cluster. This is because I'm testing the behavior of LoadBalancers, and the packet datapath varies hugely for traffic sources outside the cluster vs. inside. Specifically, client traffic should come from a "machine" that's never had `kube-proxy` or the CNI addon messing with it.

I can trivially do this myself with `docker run -d --cap-add=NET_ADMIN --name=client debian:stable /bin/bash -c "while true; do sleep 600; done"`, and then `docker exec` into that container to run things as needed. However, with this method, the `client` container isn't tied to the lifetime of the kind cluster, so it's very easy to get desynchronized with leftover dirty state.

I'd like the ability to tie this "bare" node's lifecycle to the kind cluster's, so I can express to kind "I need a 2-node k8s cluster, and also one more machine that's not in the k8s cluster". I only want kind to create/delete this container, other kind operations (e.g. loading docker images) should just ignore these extra nodes.

WDYT? I realize this is a somewhat peripheral use case for kind. At the same time, it _feels_ like it should be possible with minimal complexity cost. I'd love to hear what you think.

**Comment by BenTheElder** [comment]
So I think the problem with this is that we'd need to be very flexible about specifying the "node" container options etc. and ignore kubernetes node specific fields (which we'll be getting more of shortly).

I'm rather hesitant of becoming a weird "docker-compose" especially as we backend to more node options (podman, ignite ... kata?) however:

> I'd like the ability to tie this "bare" node's lifecycle to the kind cluster's, so I can express to kind "I need a 2-node k8s cluster, and also one more machine that's not in the k8s cluster". I only want kind to create/delete this container, other kind operations (e.g. loading docker images) should just ignore these extra nodes.

If you're OK still _creating_ this container yourself and want to simplify cleanup / have kind handle it, kind actually cleans up resources by looking for anything tagged as owned by the cluster by cluster name.

Currently this is done with `--label io.k8s.sigs.kind.cluster=${CLUSTER_NAME}`. During `kind delete cluster` we list objects with this label in the underlying runtime (currently just docker containers). If you label your extra containers this way then kind should already remove them during cluster deletion.

Minor Disclaimer: this label key _might_ need to change in the future due to API review restrictions around what goes in to *.k8s.io API wise, but since this would be a breaking change anyhow we'd document that and have a period where we supported the old *.k8s.io and the new (x-k8s.io?) labels etc.

**Comment by BenTheElder** [comment]
That label isn't exactly a public detail at the moment, but it's hardly hidden and breaking it and the deletion behavior around it would be a compatibility change. 

Short of possibly having a migration period to x-k8s.io or similar domain / namespace at some point I don't expect that to change.

**Comment by aojea** [comment]
I think that `kinder` is doing something along those lines @danderson https://github.com/kubernetes/kubeadm/tree/master/kinder

**Comment by BenTheElder** [comment]
@ajoea not quite, they're sometimes using some kind functionality to create kubernetes nodes that stop short of running kubeadm init etc., they're still kind node images running a nested container runtime etc., not "bare" nodes, but rather "partially provisioned" nodes.

Also note though that kinder is primarily meant for kubeadm development rather than consumption for other projects.

**Comment by danderson** [comment]
I completely agree with wanting to avoid scope creep on kind, and that a `bare` node type increases the risk of that.

Using a label to tie my container(s) to the lifetime of the kind cluster is great, and will work just fine for me. As you said, my main concern was cleanup rather than creation.

If I (and others who find this bug) start relying on labels for lifecycle control, this effectively becomes a de-facto standard API for kind. Are you okay with that, or do you want to take this opportunity to explicitly promise nothing about the future of these labels? :)

**Comment by danderson** [comment]
I think this should be closed, as far as I'm concerned. The labeling approach is fine for my needs, and there's good reason to want to avoid the scope creep on kind. @BenTheElder anything else to add, or should I just close this?

**Comment by BenTheElder** [comment]
SGTM :-)

I think the defacto API already exists for containers at least, we'd have to be careful changing that or otherwise not be able to clean up clusters from previous versions.

We probably will have that transition period to re-key them into the "less official" x-k8s.io namespace though (much as I don't particularly love that name, see the discussions around API review and guidance for unofficial / non-core APIs ...).
