### ISSUE TITLE
Update the docker version to maximum validated version 18.06

### ISSUE THREAD

**Issue by warmchang** [kubernetes-sigs/kind#85]
Looks like kubernetes support the maximum validated docker is 18.06 now:
https://github.com/kubernetes/website/pull/10299
https://github.com/kubernetes/test-infra/pull/9444
https://github.com/kubernetes/kubernetes/pull/68495
https://kubernetes.io/docs/setup/cri/#docker
> On each of your machines, **install Docker. Version 18.06 is recommended**, but 1.11, 1.12, 1.13 and 17.03 are known to work as well. Keep track of the latest verified Docker version in the Kubernetes release notes.

So we can update the docker version to 18.06 in images/base/Dockerfile. :smiley: 
https://github.com/kubernetes-sigs/kind/blob/c007d6da085ce96f8b95d2c310908fd4fd4a97f0/images/base/Dockerfile#L78-L80

**Comment by BenTheElder** [comment]
/cc @munnerz 
Probably we should also consider switching to an Ubuntu base image too so that:
- we can use newer systemd without hacks
- we don't circularly depend on an image from k/k
- we can use the Ubuntu guides for install
... But still use the Debian package logic we have setup.

I think the 18.04 image should be small enough. 

This docker version was the main reason for using debian-base. We used that one due to validation from sig-node, but I agree we should upgrade 👍

/assign
/kind cleanup
/lifecycle active

**Comment by neolit123** [comment]
> Update the docker version to maximum validated version 18.06

validated by k8s consumers and contributors.
AFAIK sig-node will no longer do that validation process they were doing for previous releases.

**Comment by warmchang** [comment]
> AFAIK sig-node will no longer do the validation process they were doing for previous releases.

The PR https://github.com/kubernetes/test-infra/pull/9444 in project test-infra added Docker 18.06 to the CI tests.

And an other PR https://github.com/kubernetes/test-infra/pull/9379 from BenTheElder upgraded docker in bootsrap to 18.06 (Please ignore the comment and issue 6187 has been fixed.):

![image](https://user-images.githubusercontent.com/13084624/47761735-8a95bc80-dcf4-11e8-8ee3-07f85c618d10.png)

https://github.com/kubernetes/test-infra/blob/f97e35a467fdfbc3bb50fed8d5be9328cf62c02a/images/bootstrap/Dockerfile#L102

**Comment by neolit123** [comment]
yes, i saw these when they merged, we do have 18.06 test signal.
but it's not the same sig-node validation.

**Comment by warmchang** [comment]
ok, i understand.

**Comment by BenTheElder** [comment]
Done in https://github.com/kubernetes-sigs/kind/pull/89
