### ISSUE TITLE
kind doesn't work at all when icc == false in docker daemon configuration

### ISSUE THREAD

**Issue by szubersk** [kubernetes-sigs/kind#859]
icc == false in dockerd configuration makes any 2+ nodes cluster configuration to fail to boot because of lack of communication between containers (kind attaches the default docker bridge network to all its containers which disallows any network traffic when icc == false). there are 2 way to go about it:

(1) make user set dockerd icc to true and restart the docker daemon (fishy and ugly)
(2) use dedicated network by default (let's say 'kind') and add appropriate flag to 'kind create cluster' e. g. --network-name <name> analogical to --name.

Solution (1) above confirmed by manipulatic icc value in daemon.json.

**Comment by aojea** [comment]
I don't know if this should be considered as an issue, from docker documentation if icc=false containers are not allowed to communicate, thus kind multinode can't work because of they need connectivity.

@szubersk if 1 works, what do you suggest? to document it as a known issue?

**Comment by szubersk** [comment]
This is an issue!

What icc does is it blocks communication between containers inside default bridge network (unless they are linked with link command). icc is set due to security reasons (compromising one of the containers doesn't mean the perpetrator has an access to all of the others, not necessarily belonging to the compromised application stack). Containers that are attached to other than default bridge network (e. g. networks create by 'docker network create') can communicate with each other regardless of icc settings (here Docker documentation is very fuzzy on that, an issue on it's own) - please try it out on your dockerd!

What I mean by writing (1) was to provide quick and dirty workaround for users which have icc == false (which is BTW a good practice, also recommended by CIS Benchmarks https://github.com/docker/docker-bench-security) to move on.

What needs to be done in my opinion is, in order:
- user should be warned by documentation that in case of icc == false they won't be able to use kind or they should lower their security by setting icc to true
- kind should always create a separate network for each cluster ('docker network create'). Networks can be named after cluster (like containers are). That way every cluster is in it's own network and there is no need to compromise on icc.

      --name string     cluster context name (default "kind")

**Comment by BenTheElder** [comment]
> This is an issue!

I think Antonio just meant that disabling container to container communication of course does just that. Single node kind will work fine, but of course multi-node won't at the moment.

This issue requires that you both want multi node kind and opt to configure your dockerd to not allow container to container communication which is not the default.

> user should be warned by documentation that in case of icc == false they won't be able to use kind or they should lower their security by setting icc to true

Right, this is currently a limitation. Please file a PR to the known issues page.

> kind should always create a separate network for each cluster ('docker network create'). Networks can be named after cluster (like containers are). That way every cluster is in it's own network and there is no need to compromise on icc.

We have this in the issue tracker in previous issues (on mobile currently, otherwise I'd link them). It's slightly more involved than it sounds unfortunately. We'd like to do this someday.

---

Note also that kind compromises on being a convenient and effective way to get a local cluster. That cluster is very much root on the docker host and the nodes are privileged in order to run everything, similar to if you installed a kubeadm cluster on that host but slightly more isolated. Currently this requires using docker containers in somewhat unusual ways and violating typical security practices.

**Comment by BenTheElder** [comment]
I am going to dedupe this with https://github.com/kubernetes-sigs/kind/issues/273, and call this working as intended until a workable design for using non-default network is worked out. It's on the TODO list, but not as high as fixing other things.

**Comment by BenTheElder** [comment]
FYI we are using user defined networks now.
