### ISSUE TITLE
[macOS] Docker Desktop - after restarting containers k8s cluster doesn't work

### ISSUE THREAD

**Issue by 2-face** [kubernetes-sigs/kind#862]
**What happened**:
kind installed k8s cluster (v1.15.3) and after mac reboot or restarting containers k8s cluster does not work anymore.

**What you expected to happen**:
k8s cluster shall remain working

**How to reproduce it (as minimally and precisely as possible)**:
create a basic 3 node cluster (one controller and 2 workers)

**Anything else we need to know?**:
When cluster got created kind-control-plane node got `172.17.0.3` and all configurations in a control plane node refer to this address. Probably same goes for worker nodes.

**Environment:**

- kind version: (use `kind version`): v0.5.0
- Kubernetes version: (use `kubectl version`): v1.15.3
- Docker version: (use `docker info`): Server Version: 18.09.2
- OS (e.g. from `/etc/os-release`): 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by aojea** [comment]
hi @2-face this is a known issue that is being tracked in https://github.com/kubernetes-sigs/kind/issues/148
short history is that it implies deep changes in kind that can be done right now, I think we can close this as duplicate and track everything in one issue only

**Comment by 2-face** [comment]
Why deep changes? Fixed IP should be a part of `docker run` where kind could just pass a static IP.

**Comment by aojea** [comment]
> Why deep changes? Fixed IP should be a part of `docker run` where kind could just pass a static IP. Here a specific issues is related to the fact that IP is not maintained. Kind while creating a cluster fetches IP using `docker inspect` hence if a static IP was assigned while `run` then appropriate addressing would go into config files (manifests etc).

this implies adding IPAM to kind and keep status on disk, also to not allow docker to assign IP addresses to other containers that can conflict with the ones that kind provide to the nodes.
One approach tried in https://github.com/kubernetes-sigs/kind/issues/148 is creating individual bridges other than the default docker bridge to keep the nodes isolated, but it turned out that you have to deal with the docker dns, that adds one loopback address to the resolv.conf and causes CoreDNS to not work because of the loop prevention mechanism.

Definitively this is something interesting to be implemented, but there are several things that need to be sorted out first, appreciate new ideas and help, but I guess that is better to keep track only in #148 to avoid spreading the info :sweat_smile:

**Comment by BenTheElder** [comment]
yeah, sorry about this, please see https://github.com/kubernetes-sigs/kind/issues/148 for more details. we'll definitely fix this, but someone needs to look into dealing with the DNS and find a reasonable solution. I'm currently working on revamping the entirety of how we manage nodes internally.

closing as a duplicate.
