### ISSUE TITLE
Where are the 1.16 images?

### ISSUE THREAD

**Issue by matthyx** [kubernetes-sigs/kind#863]
@BenTheElder do you have an automated (read CI) way of publishing new images of kindest/node when new binaries are released in k/k?

**Comment by aojea** [comment]
Quoting Ben answer in slack https://kubernetes.slack.com/archives/CEKK1KTN2/p1568828531071900?thread_ts=1568823668.071300&cid=CEKK1KTN2

>  bentheelder  5 days ago

> it's ad-hoc and demand driven at the moment. (mostly around kind releases)
> so far most projects we support directly haven't voiced much demand for it, so I've been monitoring the progress to get automated image pushing tools rolled out to kubernetes projects


Temporarily there are "unofficial" images created nightly here https://github.com/kubernetes-sigs/kind/issues/197#issuecomment-517791203

**Comment by matthyx** [comment]
Thanks @aojea this is exactly what I needed... and I didn't do my homework :-/
I think it's safe to close this one then.
/close

**Comment by BenTheElder** [comment]
Sadly not yet, there's another issue tracking automated publishing.

**Comment by AkihiroSuda** [comment]
any ETA for this?

**Comment by BenTheElder** [comment]
Currently we publish pre-built node images when we're ready to cut a release of the CLI. We're not quite there being in the middle of a few important transitions in HEAD.

In the future this will change but we're chasing many priorities and don't have the secure first party infrastructure for building these. (see the automated publishing issue in the tracker).

We have also fairly recently a lot of problems with users using images that are not compatible with the release they are using (due to necessary changes in the image <-> cli interactions), which has been reduced by clearly publishing images that are expected to work in release notes and otherwise suggesting building images with a matching version of the CLI. I'd like to stop having those and go alpha -> beta, but I'm not confident that we won't need to do that again.

You can build your own image with `kind build node-image` and a kubernetes 1.16 checkout in the meantime.

 I believe @aojea also has some third party infra publishing nightlies.

**Comment by aojea** [comment]
https://github.com/kubernetes-sigs/kind/issues/197#issuecomment-517791203

**Comment by BenTheElder** [comment]
`kindest/node:v1.16.1@sha256:fa06fad0f635401fc0822ae8ad4d81d2b79d8481fc3223c5f48b36d4369d6da6` will be the new temporary default for kind at HEAD, currently https://github.com/kubernetes-sigs/kind/commit/37030ed6aca63c577a7660e483ec42ab87c6f59a.

it has not been tested with other versions.
